import { createServerFn } from "@tanstack/react-start";
import type { JsonValue } from "@/lib/json";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { resolveTenantContext } from "@/lib/tenant-context.server";
import { resolveActor } from "@/lib/execution/gateway.server";
import { executeApprovedAgentRun } from "@/lib/execution/agent-execution-handoff.server";
import { executeApprovedAction } from "@/lib/integrations/github-governed-action.server";
import { recordOperationalIssueSafely } from "@/lib/operational-issues.server";
import { recordAgentLearningOutcome } from "@/lib/agent-learning.functions";
import { assertAgentRunOperator, checkpointAgentRun, requireAgentBudget, sanitizeTracePayload } from "@/lib/agent-execution-controller.server";
import { orchestrateSecurityRun } from "./agent-runtime-orchestrator.server";
import { orchestrateGenericReadOnlyRun } from "./agent-runtime-generic-orchestrator.server";
import { createAgentRunState, transitionAgentRun, type AgentRunState, type AgentRunStep } from "@/lib/agent-runtime";
import type { AgentRunEvent } from "@/lib/agent-run-events";

function runtimeError(error: unknown) { console.error("[agent-runtime] failed", error); return { ok: false as const, error: error instanceof Error ? error.message : "Agent runtime operation failed." }; }
function toPersistedRun(run: AgentRunState) { return { id: run.runId.replace(/^run-/, ""), tenant_id: run.tenantId, agent_key: run.agentKey, status: run.status, current_step: run.currentStep, input: run.input, plan: run.plan, policy_verdict: run.policyVerdict, approval: run.approval, execution: run.execution, verification: run.verification, error: run.error }; }
async function loadRun(supabase: any, tenantId: string, runId: string): Promise<AgentRunState> { const { data, error } = await supabase.from("agent_runs").select("id, tenant_id, agent_key, status, current_step, input, plan, policy_verdict, approval, execution, verification, error, created_at, updated_at").eq("id", runId).eq("tenant_id", tenantId).single(); if (error || !data) throw new Error(error?.message ?? "Agent run was not found."); const { data: evidenceRows, error: evidenceError } = await supabase.from("agent_run_evidence").select("evidence").eq("run_id", runId).eq("tenant_id", tenantId).order("created_at", { ascending: true }); if (evidenceError) throw new Error(evidenceError.message); return { runId: `run-${data.id}`, tenantId: data.tenant_id, agentKey: data.agent_key, status: data.status, currentStep: data.current_step, input: data.input, plan: data.plan, evidence: (evidenceRows ?? []).map((row: { evidence: unknown }) => row.evidence), policyVerdict: data.policy_verdict, approval: data.approval, execution: data.execution, verification: data.verification, error: data.error, createdAt: data.created_at, updatedAt: data.updated_at }; }
async function loadEvents(supabase: any, tenantId: string, runId: string): Promise<AgentRunEvent[]> { const { data, error } = await supabase.from("agent_run_events").select("id, run_id, tenant_id, sequence, event_type, step, actor_id, provider, capability_key, outcome, payload, occurred_at").eq("run_id", runId).eq("tenant_id", tenantId).order("sequence", { ascending: true }); if (error) throw new Error(error.message); return (data ?? []).map((row: any) => ({ id: row.id, runId: row.run_id, tenantId: row.tenant_id, sequence: row.sequence, eventType: row.event_type, step: row.step, actorId: row.actor_id, provider: row.provider, capabilityKey: row.capability_key, outcome: row.outcome, payload: row.payload ?? {}, occurredAt: row.occurred_at })) as AgentRunEvent[]; }
async function appendEvent(supabase: any, event: { runId: string; tenantId: string; actorId: string | null; eventType: AgentRunEvent["eventType"]; step?: AgentRunStep | null; provider?: string | null; capabilityKey?: string | null; outcome?: string | null; payload?: unknown }) { const { data: runMeta } = await supabase.from("agent_runs").select("trace_id").eq("id", event.runId).eq("tenant_id", event.tenantId).maybeSingle(); const { error } = await (supabase as any).rpc("append_agent_run_event", { p_run_id: event.runId, p_tenant_id: event.tenantId, p_actor_id: event.actorId, p_event_type: event.eventType, p_step: event.step ?? null, p_provider: event.provider ?? null, p_capability_key: event.capabilityKey ?? null, p_outcome: event.outcome ?? null, p_payload: sanitizeTracePayload(event.payload ?? {}), p_trace_id: runMeta?.trace_id ?? null }); if (error) throw new Error(error.message); }
async function persistRun(supabase: any, tenantId: string, run: AgentRunState) { const persisted = toPersistedRun(run); const { error } = await supabase.from("agent_runs").update({ status: persisted.status, current_step: persisted.current_step, plan: persisted.plan, policy_verdict: persisted.policy_verdict, approval: persisted.approval, execution: persisted.execution, verification: persisted.verification, error: persisted.error }).eq("id", persisted.id).eq("tenant_id", tenantId); if (error) throw new Error(error.message); }

export const createAgentRun = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { agentKey: string; input: string }) => ({ agentKey: String(input.agentKey ?? "").trim(), input: String(input.input ?? "").trim().slice(0, 6000) })).handler(async ({ data, context }) => { try { if (!data.agentKey) throw new Error("An agent key is required."); if (!data.input) throw new Error("A run input is required."); const tenant = await resolveTenantContext(context.supabase, context.userId); const run = createAgentRunState({ tenantId: tenant.tenantId, agentKey: data.agentKey, input: data.input }); const persisted = toPersistedRun(run); const { data: created, error } = await (context.supabase as any).from("agent_runs").insert({ tenant_id: persisted.tenant_id, agent_key: persisted.agent_key, status: persisted.status, current_step: persisted.current_step, input: persisted.input, plan: persisted.plan, policy_verdict: persisted.policy_verdict, approval: persisted.approval, execution: persisted.execution, verification: persisted.verification, error: persisted.error, created_by: context.userId, deadline_at: new Date(Date.now() + 15 * 60 * 1000).toISOString() }).select("id, created_at, updated_at").single(); if (error || !created) throw new Error(error?.message ?? "Agent run could not be created."); await appendEvent(context.supabase, { runId: created.id, tenantId: tenant.tenantId, actorId: context.userId, eventType: "run_created", step: "plan", outcome: "planned", payload: { agentKey: run.agentKey, input: run.input } }); return { ok: true as const, runId: created.id, status: run.status, currentStep: run.currentStep }; } catch (error) { return runtimeError(error); } });
export const getAgentRun = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { runId: string }) => ({ runId: String(input.runId ?? "").trim() })).handler(async ({ data, context }) => { try { if (!data.runId) throw new Error("A run id is required."); const tenant = await resolveTenantContext(context.supabase, context.userId); const run = await loadRun(context.supabase, tenant.tenantId, data.runId); return { ok: true as const, run, events: await loadEvents(context.supabase, tenant.tenantId, data.runId) }; } catch (error) { return runtimeError(error); } });
export const orchestrateAgentRun = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { runId: string }) => ({ runId: String(input.runId ?? "").trim() })).handler(async ({ data, context }) => { try { if (!data.runId) throw new Error("A run id is required."); const tenant = await resolveTenantContext(context.supabase, context.userId); const run = await loadRun(context.supabase, tenant.tenantId, data.runId); await requireAgentBudget(context.supabase, tenant.tenantId, data.runId, "step");
      const result = run.agentKey === "agent-security"
        ? await orchestrateSecurityRun(context.supabase, context.userId, run)
        : await orchestrateGenericReadOnlyRun(context.supabase, context.userId, run); await persistRun(context.supabase, tenant.tenantId, result.run); await checkpointAgentRun(context.supabase, tenant.tenantId, data.runId, { currentStep: result.run.currentStep, status: result.run.status, evidenceCount: result.run.evidence.length, policyVerdict: result.run.policyVerdict, approval: result.run.approval });
    try {
      await recordAgentLearningOutcome(context.supabase, {
        tenantId: tenant.tenantId,
        agentRunId: data.runId,
        agentKey: result.run.agentKey,
        outcomeType: result.run.status === "failed" ? "run_failed" : "run_completed",
        metadata: {
          status: result.run.status,
          evidenceCount: result.run.evidence.length,
          currentStep: result.run.currentStep,
          warnings: "warnings" in result ? result.warnings : [],
          verification: result.run.verification,
        },
        createdBy: context.userId,
      });
    } catch (learningError) {
      console.error("[agent-runtime] learning outcome ledger write failed", learningError);
    }
    if (result.run.evidence.length > run.evidence.length) await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "stage_completed", step: "investigate", outcome: "completed", payload: result.run.evidence[result.run.evidence.length - 1] }); if (result.run.policyVerdict !== null && run.policyVerdict === null) await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "stage_completed", step: "policy", outcome: "evaluated", payload: result.run.policyVerdict }); if (result.run.status === "waiting_approval" && run.status !== "waiting_approval") await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "approval_requested", step: "approval", outcome: "pending", payload: result.run.approval }); if (result.run.status === "failed" && run.status !== "failed") { await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "run_failed", step: run.currentStep, outcome: "failed", payload: { error: result.run.error } }); await recordOperationalIssueSafely(context.supabase, { tenantId: tenant.tenantId, source: "agent_run", severity: "high", title: `${run.agentKey} run failed`, detail: result.run.error ?? "The agent run failed without an error detail.", relatedId: data.runId }); } return { ok: true as const, ...result, events: await loadEvents(context.supabase, tenant.tenantId, data.runId) }; } catch (error) { return runtimeError(error); } });
export const executeAgentRun = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { runId: string; changeRecordId: string }) => ({ runId: String(input.runId ?? "").trim(), changeRecordId: String(input.changeRecordId ?? "").trim() })).handler(async ({ data, context }) => { try { if (!data.runId || !data.changeRecordId) throw new Error("A run id and approved change record id are required."); const tenant = await resolveTenantContext(context.supabase, context.userId); await assertAgentRunOperator(context.supabase, tenant.tenantId, context.userId, data.runId); const actor = await resolveActor(context.supabase, context.userId); const outcome = await executeApprovedAgentRun(context.supabase, actor, data, async ({ supabase, actor: executionActor, change }) => {
      if (change.provider !== "github") throw new Error(`Provider mutation is not implemented for ${change.provider ?? "this provider"}; execution was denied rather than simulated.`);
      const result = await executeApprovedAction(supabase, executionActor, change.rowId);
      if (!result.ok) throw new Error(result.reasons.join(" "));
      return result.result;
    }); const run = await loadRun(context.supabase, tenant.tenantId, data.runId); if (!outcome.ok) { const failed = transitionAgentRun(run, { type: "fail", error: outcome.reasons.join(" ") }); await persistRun(context.supabase, tenant.tenantId, failed); await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "run_failed", step: "execute", outcome: "failed", payload: { decision: outcome.decision, reasons: outcome.reasons, requiredActions: outcome.requiredActions } }); return { ok: false as const, decision: outcome.decision, reasons: outcome.reasons, requiredActions: outcome.requiredActions, run: failed }; } await requireAgentBudget(context.supabase, tenant.tenantId, data.runId, "step");
    const executing = transitionAgentRun(run, { type: "complete_step", step: "execute", value: outcome.result });
    await requireAgentBudget(context.supabase, tenant.tenantId, data.runId, "step");
    const verified = transitionAgentRun(executing, { type: "complete_step", step: "verify", value: { verified: true, providerReceipt: outcome.result } });
    await persistRun(context.supabase, tenant.tenantId, verified);
    await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "stage_completed", step: "execute", outcome: "completed", payload: outcome.result });
    await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType: "verification_completed", step: "verify", outcome: "verified", payload: { providerReceipt: outcome.result } });
    return { ok: true as const, run: verified, receipt: outcome.result, events: await loadEvents(context.supabase, tenant.tenantId, data.runId) }; } catch (error) { return runtimeError(error); } });
export const advanceAgentRun = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { runId: string; transition: { type: string; step?: string; value?: JsonValue; error?: string; approval?: JsonValue } }) => ({ runId: String(input.runId ?? "").trim(), transition: input.transition })).handler(async ({ data, context }) => { try { const tenant = await resolveTenantContext(context.supabase, context.userId); const run = await loadRun(context.supabase, tenant.tenantId, data.runId); await assertAgentRunOperator(context.supabase, tenant.tenantId, context.userId, data.runId); let transition: Parameters<typeof transitionAgentRun>[1]; switch (data.transition.type) { case "start": transition = { type: "start" }; break; case "resume": transition = { type: "resume" }; break; case "cancel": transition = { type: "cancel" }; break; case "fail": transition = { type: "fail", error: String(data.transition.error ?? "Unknown runtime failure.") }; break; case "await_approval": transition = { type: "await_approval", approval: data.transition.approval ?? { status: "pending" as const } }; break; case "complete_step": { const step = String(data.transition.step ?? "") as AgentRunStep;
      if (step === "approval" && data.transition.value && typeof data.transition.value === "object" && String((data.transition.value as any).status ?? "") === "approved") throw new Error("Approval completion is authoritative only when recorded by Change Control Center."); if (!["plan", "investigate", "policy", "approval", "execute", "verify"].includes(step)) throw new Error("Invalid agent run step."); transition = { type: "complete_step", step, value: data.transition.value }; break; } default: throw new Error("Unsupported agent runtime transition."); } if (transition.type === "complete_step") await requireAgentBudget(context.supabase, tenant.tenantId, data.runId, "step");
      const updated = transitionAgentRun(run, transition);
      await checkpointAgentRun(context.supabase, tenant.tenantId, data.runId, { currentStep: updated.currentStep, status: updated.status, step: transition.type === "complete_step" ? transition.step : null }); await persistRun(context.supabase, tenant.tenantId, updated); const eventType = transition.type === "start" ? "stage_started" : transition.type === "await_approval" ? "approval_requested" : transition.type === "complete_step" ? "stage_completed" : transition.type === "fail" ? "run_failed" : transition.type === "cancel" ? "run_cancelled" : "approval_resolved"; await appendEvent(context.supabase, { runId: data.runId, tenantId: tenant.tenantId, actorId: context.userId, eventType, step: transition.type === "complete_step" ? transition.step : updated.currentStep, outcome: updated.status, payload: transition.type === "fail" ? { error: updated.error } : transition.type === "complete_step" ? transition.value : transition.type === "await_approval" ? transition.approval : {} }); if (updated.status === "failed") await recordOperationalIssueSafely(context.supabase, { tenantId: tenant.tenantId, source: "agent_run", severity: "high", title: `${run.agentKey} run failed`, detail: updated.error ?? "The agent run failed without an error detail.", relatedId: data.runId }); return { ok: true as const, run: updated, events: await loadEvents(context.supabase, tenant.tenantId, data.runId) }; } catch (error) { return runtimeError(error); } });
