// Sensitive change-control actions. Every one of these writes an immutable
// audit entry and emits a tenant notification; Realtime pushes the result to
// every open client.
import { supabase } from "@/integrations/supabase/client";
import type { Json } from "@/integrations/supabase/types";
import { writeAudit } from "@/lib/audit";
import { pushNotification, updateRecords } from "@/lib/realtime";
import { createExternalTicketServer } from "@/lib/integrations/external-ticket.server";

import { CHANGE_STAGES, type ChangeRecord, type ChangeStage, type ChangeTimelineEvent, type ExternalTicket } from "@/lib/change-data";
import { resolveTenantContext } from "@/lib/tenant-context.server";
interface ActorContext { tenantId: string; actor: string; role: string; userId: string; }
async function appendTimeline(record: ChangeRecord, event: ChangeTimelineEvent, extra: { stage?: ChangeStage; externalTickets?: ExternalTicket[] } = {}) { if (!record.rowId) return; await supabase.from("change_records").update({ timeline: [event, ...record.timeline] as unknown as Json, ...(extra.stage ? { stage: extra.stage } : {}), ...(extra.externalTickets ? { external_tickets: extra.externalTickets as unknown as Json } : {}) }).eq("id", record.rowId); }
function nextStage(record: ChangeRecord, allApproved: boolean): ChangeStage | undefined { if (!allApproved) return undefined; const idx = CHANGE_STAGES.indexOf(record.stage); return idx >= 0 && idx < CHANGE_STAGES.length - 1 ? CHANGE_STAGES[idx + 1] : undefined; }
export async function decideChange(record: ChangeRecord, decision: "approved" | "rejected", ctx: ActorContext, comment?: string) {
  const { environmentMode } = await resolveTenantContext(supabase, ctx.userId);
  const now = new Date().toISOString();
  if (environmentMode === "demo") { const stage = nextStage(record, decision === "approved"); updateRecords((records) => records.map((current) => current.id !== record.id ? current : { ...current, stage: stage ?? current.stage, approvals: current.approvals.map((approval) => approval.status === "pending" ? { ...approval, status: decision, timestamp: now, comment: comment ?? `${decision === "approved" ? "Approved" : "Rejected"} by ${ctx.actor} (${ctx.role})` } : approval), timeline: [{ ts: now, actor: ctx.actor, kind: "status", text: decision === "approved" ? `Approval recorded by ${ctx.actor} (${ctx.role}).${stage ? ` Stage advanced to ${stage}.` : ""}` : `Change rejected by ${ctx.actor} (${ctx.role}).` }, ...current.timeline] })); await pushNotification({ tenantId: ctx.tenantId, kind: "approval_deadline", title: `${record.id} ${decision}`, body: `${record.title} — ${decision} by ${ctx.actor} (${ctx.role}).`, href: `/approvals/${record.id}` }); return; }
  const pending = record.approvals.filter((a) => a.status === "pending" && a.rowId); const ids = pending.map((a) => a.rowId!) as string[];
  if (ids.length) { const { error } = await supabase.from("change_approvals").update({ status: decision, decided_at: now, comment: comment ?? `${decision === "approved" ? "Approved" : "Rejected"} by ${ctx.actor} (${ctx.role})` }).in("id", ids); if (error) throw error; }
  const stage = nextStage(record, decision === "approved"); await appendTimeline(record, { ts: now, actor: ctx.actor, kind: "status", text: decision === "approved" ? `Approval recorded by ${ctx.actor} (${ctx.role}).${stage ? ` Stage advanced to ${stage}.` : ""}` : `Change rejected by ${ctx.actor} (${ctx.role}).` }, { stage }); await writeAudit({ tenantId: ctx.tenantId, action: decision === "approved" ? "change.approved" : "change.rejected", entityType: "change_record", entityId: record.id, actorRole: ctx.role, detail: `${record.title} — ${decision} (${ids.length} approval row(s))`, payload: { changeId: record.id, risk: record.risk.tier, executionMode: record.executionMode, approvalsDecided: pending.map((a) => a.team), comment: comment ?? null } }); await pushNotification({ tenantId: ctx.tenantId, kind: "approval_deadline", title: `${record.id} ${decision}`, body: `${record.title} — ${decision} by ${ctx.actor} (${ctx.role}).`, href: `/approvals/${record.id}` });
}
export async function bulkDecideChanges(records: ChangeRecord[], decision: "approved" | "rejected", ctx: ActorContext) { for (const record of records) await decideChange(record, decision, ctx, `Bulk ${decision} by ${ctx.actor} (${ctx.role})`); if (!environmentMode === "demo") await writeAudit({ tenantId: ctx.tenantId, action: decision === "approved" ? "change.bulk_approved" : "change.bulk_rejected", entityType: "change_record", actorRole: ctx.role, detail: `Bulk ${decision} of ${records.length} change record(s)`, payload: { changeIds: records.map((r) => r.id) } }); }
export async function initiateRollback(record: ChangeRecord, ctx: ActorContext) { const now = new Date().toISOString(); if (environmentMode === "demo") { updateRecords((records) => records.map((current) => current.id === record.id ? { ...current, timeline: [{ ts: now, actor: ctx.actor, kind: "action", text: `Rollback initiated by ${ctx.actor} (${ctx.role}). ${current.rollbackSteps.length} documented step(s) queued.` }, ...current.timeline] } : current)); await pushNotification({ tenantId: ctx.tenantId, kind: "incident", title: `Rollback initiated — ${record.id}`, body: `${ctx.actor} started the documented rollback plan for "${record.title}".`, href: `/approvals/${record.id}` }); return; } await appendTimeline(record, { ts: now, actor: ctx.actor, kind: "action", text: `Rollback initiated by ${ctx.actor} (${ctx.role}). ${record.rollbackSteps.length} documented step(s) queued.` }); await writeAudit({ tenantId: ctx.tenantId, action: "change.rollback_initiated", entityType: "change_record", entityId: record.id, actorRole: ctx.role, detail: `Rollback initiated for ${record.title}`, payload: { changeId: record.id, steps: record.rollbackSteps } }); await pushNotification({ tenantId: ctx.tenantId, kind: "incident", title: `Rollback initiated — ${record.id}`, body: `${ctx.actor} started the documented rollback plan for "${record.title}".`, href: `/approvals/${record.id}` }); }
export async function createExternalTicket(record: ChangeRecord, system: ExternalTicket["system"], ctx: ActorContext) { if (system !== "Jira" && system !== "ServiceNow") throw new Error(`${system} ticket creation is not implemented.`); if (!record.rowId) throw new Error("This change record has no persisted database ID."); const ticket = await createExternalTicketServer({ data: { changeRecordId: record.rowId, system } }); await writeAudit({ tenantId: ctx.tenantId, action: "ticket.created", entityType: "ticket", entityId: record.rowId, actorRole: ctx.role, detail: `${system} ticket ${ticket.id} linked to ${record.id}`, payload: { changeId: record.id, system, ticketId: ticket.id, url: ticket.url } }); await pushNotification({ tenantId: ctx.tenantId, kind: "approval_deadline", title: `${system} ticket created — ${ticket.id}`, body: `${ticket.id} was created for ${record.id}.`, href: `/approvals/${record.id}` }); return ticket; }
