import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { resolveTenant } from "@/lib/genesys/store.server";
import { resolveDepartmentContext } from "@/lib/department-access.server";
import { DEMO_CHAT_SESSIONS } from "@/lib/demo-data";
import type { EnterpriseChatMessage } from "@/lib/enterprise-chat.functions";
import { resolveTenantContext } from "@/lib/tenant-context.server";
export type ChatSession = { id: string; title: string; createdAt: string; updatedAt: string; departmentKey: string | null; departmentName: string | null };
export type StoredChatMessage = EnterpriseChatMessage & { id: string; createdAt: string; result?: Record<string, unknown> | null };
type DemoSessionState = { session: ChatSession; messages: StoredChatMessage[] };
const demoSessionsByUser = new Map<string, Map<string, DemoSessionState>>();
function demoSessions(userId: string) { let sessions = demoSessionsByUser.get(userId); if (!sessions) { sessions = new Map(DEMO_CHAT_SESSIONS.map((row) => { const session: ChatSession = { id: row.id, title: row.title, createdAt: row.updatedAt, updatedAt: row.updatedAt, departmentKey: "contact-center", departmentName: "Contact Center" }; const messages = row.messages.map((message, index) => ({ id: `${row.id}-${index}`, role: message.role, content: message.content, createdAt: row.updatedAt } satisfies StoredChatMessage)); return [session.id, { session, messages }]; })); demoSessionsByUser.set(userId, sessions); } return sessions; }
function departmentName(key: string | null) { return key === "contact-center" ? "Contact Center" : key === "cloud-platform" ? "Cloud Platform" : key === "security" ? "Security" : "All departments"; }
async function isDemoTenant(context: any) { return (await resolveTenantContext(context.supabase, context.userId)).environmentMode === "demo"; }

export const createChatSession = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input?: { departmentKey?: string | null }) => ({ departmentKey: input?.departmentKey ? String(input.departmentKey).trim().toLowerCase() : null })).handler(async ({ data, context }) => {
  if (await isDemoTenant(context)) { const now = new Date().toISOString(); const session: ChatSession = { id: `demo-chat-${Date.now()}-${Math.random().toString(36).slice(2,8)}`, title: "New chat", createdAt: now, updatedAt: now, departmentKey: data.departmentKey ?? "all", departmentName: departmentName(data.departmentKey) }; demoSessions(context.userId).set(session.id, { session, messages: [] }); return { session }; }
  const { tenantId } = await resolveTenant(context.supabase, context.userId); const department = await resolveDepartmentContext(context.supabase, context.userId, data.departmentKey); const db = context.supabase as any; const { data: row, error } = await db.from("chat_sessions").insert({ tenant_id: tenantId, user_id: context.userId, title: "New chat", department_key: department.departmentKey }).select("id,title,created_at,updated_at,department_key").single(); if (error || !row) throw new Error(error?.message ?? "Unable to create chat session."); return { session: { id: row.id, title: row.title, createdAt: row.created_at, updatedAt: row.updated_at, departmentKey: row.department_key ?? null, departmentName: department.departmentName } satisfies ChatSession };
});

export const getMyDepartments = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { if (await isDemoTenant(context)) return { departments: [{ department_key: "contact-center", display_name: "Contact Center" }, { department_key: "cloud-platform", display_name: "Cloud Platform" }, { department_key: "security", display_name: "Security" }], selected: "contact-center", unrestricted: true }; const department = await resolveDepartmentContext(context.supabase, context.userId); return { departments: department.departments, selected: department.departmentKey, unrestricted: department.unrestricted }; });

export const listChatSessions = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => { if (await isDemoTenant(context)) return { sessions: [...demoSessions(context.userId).values()].map(({ session }) => session) }; const { tenantId } = await resolveTenant(context.supabase, context.userId); const db = context.supabase as any; const { data, error } = await db.from("chat_sessions").select("id,title,created_at,updated_at,department_key").eq("tenant_id", tenantId).eq("user_id", context.userId).order("updated_at", { ascending: false }); if (error) throw new Error(error.message); const departmentKeys = [...new Set((data ?? []).map((row: any) => row.department_key).filter(Boolean))]; const { data: departments } = departmentKeys.length ? await db.from("departments").select("department_key,display_name").in("department_key", departmentKeys) : { data: [] }; const names = new Map((departments ?? []).map((row: any) => [row.department_key, row.display_name])); return { sessions: (data ?? []).map((row: any) => ({ id: row.id, title: row.title, createdAt: row.created_at, updatedAt: row.updated_at, departmentKey: row.department_key ?? null, departmentName: row.department_key ? names.get(row.department_key) ?? row.department_key : null } satisfies ChatSession)) };
});

export const getChatSession = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).inputValidator((input: { sessionId: string }) => ({ sessionId: String(input.sessionId ?? "").trim() })).handler(async ({ data, context }) => {
  if (await isDemoTenant(context)) { const row = demoSessions(context.userId).get(data.sessionId); if (!row) throw new Error("Chat session not found."); return row; }
  const { tenantId } = await resolveTenant(context.supabase, context.userId); const db = context.supabase as any; const { data: session, error: sessionError } = await db.from("chat_sessions").select("id,title,created_at,updated_at,department_key").eq("id", data.sessionId).eq("tenant_id", tenantId).eq("user_id", context.userId).maybeSingle(); if (sessionError) throw new Error(sessionError.message); if (!session) throw new Error("Chat session not found."); const department = await resolveDepartmentContext(context.supabase, context.userId, session.department_key); const { data: messages, error: messageError } = await db.from("chat_messages").select("id,role,content,result,created_at").eq("session_id", session.id).eq("tenant_id", tenantId).eq("user_id", context.userId).order("created_at", { ascending: true }); if (messageError) throw new Error(messageError.message); return { session: { id: session.id, title: session.title, createdAt: session.created_at, updatedAt: session.updated_at, departmentKey: department.departmentKey, departmentName: department.departmentName } satisfies ChatSession, messages: (messages ?? []).map((row: any) => ({ id: row.id, role: row.role as EnterpriseChatMessage["role"], content: row.content, result: (row.result ?? undefined) as Record<string, unknown> | undefined, createdAt: row.created_at } satisfies StoredChatMessage)) };
});

export const deleteChatSession = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { sessionId: string }) => ({ sessionId: String(input.sessionId ?? "").trim() })).handler(async ({ data, context }) => { if (await isDemoTenant(context)) { demoSessions(context.userId).delete(data.sessionId); return { ok: true as const }; } const { tenantId } = await resolveTenant(context.supabase, context.userId); const db = context.supabase as any; const { error } = await db.from("chat_sessions").delete().eq("id", data.sessionId).eq("tenant_id", tenantId).eq("user_id", context.userId); if (error) throw new Error(error.message); return { ok: true as const }; });
