import { resolveTenant } from "@/lib/genesys/store.server";
import { loadLiveWorkspaceData, type LiveRecommendation } from "@/lib/live-workspace.functions";
import { loadProviderReportData, deriveCorrelatedSignals } from "@/lib/provider-sync.functions";
import { DEMO_GENESYS, DEMO_VULNERABILITIES, DEMO_CHANGES } from "@/lib/demo-data";
import { resolveTenantContext } from "@/lib/tenant-context.server";
import { toSharedFinding, type SharedFinding } from "@/lib/evidence/finding";
export type UserClientLike = Parameters<typeof resolveTenant>[0];
export type InvestigationConfidence = "high" | "medium" | "insufficient";
export interface InvestigationEvidenceItem { source: string; observation: string; observedAt: string; }
export interface InvestigationTimelineItem { ts: string; actor: string; kind: string; text: string; }
export interface InvestigationCorrelation { changeId: string; rowId: string; title: string; stage: string; severity: string; createdAt: string; }
export interface InvestigationSummary { isDemo?: boolean; key: string; provider?: string | null; title: string; severity: LiveRecommendation["severity"]; category: LiveRecommendation["category"]; impact: string; confidence: InvestigationConfidence; correlatedChangeCount: number; sharedFinding: SharedFinding; }
export interface Investigation { isDemo?: boolean; key: string; title: string; severity: LiveRecommendation["severity"]; category: LiveRecommendation["category"]; finding: string; evidence: InvestigationEvidenceItem[]; timeline: InvestigationTimelineItem[]; correlatedSignals: InvestigationCorrelation[]; confidence: InvestigationConfidence; confidenceRationale: string; businessImpact: string; risk: { tier: "Low" | "Medium" | "High" | "Critical"; factors: string[]; scoreAvailable: false }; recommendedAction: string; executable: boolean; provider: string | null; region: string | null; fetchedAt: string; lastSyncAt: string | null; insufficientEvidenceReason: string | null; sharedFinding: SharedFinding; }
function riskTier(severity: LiveRecommendation["severity"]): Investigation["risk"]["tier"] { if (severity === "critical") return "Critical"; if (severity === "high") return "High"; if (severity === "medium") return "Medium"; return "Low"; }
function confidenceScore(confidence: InvestigationConfidence): number { return confidence === "high" ? 0.9 : confidence === "medium" ? 0.6 : 0.2; }
function findingRef(provider: string | null, fetchedAt: string, lastSyncAt: string | null, key: string): string[] { return [lastSyncAt ? `${provider ?? "provider"}:sync:${lastSyncAt}` : `${provider ?? "provider"}:live-read:${fetchedAt}`, `finding:${key}`]; }
const demoInvestigation = (item: typeof DEMO_VULNERABILITIES[number]): Investigation => { const fetchedAt = "2026-09-04T08:30:00.000Z"; const sharedFinding = toSharedFinding({ id: item.id, title: item.title, severity: String(item.severity).toLowerCase() as SharedFinding["severity"], category: "Security", impact: item.recommendation, confidence: 1, href: `/investigations/${item.id}`, freshness: fetchedAt, evidenceRefs: [`demo:${item.provider}:${item.id}`] }); return { isDemo: true, key: item.id, title: item.title, severity: item.severity as LiveRecommendation["severity"], category: "Security", finding: item.evidence, evidence: [{ source: `${item.provider} demo security evidence`, observation: item.evidence, observedAt: "2026-09-04T07:30:00.000Z" }, { source: "Demo recommendation engine", observation: item.recommendation, observedAt: "2026-09-04T07:31:00.000Z" }], timeline: [{ ts: "2026-09-04T06:55:00.000Z", actor: "Aegis Security Agent", kind: "finding", text: "Finding detected from demo security evidence." }, { ts: "2026-09-04T07:05:00.000Z", actor: "Aegis Governance", kind: "assessment", text: "Human approval required before remediation." }], correlatedSignals: DEMO_CHANGES.filter((change) => item.severity === "critical" || change.severity === item.severity).slice(0, 2).map((change) => ({ changeId: change.changeId, rowId: change.id, title: change.title, stage: change.stage, severity: change.severity, createdAt: change.createdAt })), confidence: "high", confidenceRationale: "Demo provider evidence and persisted demo snapshot are intentionally aligned for product evaluation.", businessImpact: item.recommendation, risk: { tier: riskTier(item.severity as LiveRecommendation["severity"]), factors: ["Demo evidence", "No provider mutation executed", "Human approval required"], scoreAvailable: false }, recommendedAction: item.recommendation, executable: false, provider: item.provider, region: "us-east-1", fetchedAt, lastSyncAt: DEMO_GENESYS.lastSyncAt, insufficientEvidenceReason: null, sharedFinding }; };

export async function listInvestigations(supabase: UserClientLike, userId: string): Promise<{ connected: boolean; provider: string | null; fetchedAt: string; isDemo: boolean; investigations: InvestigationSummary[] }> {
  const { environmentMode } = await resolveTenantContext(supabase, userId);
  if (environmentMode === "demo") return { connected: true, provider: "AWS + Genesys Cloud", fetchedAt: "2026-09-04T08:30:00.000Z", isDemo: true, investigations: DEMO_VULNERABILITIES.map((item) => ({ isDemo: true, key: item.id, provider: item.provider, title: item.title, severity: item.severity as LiveRecommendation["severity"], category: "Security" as LiveRecommendation["category"], impact: item.recommendation, confidence: "high", correlatedChangeCount: DEMO_CHANGES.length > 0 ? 1 : 0, sharedFinding: demoInvestigation(item).sharedFinding })) };
  const live = await loadLiveWorkspaceData(supabase, userId); if (!live.connected) return { connected: false, provider: null, fetchedAt: live.fetchedAt, isDemo: false, investigations: [] }; const { tenantId } = await resolveTenant(supabase, userId); const db = supabase as any; const changes = await db.from("change_records").select("change_id,title").eq("tenant_id", tenantId).limit(500); const changeRows: any[] = changes.data ?? [];
  return { connected: true, provider: live.provider, fetchedAt: live.fetchedAt, isDemo: false, investigations: live.recommendations.map((recommendation) => { const confidence = confidenceFor(live.lastSyncAt); return { isDemo: false, key: recommendation.key, title: recommendation.title, severity: recommendation.severity, category: recommendation.category, impact: recommendation.impact, confidence, correlatedChangeCount: changeRows.filter((row) => String(row.title) === recommendation.title).length, sharedFinding: toSharedFinding({ id: recommendation.key, title: recommendation.title, severity: recommendation.severity, category: recommendation.category, impact: recommendation.impact, confidence: confidenceScore(confidence), href: `/investigations/${recommendation.key}`, freshness: live.lastSyncAt ?? live.fetchedAt, evidenceRefs: findingRef(live.provider, live.fetchedAt, live.lastSyncAt, recommendation.key) }) }; }) };
}
function confidenceFor(lastSyncAt: string | null): InvestigationConfidence { if (!lastSyncAt) return "medium"; return Date.now() - new Date(lastSyncAt).getTime() <= 48 * 3_600_000 ? "high" : "medium"; }
export async function loadInvestigation(supabase: UserClientLike, userId: string, key: string): Promise<Investigation | { unavailable: true; reason: string }> {
  const { environmentMode } = await resolveTenantContext(supabase, userId);
  if (environmentMode === "demo") { const item = DEMO_VULNERABILITIES.find((candidate) => candidate.id === key); return item ? demoInvestigation(item) : { unavailable: true, reason: "Demo finding not found." }; }
  const live = await loadLiveWorkspaceData(supabase, userId); if (!live.connected) return { unavailable: true, reason: "No provider is connected, so there is no evidence to investigate. Connect an integration and run a sync first." }; const recommendation = live.recommendations.find((item) => item.key === key); if (!recommendation) return { unavailable: true, reason: "This finding is no longer present in the current provider evidence." }; const { tenantId } = await resolveTenant(supabase, userId); const db = supabase as any;
  const [changes, audit, providerEvidence] = await Promise.all([
    db.from("change_records").select("id,change_id,title,stage,severity,created_at,timeline").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(200),
    db.from("audit_log").select("action,entity_type,entity_id,detail,actor_email,created_at").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(200),
    loadProviderReportData(supabase, userId, null).catch(() => ({ connectedProviders: [], entities: [], runs: [], department: { key: "default", name: "Default", unrestricted: true } })),
  ]);
  const correlated: any[] = (changes.data ?? []).filter((row: any) => String(row.title) === recommendation.title); const correlatedIds = new Set(correlated.map((row) => String(row.change_id))); const crossProviderSignals = deriveCorrelatedSignals(providerEvidence.entities ?? []);
  const evidence: InvestigationEvidenceItem[] = [{ source: `${live.provider ?? "Provider"} live read (${live.region ?? "region unknown"})`, observation: recommendation.evidence, observedAt: live.fetchedAt }, { source: "Live workspace counters", observation: `${live.users} users, ${live.licensedUsers} licensed users, ${live.licenseAssignments} license assignments, ${live.queues} queues observed in the current read.`, observedAt: live.fetchedAt }];
  if (live.lastSyncAt) evidence.push({ source: "Persisted provider snapshot", observation: `The most recent successful persisted sync for this integration completed at ${live.lastSyncAt}.`, observedAt: live.lastSyncAt });
  for (const signal of crossProviderSignals.slice(0, 10)) evidence.push({ source: `Cross-provider temporal correlation (${signal.providers.join(" + ")})`, observation: signal.detail, observedAt: signal.timestamp });
  const timeline: InvestigationTimelineItem[] = [];
  for (const row of (audit.data ?? []) as any[]) { const entityId = row.entity_id ? String(row.entity_id) : null; const relevant = (entityId && correlatedIds.has(entityId)) || String(row.entity_type) === "integration" || String(row.action).startsWith("integration.") || String(row.action).startsWith("guardrail."); if (!relevant) continue; timeline.push({ ts: String(row.created_at), actor: row.actor_email ? String(row.actor_email) : "system", kind: String(row.entity_type), text: row.detail ? String(row.detail) : String(row.action) }); if (timeline.length >= 20) break; }
  for (const signal of crossProviderSignals.slice(0, 10)) timeline.push({ ts: signal.timestamp, actor: "CenOps correlation engine", kind: "temporal-correlation", text: signal.detail });
  const confidence = confidenceFor(live.lastSyncAt); const corroborated = crossProviderSignals.length > 0; const sharedFinding = toSharedFinding({ id: recommendation.key, title: recommendation.title, severity: recommendation.severity, category: recommendation.category, impact: recommendation.impact, confidence: corroborated ? 0.95 : confidenceScore(confidence), href: `/investigations/${recommendation.key}`, freshness: live.lastSyncAt ?? live.fetchedAt, evidenceRefs: [...findingRef(live.provider, live.fetchedAt, live.lastSyncAt, recommendation.key), ...crossProviderSignals.slice(0, 10).flatMap((signal) => signal.evidence.map((item) => `${item.provider}:${item.entityType}:${item.entityKey}:${item.observedAt}`))] });
  return { isDemo: false, key: recommendation.key, title: recommendation.title, severity: recommendation.severity, category: recommendation.category, finding: recommendation.title, evidence, timeline: timeline.sort((a, b) => new Date(b.ts).getTime() - new Date(a.ts).getTime()).slice(0, 30), correlatedSignals: correlated.map((row) => ({ changeId: String(row.change_id), rowId: String(row.id), title: String(row.title), stage: String(row.stage), severity: String(row.severity), createdAt: String(row.created_at) })), confidence: corroborated ? "high" : confidence, confidenceRationale: corroborated ? "The live finding is additionally corroborated by synchronized GitHub/Jira temporal evidence. The correlation is explicitly temporal and is not treated as causation." : confidence === "high" ? "The live provider read and a persisted sync completed within the last 48 hours both contain the evidence for this finding." : "The finding is supported by the current live provider read, but no recent persisted sync corroborates it.", businessImpact: recommendation.impact, risk: { tier: riskTier(recommendation.severity), factors: ["Derived from read-only provider evidence", ...(corroborated ? ["Cross-provider temporal correlation available"] : []), "No provider mutation has been executed", "Human approval required before any change"], scoreAvailable: false }, recommendedAction: recommendation.action, executable: recommendation.canExecute, provider: live.provider, region: live.region, fetchedAt: live.fetchedAt, lastSyncAt: live.lastSyncAt, insufficientEvidenceReason: null, sharedFinding };
}
