// Live operational state backed by Lovable Cloud.
import { useSyncExternalStore } from "react";
import type { RealtimeChannel } from "@supabase/supabase-js";
import "@/lib/change-impact.types";
import { supabase } from "@/integrations/supabase/client";
import { type ChangeApproval, type ChangeAuditEntry, type ChangeRecord, type ChangeStage, type ChangeTimelineEvent, type ExecutionMode, type ExternalTicket, type Notification, type NotificationKind, type RiskTier, type ValidationCheck } from "@/lib/change-data";
import type { Severity } from "@/lib/mock-data";
import { DEMO_CHANGES, DEMO_DATA_ENABLED } from "@/lib/demo-data";
export interface RealtimeState { records: ChangeRecord[]; notifications: Notification[]; lastEventAt: number | null; connected: boolean; loading: boolean; tenantId: string | null; }
const initialState: RealtimeState = { records: [], notifications: [], lastEventAt: null, connected: false, loading: true, tenantId: null };
let state: RealtimeState = initialState; const subscribers = new Set<() => void>(); let channel: RealtimeChannel | null = null; let activeTenant: string | null = null;
function setState(next: Partial<RealtimeState>) { state = { ...state, ...next }; subscribers.forEach((fn) => fn()); }
interface ApprovalRow { id:string; change_record_id:string; team:string; approver:string; approver_role:string|null; status:string; decided_at:string|null; comment:string|null; position:number; }
interface RecordRow { id:string; change_id:string; title:string; stage:string; severity:string; risk:unknown; execution_mode:string; owner_team:string; requester:string|null; category:string|null; agent:string|null; change_window:unknown; business_impact:string|null; ai_reasoning:string|null; rollback_steps:unknown; validations:unknown; external_tickets:unknown; timeline:unknown; created_at:string; estimated_cost_amount:number|null; estimated_cost_currency:string|null; estimated_savings_amount:number|null; estimated_downtime_minutes:number|null; change_approvals?:ApprovalRow[]; }
function mapApproval(row:ApprovalRow):ChangeApproval{return{rowId:row.id,team:row.team,approver:row.approver,role:row.approver_role??"",status:(row.status as ChangeApproval["status"])??"pending",timestamp:row.decided_at??undefined,comment:row.comment??undefined};}
function mapRecord(row:RecordRow,audit:ChangeAuditEntry[]=[]):ChangeRecord{const approvals=[...(row.change_approvals??[])].sort((a,b)=>a.position-b.position).map(mapApproval);return{rowId:row.id,id:row.change_id,title:row.title,stage:row.stage as ChangeStage,severity:row.severity as Severity,risk:(row.risk as ChangeRecord["risk"])??{tier:"Low" as RiskTier,score:0,factors:[]},executionMode:row.execution_mode as ExecutionMode,ownerTeam:row.owner_team,requester:row.requester??"",category:row.category??"",agent:row.agent??"",window:(row.change_window as ChangeRecord["window"])??{start:"",end:"",inMaintenance:false},businessImpact:row.business_impact??"",aiReasoning:row.ai_reasoning??"",approvals,rollbackSteps:(row.rollback_steps as string[])??[],validations:(row.validations as ValidationCheck[])??[],externalTickets:(row.external_tickets as ExternalTicket[])??[],timeline:(row.timeline as ChangeTimelineEvent[])??[],audit,createdAt:row.created_at,estimatedCostAmount:row.estimated_cost_amount,estimatedCostCurrency:row.estimated_cost_currency,estimatedSavingsAmount:row.estimated_savings_amount,estimatedDowntimeMinutes:row.estimated_downtime_minutes};}
function demoRiskTier(severity:string):RiskTier{return severity.toLowerCase()==="critical"?"Critical":severity.toLowerCase()==="high"?"High":severity.toLowerCase()==="medium"?"Medium":"Low";}
function mapDemoRecord(row:typeof DEMO_CHANGES[number]):ChangeRecord{return{rowId:row.id,id:row.changeId,title:row.title,stage:row.stage as ChangeStage,severity:row.severity as Severity,risk:{tier:demoRiskTier(row.severity),score:row.severity.toLowerCase()==="critical"?95:row.severity.toLowerCase()==="high"?78:row.severity.toLowerCase()==="medium"?55:25,factors:[`${row.severity} severity demo fixture`]},executionMode:"Manual",ownerTeam:row.ownerTeam,requester:"Aegis AI",category:"AI Proposal",agent:"Aegis Operations Agent",window:{start:"",end:"",inMaintenance:false},businessImpact:"Review the affected operational resource before execution.",aiReasoning:"Generated from deterministic demo evidence for workflow evaluation.",approvals:[{rowId:`demo-approval-${row.id}`,team:row.ownerTeam,approver:"Workspace approver",role:"Admin",status:"pending"}],rollbackSteps:["Validate and execute only after approval."],validations:[{name:"Governance gate",status:"warning",detail:"Demo proposal — no provider mutation is executed."}],externalTickets:[],timeline:[{ts:row.createdAt,actor:"Aegis AI",kind:"system",text:"Demo change proposal created."}],audit:[],createdAt:row.createdAt,estimatedCostAmount:null,estimatedCostCurrency:null,estimatedSavingsAmount:null,estimatedDowntimeMinutes:null};}
export function relativeTime(iso:string){const diff=Date.now()-new Date(iso).getTime();const mins=Math.round(diff/60000);if(mins<1)return"just now";if(mins<60)return`${mins}m ago`;const hours=Math.round(mins/60);if(hours<24)return`${hours}h ago`;return`${Math.round(hours/24)}d ago`;}
interface NotificationRow{id:string;kind:string;title:string;body:string|null;href:string|null;unread:boolean;created_at:string;}
function mapNotification(row:NotificationRow):Notification{return{id:row.id,kind:(row.kind as NotificationKind)??"info",title:row.title,body:row.body??"",ts:relativeTime(row.created_at),unread:row.unread,href:row.href??undefined};}
const RECORD_COLUMNS="id, change_id, title, stage, severity, risk, execution_mode, owner_team, requester, category, agent, change_window, business_impact, ai_reasoning, rollback_steps, validations, external_tickets, timeline, created_at, estimated_cost_amount, estimated_cost_currency, estimated_savings_amount, estimated_downtime_minutes, change_approvals(id, change_record_id, team, approver, approver_role, status, decided_at, comment, position)";
async function loadAll(tenantId:string){if(DEMO_DATA_ENABLED){setState({records:DEMO_CHANGES.map(mapDemoRecord),notifications:[],loading:false,tenantId,connected:true});return;}const[records,notes,audit]=await Promise.all([supabase.from("change_records").select(RECORD_COLUMNS).eq("tenant_id",tenantId).order("change_id"),supabase.from("notifications").select("id, kind, title, body, href, unread, created_at").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(30),supabase.from("audit_log").select("entity_id, action, actor_email, hash, created_at").eq("tenant_id",tenantId).eq("entity_type","change_record").order("created_at",{ascending:false}).limit(200)]);const auditByChange=new Map<string,ChangeAuditEntry[]>();for(const row of audit.data??[]){const key=row.entity_id??"";const list=auditByChange.get(key)??[];list.push({ts:row.created_at,actor:row.actor_email??"system",action:row.action,hash:row.hash});auditByChange.set(key,list);}setState({records:((records.data??[]) as unknown as RecordRow[]).map(row=>mapRecord(row,auditByChange.get(row.change_id)??[])),notifications:((notes.data??[]) as NotificationRow[]).map(mapNotification),loading:false,tenantId});}
export function initRealtime(tenantId:string){if(activeTenant===tenantId)return;teardownRealtime();activeTenant=tenantId;setState({loading:true,tenantId});void loadAll(tenantId);if(DEMO_DATA_ENABLED){setState({connected:true});return;}const filter=`tenant_id=eq.${tenantId}`;channel=supabase.channel(`aegis-live-${tenantId}`).on("postgres_changes",{event:"*",schema:"public",table:"change_records",filter},()=>{setState({lastEventAt:Date.now()});void loadAll(tenantId);}).on("postgres_changes",{event:"*",schema:"public",table:"change_approvals",filter},()=>{setState({lastEventAt:Date.now()});void loadAll(tenantId);}).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter},payload=>{setState({lastEventAt:Date.now()});if(payload.eventType==="INSERT"){const row=payload.new as unknown as NotificationRow;setState({notifications:[mapNotification(row),...state.notifications].slice(0,30)});return;}if(payload.eventType==="UPDATE"){const row=payload.new as unknown as NotificationRow;setState({notifications:state.notifications.map(n=>n.id===row.id?mapNotification(row):n)});return;}const removed=payload.old as{id?:string};setState({notifications:state.notifications.filter(n=>n.id!==removed.id)});}).subscribe(status=>setState({connected:status==="SUBSCRIBED"}));}
export function teardownRealtime(){if(channel)supabase.removeChannel(channel);channel=null;activeTenant=null;setState({...initialState});}
export function refreshRealtime(){if(activeTenant)void loadAll(activeTenant);}
function subscribe(fn:()=>void){subscribers.add(fn);return()=>subscribers.delete(fn);}const getSnapshot=()=>state;const getServerSnapshot=()=>initialState;
export function useRealtime(){return useSyncExternalStore(subscribe,getSnapshot,getServerSnapshot);}
export function updateRecords(fn:(records:ChangeRecord[])=>ChangeRecord[]){setState({records:fn(state.records),lastEventAt:Date.now()});}
export async function pushNotification(input:{tenantId:string;kind:NotificationKind;title:string;body:string;href?:string}){if(DEMO_DATA_ENABLED){setState({notifications:[{id:`demo-notification-${Date.now()}`,kind:input.kind,title:input.title,body:input.body,ts:"just now",unread:true,href:input.href},...state.notifications].slice(0,30)});return;}await supabase.from("notifications").insert({tenant_id:input.tenantId,kind:input.kind,title:input.title,body:input.body,href:input.href??null});}
export async function markNotificationRead(id:string){setState({notifications:state.notifications.map(n=>n.id===id?{...n,unread:false}:n)});if(!DEMO_DATA_ENABLED)await supabase.from("notifications").update({unread:false}).eq("id",id);}
export async function markAllNotificationsRead(){const ids=state.notifications.filter(n=>n.unread).map(n=>n.id);setState({notifications:state.notifications.map(n=>({...n,unread:false}))});if(!DEMO_DATA_ENABLED&&ids.length)await supabase.from("notifications").update({unread:false}).in("id",ids);}
