import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, CheckCircle2, Database, Loader2, Plug, RefreshCw, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DATA_SOURCE_STATE_LABELS, providerLabel, type DataSourceState } from "@/lib/capabilities/registry";
import { FRESHNESS_LABELS } from "@/lib/capabilities/freshness";
import { addAgentDataSource, getAgentDataSources, previewAgentCapability, removeAgentDataSource, saveAgentInstructions, updateAgentDataSource } from "@/lib/agent-architecture.functions";
import { getAgentConfiguration, saveAgentConfiguration } from "@/lib/agent-configuration.functions";
import { AGENT_POLICY_RULE_TYPES, DEFAULT_AGENT_POLICY_RULES, type AgentPolicyRule, type AgentPolicyRuleType } from "@/lib/capabilities/agent-policy-rules";

function StatePill({ state }: { state: DataSourceState }) {
  const map: Record<DataSourceState, string> = { active: "bg-success/15 text-success border-success/30", connected_not_bound: "bg-muted text-muted-foreground border-border", unhealthy: "bg-destructive/15 text-destructive border-destructive/30", stale: "bg-warning/20 text-warning-foreground border-warning/40", capability_unavailable: "bg-muted text-muted-foreground border-border", not_connected: "bg-muted text-muted-foreground border-border" };
  const Icon = state === "active" ? CheckCircle2 : state === "connected_not_bound" ? Plug : AlertTriangle;
  return <span className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-[11px] font-medium ${map[state]}`}><Icon className="h-3 w-3" />{DATA_SOURCE_STATE_LABELS[state]}</span>;
}

function newRule(index: number): AgentPolicyRule { return { id: `policy-${Date.now()}-${index}`, name: `Policy ${index + 1}`, rule: "", type: "business", priority: Math.max(1, 100 - index), enabled: true }; }

export function AgentDataSourceManager({ agentKey, agentName }: { agentKey: string; agentName: string }) {
  const qc = useQueryClient();
  const fetchSources = useServerFn(getAgentDataSources), addSource = useServerFn(addAgentDataSource), updateSource = useServerFn(updateAgentDataSource), removeSource = useServerFn(removeAgentDataSource), saveInstructions = useServerFn(saveAgentInstructions), preview = useServerFn(previewAgentCapability), fetchConfig = useServerFn(getAgentConfiguration), saveConfig = useServerFn(saveAgentConfiguration);
  const sourceKey = ["agent-data-sources", agentKey], configKey = ["agent-configuration", agentKey];
  const { data, isLoading } = useQuery({ queryKey: sourceKey, queryFn: () => fetchSources({ data: { agentKey } }) });
  const { data: configData, isLoading: configLoading } = useQuery({ queryKey: configKey, queryFn: () => fetchConfig({ data: { agentKey } }) });
  const canManage = data?.canManage ?? configData?.canManage ?? false;
  const [pick, setPick] = useState(""), [purpose, setPurpose] = useState(""), [rules, setRules] = useState<AgentPolicyRule[]>(DEFAULT_AGENT_POLICY_RULES), [instr, setInstr] = useState({ pre: "", system: "", post: "" });
  useEffect(() => { if (configData?.ok) { setPurpose(configData.settings.purposeBehavior); setRules(configData.settings.policyRules); } }, [configData]);
  useEffect(() => { if (data?.ok) setInstr({ pre: data.settings.preInstructions, system: data.settings.systemInstructions, post: data.settings.postInstructions }); }, [data]);
  const invalidate = () => { void qc.invalidateQueries({ queryKey: sourceKey }); void qc.invalidateQueries({ queryKey: configKey }); };
  const addMutation = useMutation({ mutationFn: (v: { integrationId: string; capabilityKey: string }) => addSource({ data: { agentKey, ...v } }), onSuccess: (r) => { if (r.ok) { toast.success("Data source connected to agent"); setPick(""); invalidate(); } else toast.error(r.errorMessage); } });
  const toggleMutation = useMutation({ mutationFn: (v: { bindingId: string; enabled: boolean }) => updateSource({ data: v }), onSuccess: (r) => { if (r.ok) invalidate(); else toast.error(r.errorMessage); } });
  const removeMutation = useMutation({ mutationFn: (id: string) => removeSource({ data: { bindingId: id } }), onSuccess: (r) => { if (r.ok) { toast.success("Data source removed"); invalidate(); } else toast.error(r.errorMessage); } });
  const configMutation = useMutation({ mutationFn: () => saveConfig({ data: { agentKey, purposeBehavior: purpose, policyRules: rules } }), onSuccess: (r) => { if (r.ok) { toast.success("Agent configuration saved"); invalidate(); } else toast.error(r.errorMessage); } });
  const instrMutation = useMutation({ mutationFn: () => saveInstructions({ data: { agentKey, preInstructions: instr.pre, systemInstructions: instr.system, postInstructions: instr.post } }), onSuccess: (r) => { if (r.ok) { toast.success("Instructions saved"); invalidate(); } else toast.error(r.errorMessage); } });
  const previewMutation = useMutation({ mutationFn: (key: string) => preview({ data: { agentKey, capabilityKey: key } }), onSuccess: (r) => { if (!r.ok) toast.error(r.errorMessage); else toast.success(`${r.recordCount} normalized records from ${r.sources.length} source${r.sources.length === 1 ? "" : "s"}`, { description: r.warnings[0] ?? "Read-only capability call — no changes were made." }); } });
  if (isLoading || configLoading) return <div className="space-y-3"><Skeleton className="h-9 w-full" /><Skeleton className="h-24 w-full" /><Skeleton className="h-24 w-full" /></div>;
  if (data && !data.ok) return <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">{data.errorMessage}</div>;
  const integrations = data?.integrations ?? [], bindings = data?.bindings ?? [], capabilities = data?.agentCapabilities ?? [];
  const options = integrations.flatMap((i) => i.compatibleCapabilities.filter((c) => !c.bound).map((c) => ({ value: `${i.integrationId}::${c.key}`, label: `${i.displayName || providerLabel(i.provider).name} → ${c.displayName}`, implemented: c.implemented })));
  const patchRule = (id: string, patch: Partial<AgentPolicyRule>) => setRules((xs) => xs.map((x) => x.id === id ? { ...x, ...patch } : x));
  return <Tabs defaultValue="sources">
    <TabsList className="w-full"><TabsTrigger value="sources" className="flex-1">Data Sources</TabsTrigger><TabsTrigger value="capabilities" className="flex-1">Capabilities</TabsTrigger><TabsTrigger value="policies" className="flex-1">Policies</TabsTrigger><TabsTrigger value="instructions" className="flex-1">Instructions</TabsTrigger></TabsList>
    <TabsContent value="sources" className="mt-4 space-y-3">
      <p className="text-xs text-muted-foreground">Every connected integration instance is shown separately. Platform and instance identity are intentionally distinct, so multiple instances of the same provider remain visible as separate sources.</p>
      {canManage && <div className="flex gap-2"><Select value={pick} onValueChange={setPick}><SelectTrigger className="flex-1"><SelectValue placeholder={options.length ? "Add an integration capability…" : "No compatible capabilities available"} /></SelectTrigger><SelectContent>{options.map((o) => <SelectItem key={o.value} value={o.value}>{o.label}{!o.implemented ? " (planned)" : ""}</SelectItem>)}</SelectContent></Select><Button size="sm" disabled={!pick || addMutation.isPending} onClick={() => { const [integrationId, capabilityKey] = pick.split("::"); if (integrationId && capabilityKey) addMutation.mutate({ integrationId, capabilityKey }); }}>{addMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Add source"}</Button></div>}
      {integrations.length === 0 && <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">{DATA_SOURCE_STATE_LABELS.not_connected}</div>}
      {integrations.map((i) => { const label = providerLabel(i.provider), rows = bindings.filter((b) => b.integrationId === i.integrationId); return <div key={i.integrationId} className="rounded-lg border p-4"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-muted text-lg">{label.logo}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{label.name}</span><Badge variant="secondary" className="text-[10px]">Integration instance</Badge>{i.isMock && <Badge variant="outline" className="text-[10px]">Sample data</Badge>}</div><div className="mt-1 text-sm">{i.displayName || "Unnamed instance"}</div><div className="mt-0.5 text-xs text-muted-foreground">{i.orgName ? `Organization / account: ${i.orgName} • ` : ""}{i.lastSyncAt ? `Last sync ${new Date(i.lastSyncAt).toLocaleString()}` : "Never synchronized"} • {FRESHNESS_LABELS[i.freshness]}</div><div className="mt-2"><StatePill state={i.state} /></div>{rows.length > 0 && <div className="mt-3 space-y-2">{rows.map((b) => <div key={b.id} className="flex items-center justify-between gap-2 rounded-md bg-muted/40 px-2.5 py-2"><div><div className="text-xs font-medium">{b.capabilityName}</div><div className="font-mono text-[10px] text-muted-foreground">{b.capabilityKey}</div></div><div className="flex items-center gap-2"><Switch checked={b.enabled} disabled={!canManage || toggleMutation.isPending} onCheckedChange={(v) => toggleMutation.mutate({ bindingId: b.id, enabled: v })} />{canManage && <Button size="sm" variant="ghost" onClick={() => removeMutation.mutate(b.id)}><Trash2 className="h-3.5 w-3.5" /></Button>}</div></div>)}</div>}</div></div></div>; })}
    </TabsContent>
    <TabsContent value="capabilities" className="mt-4 space-y-3"><p className="text-xs text-muted-foreground">Capabilities are provider-neutral contracts. READ capabilities retrieve facts. WRITE capabilities may request production mutations, but permissions and execution remain governed by the router, policy and approval controls.</p>{(["read", "write"] as const).map((mode) => { const list = capabilities.filter((c) => mode === "write" ? c.writeCapable : !c.writeCapable); return <div key={mode} className="space-y-2"><div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{mode} capabilities</div>{list.length ? list.map((c) => <div key={c.id} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Database className="h-3.5 w-3.5 text-primary" /><span className="text-sm font-medium">{c.displayName}</span><Badge variant="outline" className="text-[10px]">{c.writeCapable ? "write capable" : "read only"}</Badge>{c.required && <Badge className="text-[10px]">required</Badge>}</div>{c.description && <p className="mt-1 text-xs text-muted-foreground">{c.description}</p>}<div className="mt-1 font-mono text-[10px] text-muted-foreground">{c.key}</div></div><Button size="sm" variant="outline" disabled={previewMutation.isPending} onClick={() => previewMutation.mutate(c.key)}><RefreshCw className="h-3.5 w-3.5" /><span className="ml-1.5">Test</span></Button></div>) : <div className="rounded-lg border border-dashed p-4 text-xs text-muted-foreground">No {mode} capabilities are registered for this agent.</div>}</div>; })}</TabsContent>
    <TabsContent value="policies" className="mt-4 space-y-3"><div className="rounded-lg border border-primary/20 bg-primary/[0.03] p-4"><div className="text-sm font-semibold">Agent-level policies</div><p className="mt-1 text-xs text-muted-foreground">Policies belong to {agentName}, not to a particular provider. Add 10–15 rules or more as needed; the platform supports up to 100. These rules are validated server-side and never grant permissions.</p></div>{rules.map((r, index) => <div key={r.id} className="rounded-lg border p-4"><div className="flex items-start gap-3"><Badge variant="outline" className="mt-1">{index + 1}</Badge><div className="min-w-0 flex-1 space-y-2"><div className="grid gap-2 md:grid-cols-[1fr_170px_100px]"><Input value={r.name} disabled={!canManage} placeholder="Policy name" onChange={(e) => patchRule(r.id, { name: e.target.value })} /><Select value={r.type} disabled={!canManage} onValueChange={(v) => patchRule(r.id, { type: v as AgentPolicyRuleType })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{AGENT_POLICY_RULE_TYPES.map((t) => <SelectItem key={t} value={t}>{t[0].toUpperCase() + t.slice(1)}</SelectItem>)}</SelectContent></Select><Input type="number" min={1} max={10000} value={r.priority} disabled={!canManage} onChange={(e) => patchRule(r.id, { priority: Number(e.target.value) })} aria-label="Policy priority" /></div><Textarea value={r.rule} disabled={!canManage} placeholder="Define the policy, e.g. Do not reclaim licenses from users with qualifying activity in the last 90 days." onChange={(e) => patchRule(r.id, { rule: e.target.value })} className="min-h-20" /><div className="flex items-center justify-between"><label className="flex items-center gap-2 text-xs"><Switch checked={r.enabled} disabled={!canManage} onCheckedChange={(v) => patchRule(r.id, { enabled: v })} />Enabled</label>{canManage && <Button size="sm" variant="ghost" onClick={() => setRules((xs) => xs.filter((x) => x.id !== r.id))}><Trash2 className="mr-1.5 h-3.5 w-3.5" />Remove</Button>}</div></div></div></div>)}{canManage && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setRules((xs) => [...xs, newRule(xs.length)])}>Add policy</Button><Button onClick={() => configMutation.mutate()} disabled={configMutation.isPending}><Save className="mr-1.5 h-4 w-4" />{configMutation.isPending ? "Saving…" : "Save policies"}</Button></div>}</TabsContent>
    <TabsContent value="instructions" className="mt-4 space-y-3"><p className="text-xs text-muted-foreground">Instructions shape model behavior and response context. They do not grant capabilities or override deterministic policy enforcement.</p>{([ ["pre", "Pre-instructions", "Checks to run before analysis"], ["system", "System instructions", "Role, tone and operating context"], ["post", "Post-instructions", "Required shape of every recommendation"] ] as const).map(([key, label, hint]) => <div key={key} className="space-y-1.5"><label className="text-xs font-medium" htmlFor={`instr-${key}`}>{label}</label><Textarea id={`instr-${key}`} rows={4} value={instr[key]} placeholder={hint} disabled={!canManage} onChange={(e) => setInstr((s) => ({ ...s, [key]: e.target.value }))} /></div>)}{canManage ? <Button size="sm" onClick={() => instrMutation.mutate()} disabled={instrMutation.isPending}>{instrMutation.isPending && <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />}Save instructions</Button> : <p className="text-xs text-muted-foreground">Only workspace admins and managers can edit instructions.</p>}</TabsContent>
  </Tabs>;
}
