import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Activity, ArrowLeft, Bot, Coins, Gauge, Plug, ShieldCheck } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { PageHeader } from "@/components/layout/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyIntegrationsState } from "@/components/EmptyIntegrationsState";
import { getAgentDetail, type AgentDetail } from "@/lib/agent-detail.functions";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/_app/agent/$agentKey")({ head: ({ params }) => pageHead({ path: `/agent/${params.agentKey}`, title: "Agent Detail — Aegis AI", description: "Real agent telemetry, bindings, changes and outcomes." }), component: AgentDetailPage });

function AgentDetailPage() {
  const { agentKey } = Route.useParams();
  const load = useServerFn(getAgentDetail);
  const [data, setData] = useState<AgentDetail | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; void load({ data: { agentKey } }).then((result) => { if (active) setData(result); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [agentKey, load]);
  if (loading) return <div className="py-16 text-center text-sm text-muted-foreground">Loading real agent telemetry…</div>;
  if (!data) return <EmptyIntegrationsState title="Agent not found" description="This agent definition is not available in the current workspace." />;
  return <div><PageHeader title={data.displayName} description={data.description ?? "No description configured."} actions={<Button variant="outline" asChild><Link to="/agents"><ArrowLeft className="mr-1.5 h-4 w-4" /> Back to agents</Link></Button>} />
    <div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline">{data.category ?? "Uncategorized"}</Badge><Badge variant="outline" className={data.operational ? "border-success/40 text-success" : ""}>{data.operational ? "Operational" : "Not bound"}</Badge></div>
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-4"><Metric icon={Activity} label="AI requests" value={data.telemetry.aiRequests.toLocaleString()} /><Metric icon={Coins} label="Tokens" value={data.telemetry.totalTokens.toLocaleString()} /><Metric icon={Gauge} label="Avg latency" value={data.telemetry.averageLatencyMs == null ? "Not available" : `${data.telemetry.averageLatencyMs} ms`} /><Metric icon={Coins} label="Savings" value={data.savings.summary} /></div>
    <div className="mt-6 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Real integration bindings</CardTitle><CardDescription>Only tenant-scoped bindings are shown.</CardDescription></CardHeader><CardContent className="space-y-2">{data.bindings.length ? data.bindings.map((binding) => <div key={`${binding.integrationId}-${binding.capabilityKey}`} className="flex items-center justify-between rounded-lg border p-3"><div><div className="flex items-center gap-2 text-sm font-medium"><Plug className="h-4 w-4 text-primary" /> {binding.provider ?? "Unknown provider"}</div><div className="mt-1 text-xs text-muted-foreground">{binding.capabilityName ?? binding.capabilityKey ?? "Capability not specified"}</div></div><Badge variant="outline" className={binding.enabled && !binding.isMock ? "border-success/40 text-success" : ""}>{binding.enabled && !binding.isMock ? "Enabled" : "Unavailable"}</Badge></div>) : <div className="py-8 text-center text-sm text-muted-foreground">No integration bindings exist for this agent.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Outcome & savings</CardTitle><CardDescription>Calculated only from persisted change estimates.</CardDescription></CardHeader><CardContent>{data.savings.entries.length ? <div className="space-y-2">{data.savings.entries.map((entry) => <div key={entry.currency} className="flex items-center justify-between rounded-lg border p-3"><span className="text-sm">{entry.currency}</span><span className="font-semibold">{entry.amount.toLocaleString()}</span></div>)}</div> : <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Not estimated</div>}</CardContent></Card></div>
    <div className="mt-6 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Related changes</CardTitle><CardDescription>Changes explicitly associated with this agent.</CardDescription></CardHeader><CardContent className="space-y-2">{data.changes.length ? data.changes.map((change) => <Link key={change.rowId} to="/approvals/$id" params={{ id: change.rowId }} className="block rounded-lg border p-3 transition hover:bg-muted/30"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{change.title}</div><div className="text-xs text-muted-foreground">{change.changeId} · {change.stage} · {change.severity}</div></div><span className="text-xs text-primary">{change.savings}</span></div></Link>) : <div className="py-8 text-center text-sm text-muted-foreground">No related changes.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Recent activity</CardTitle><CardDescription>Audit-backed activity associated with this agent.</CardDescription></CardHeader><CardContent className="space-y-2">{data.activity.length ? data.activity.map((item, index) => <div key={`${item.createdAt}-${index}`} className="rounded-lg border p-3"><div className="flex items-center gap-2 text-sm"><ShieldCheck className="h-4 w-4 text-primary" /> {item.action}</div><div className="mt-1 text-xs text-muted-foreground">{item.detail ?? "No detail recorded"} · {new Date(item.createdAt).toLocaleString()}</div></div>) : <div className="py-8 text-center text-sm text-muted-foreground">No audit-backed activity recorded.</div>}</CardContent></Card></div>
    <Card className="mt-6"><CardHeader><CardTitle className="text-base">Agent configuration</CardTitle><CardDescription>Instructions currently stored for this tenant.</CardDescription></CardHeader><CardContent className="space-y-4">{([['Pre', data.instructions.pre], ['System', data.instructions.system], ['Post', data.instructions.post]] as const).map(([label, value]) => <div key={label}><div className="mb-1 text-xs font-medium">{label} instructions</div><div className="rounded-lg border bg-muted/20 p-3 text-sm whitespace-pre-wrap">{value ?? "Not configured"}</div></div>)}</CardContent></Card>
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string }) { return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-muted-foreground" /><div className="mt-2 break-words text-xl font-semibold">{value}</div><div className="text-xs text-muted-foreground">{label}</div></CardContent></Card>; }
