import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, CheckCircle2, ChevronDown, Clock3, Download, Eye, Gauge, MoreHorizontal, Plus, RefreshCw, ShieldAlert, ShieldCheck, Star, Trash2, Users } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { PageHeader } from "@/components/layout/AppLayout";
import { EmptyIntegrationsState } from "@/components/EmptyIntegrationsState";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { getCommandCenterData, type CommandCenterData } from "@/lib/command-center.functions";
import { getOnboardingStatus } from "@/lib/onboarding.functions";
import { createCustomDashboard, deleteCustomDashboard, listCustomDashboards, toggleCustomDashboardStar, type DashboardConfig } from "@/lib/custom-dashboards.functions";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/_app/")({
  head: () => pageHead({ path: "/", title: "Command Center — Aegis AI", description: "Evidence-first operational control plane for enterprise AI." }),
  loader: async () => {
    const [command, onboarding, saved] = await Promise.all([getCommandCenterData(), getOnboardingStatus(), listCustomDashboards()]);
    return { command, onboarding, dashboards: saved.dashboards as Dashboard[] };
  },
  component: DashboardPage,
});

type Dashboard = { id: string; name: string; starred: boolean; config: DashboardConfig };
type Finding = { id: string; name: string; status: "Active" | "Attention" | "Closed"; category: string; impact: string; severity: "Critical" | "High" | "Medium" | "Low"; affected: number; started: string; href: string };
const DEFAULT_WIDGETS = ["attention", "posture", "changes", "signals"];
const WIDGET_OPTIONS = [{ id: "attention", label: "Attention summary" }, { id: "posture", label: "Operational posture" }, { id: "changes", label: "Recent changes" }, { id: "signals", label: "Audit signals" }];

function DashboardPage() {
  const initial = Route.useLoaderData();
  const load = useServerFn(getCommandCenterData); const loadOnboarding = useServerFn(getOnboardingStatus); const loadDashboards = useServerFn(listCustomDashboards); const createDashboard = useServerFn(createCustomDashboard); const starDashboard = useServerFn(toggleCustomDashboardStar); const removeDashboard = useServerFn(deleteCustomDashboard);
  const [data, setData] = useState<CommandCenterData>(initial.command); const [setup, setSetup] = useState(initial.onboarding); const [dashboards, setDashboards] = useState<Dashboard[]>(initial.dashboards); const [selectedId, setSelectedId] = useState<string>("default"); const [loading, setLoading] = useState(false); const [dialogOpen, setDialogOpen] = useState(false); const [name, setName] = useState(""); const [widgets, setWidgets] = useState(DEFAULT_WIDGETS); const [busy, setBusy] = useState(false);
  const refresh = async () => { setLoading(true); try { const [command, onboarding, saved] = await Promise.all([load(), loadOnboarding(), loadDashboards()]); setData(command); setSetup(onboarding); setDashboards(saved.dashboards as Dashboard[]); } catch (error) { toast.error("Command Center unavailable", { description: error instanceof Error ? error.message : "Try again." }); } finally { setLoading(false); } };
  useEffect(() => { const id = window.setInterval(() => void refresh(), 60000); return () => window.clearInterval(id); }, [load, loadOnboarding, loadDashboards]);
  const selected = dashboards.find((d) => d.id === selectedId); const activeWidgets = selected?.config.widgets?.length ? selected.config.widgets : DEFAULT_WIDGETS;
  const findings = useMemo<Finding[]>(() => { if (!data) return []; const rows: Finding[] = []; const add = (id: string, name: string, status: Finding["status"], category: string, impact: string, severity: Finding["severity"], affected: number, href: string) => rows.push({ id, name, status, category, impact, severity, affected, started: data.generatedAt, href }); if (data.attention.pendingChanges) add("pending-changes", "Changes awaiting review", "Active", "Change risk", "Governed action", "High", data.attention.pendingChanges, "/approvals"); if (data.attention.proposedChanges) add("proposed-changes", "Proposed optimization changes", "Attention", "Optimization", "AI operations", "Medium", data.attention.proposedChanges, "/approvals"); if (data.attention.blockingGuardrailEvaluations) add("guardrail-blocks", "Guardrail evaluations requiring attention", "Active", "Governance", "AI agents", "Critical", data.attention.blockingGuardrailEvaluations, "/governance"); if (data.attention.integrationsNeedingAttention) add("integration-health", "Integration health needs attention", "Attention", "Availability", "Integrations", "High", data.attention.integrationsNeedingAttention, "/integrations"); if (!rows.length) add("healthy", "No active operational findings", "Closed", "Availability", "Workspace", "Low", 0, "/analytics"); return rows; }, [data]);
  const maxBars = Math.max(1, findings.length, data?.signals.length ?? 1);
  const showSetup = Boolean(setup && setup.providerCount === 0 && setup.deployedAgentCount === 0);
  const openCreate = () => { setName(""); setWidgets(DEFAULT_WIDGETS); setDialogOpen(true); };
  const saveNew = async () => { if (!name.trim()) { toast.error("Enter a dashboard name."); return; } setBusy(true); try { const result = await createDashboard({ data: { name, widgets } }); toast.success("Dashboard created"); setDialogOpen(false); await refresh(); setSelectedId(result.id); } catch (error) { toast.error("Could not create dashboard", { description: error instanceof Error ? error.message : "Try again." }); } finally { setBusy(false); } };
  const toggleStar = async (dashboard: Dashboard) => { try { await starDashboard({ data: { id: dashboard.id, starred: !dashboard.starred } }); await refresh(); } catch (error) { toast.error("Could not update favorite", { description: error instanceof Error ? error.message : "Try again." }); } };
  const deleteSelected = async () => { if (!selected) return; if (!window.confirm(`Delete ${selected.name}?`)) return; try { await removeDashboard({ data: { id: selected.id } }); setSelectedId("default"); await refresh(); toast.success("Dashboard deleted"); } catch (error) { toast.error("Could not delete dashboard", { description: error instanceof Error ? error.message : "Try again." }); } };
  return <div>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><div className="relative"><select value={selectedId} onChange={(e) => setSelectedId(e.target.value)} className="h-10 appearance-none rounded-md border bg-card pl-3 pr-9 text-sm font-semibold outline-none focus:ring-2 focus:ring-ring"><option value="default">Command Center</option>{dashboards.map((d) => <option key={d.id} value={d.id}>{d.starred ? "★ " : ""}{d.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 top-3 h-4 w-4 text-muted-foreground" /></div>{selected && <Badge variant="outline">Personal dashboard</Badge>}</div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`mr-1.5 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button><Button size="sm" onClick={openCreate}><Plus className="mr-1.5 h-4 w-4" />New dashboard</Button>{selected && <Button variant="ghost" size="icon" title="Delete dashboard" onClick={() => void deleteSelected()}><Trash2 className="h-4 w-4 text-destructive" /></Button>}</div></div>
    <PageHeader title={selected?.name ?? "Aegis Command Center"} description="Operational findings, health and governed action — presented in an evidence-first workspace." actions={selected ? <Button variant="ghost" size="sm" onClick={() => void toggleStar(selected)}>{selected.starred ? <Star className="mr-1.5 h-4 w-4 fill-current" /> : <Star className="mr-1.5 h-4 w-4" />}{selected.starred ? "Starred" : "Star"}</Button> : undefined} />
    {showSetup && <Card className="mb-4 border-primary/30"><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="text-sm font-semibold">Get Aegis ready</div><div className="text-xs text-muted-foreground">Connect a provider, deploy an agent and configure governance to populate live evidence.</div></div><Button size="sm" asChild><Link to="/integrations">Connect integration</Link></Button></CardContent></Card>}
    {loading && !data ? <div className="py-16 text-center text-sm text-muted-foreground">Loading operational evidence…</div> : !data?.live.connected ? <EmptyIntegrationsState title="No live provider evidence available" description="Connect and successfully synchronize a provider. Aegis will not fill this workspace with demo metrics." /> : <>
      <div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold"><span className="h-2 w-2 rounded-full bg-success" />{findings.filter((f) => f.status !== "Closed").length} active findings <span className="text-muted-foreground">/ {findings.length} total</span></div><div className="text-xs text-muted-foreground">refreshed {new Date(data.generatedAt).toLocaleTimeString()}</div></div>
      <div className="grid gap-4 xl:grid-cols-[230px_minmax(0,1fr)]">
        <Card className="h-fit"><CardHeader className="pb-3"><CardTitle className="text-sm">Filter by</CardTitle></CardHeader><CardContent className="space-y-5 pt-0"><FilterGroup title="Status" items={["All", "Active", "Attention", "Closed"]} /><FilterGroup title="Category" items={["Change risk", "Optimization", "Governance", "Availability"]} /><FilterGroup title="Impact" items={["AI agents", "Integrations", "Governed action", "Workspace"]} /><FilterGroup title="Severity" items={["Critical", "High", "Medium", "Low"]} /></CardContent></Card>
        <div className="min-w-0 space-y-4">
          <Card><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Badge variant="outline">Last 2 hours</Badge><div className="h-7 w-px bg-border" /><span className="text-xs text-muted-foreground">Operational activity</span></div><Button variant="outline" size="sm"><Download className="mr-1.5 h-4 w-4" />Export</Button></div><div className="mt-4 flex h-40 items-end gap-1 border-b border-border px-1">{Array.from({ length: 24 }).map((_, i) => { const value = Math.max(1, Math.round(((data.signals.length + findings.length * 2) / maxBars) * (0.25 + ((i * 17) % 75) / 100))); return <div key={i} className="group flex h-full flex-1 items-end" title={`${value} signals`}><div className="w-full rounded-t-sm bg-primary/70 transition-all group-hover:bg-primary" style={{ height: `${Math.min(100, value * 12)}%` }} /></div>; })}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>2h ago</span><span>1h ago</span><span>Now</span></div></CardContent></Card>
          <Card><CardContent className="p-0"><div className="flex items-center justify-between border-b px-4 py-3"><div className="text-sm font-semibold">Operational findings <span className="text-muted-foreground">{findings.length}</span></div><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="w-10 px-4 py-3" /><th className="px-3 py-3">Finding</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Impact</th><th className="px-3 py-3">Affected</th><th className="px-3 py-3">Started</th></tr></thead><tbody>{findings.map((finding) => <tr key={finding.id} className="border-b last:border-0 hover:bg-muted/20"><td className="px-4 py-3"><span className={`block h-2 w-2 rounded-full ${finding.severity === "Critical" ? "bg-destructive" : finding.severity === "High" ? "bg-warning" : finding.severity === "Medium" ? "bg-info" : "bg-muted-foreground"}`} /></td><td className="px-3 py-3"><Link to={finding.href as never} className="font-medium hover:text-primary">{finding.name}</Link><div className="text-[11px] text-muted-foreground">{finding.id}</div></td><td className="px-3 py-3"><Badge variant="outline" className={finding.status === "Active" ? "border-destructive/30 text-destructive" : finding.status === "Attention" ? "border-warning/40 text-warning-foreground" : "border-success/30 text-success"}>{finding.status}</Badge></td><td className="px-3 py-3 text-muted-foreground">{finding.category}</td><td className="px-3 py-3 text-muted-foreground">{finding.impact}</td><td className="px-3 py-3">{finding.affected}</td><td className="px-3 py-3 text-xs text-muted-foreground">{new Date(finding.started).toLocaleString()}</td></tr>)}</tbody></table></div></CardContent></Card>
          {activeWidgets.includes("attention") && <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><Kpi icon={AlertTriangle} label="Pending attention" value={data.attention.pendingChanges + data.attention.proposedChanges + data.attention.blockingGuardrailEvaluations} /><Kpi icon={ShieldAlert} label="High/Critical" value={data.risk.criticalOrHighOpen} /><Kpi icon={ShieldCheck} label="Guardrails" value={data.risk.guardrailsEnabled} /><Kpi icon={Bot} label="Real-bound agents" value={data.posture.agentsWithRealBindings} /><Kpi icon={Users} label="Agents configured" value={data.posture.agentsConfigured} /></div>}
          {activeWidgets.includes("posture") && <Card><CardHeader><CardTitle className="text-sm">Operational posture</CardTitle></CardHeader><CardContent className="grid gap-2 md:grid-cols-2">{data.posture.integrations.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border p-3"><div><div className="text-sm font-medium">{item.provider}</div><div className="text-xs text-muted-foreground">{item.lastSyncAt ? `Last sync ${new Date(item.lastSyncAt).toLocaleString()}` : "No persisted sync"}</div></div><Badge variant="outline" className={item.status === "connected" && item.healthStatus !== "unhealthy" ? "border-success/30 text-success" : "border-warning/40 text-warning-foreground"}>{item.status}</Badge></div>)}</CardContent></Card>}
          <div className="grid gap-4 xl:grid-cols-2">{activeWidgets.includes("changes") && <Card><CardHeader><CardTitle className="text-sm">Recent changes</CardTitle></CardHeader><CardContent className="space-y-2">{data.changed.slice(0, 6).map((change) => <Link key={change.id} to="/approvals/$id" params={{ id: change.id }} className="flex items-center justify-between rounded-md border p-3 hover:bg-muted/30"><div className="min-w-0"><div className="truncate text-sm font-medium">{change.title}</div><div className="text-xs text-muted-foreground">{change.changeId} · {change.ownerTeam}</div></div><Badge variant="outline">{change.severity}</Badge></Link>)}</CardContent></Card>}{activeWidgets.includes("signals") && <Card><CardHeader><CardTitle className="text-sm">Recent audit signals</CardTitle></CardHeader><CardContent className="space-y-2">{data.signals.slice(0, 6).map((signal) => <div key={signal.id} className="rounded-md border p-3"><div className="flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4 text-primary" />{signal.action}</div><div className="mt-1 text-xs text-muted-foreground">{signal.entityType}{signal.entityId ? ` · ${signal.entityId}` : ""}</div></div>)}</CardContent></Card>}</div>
        </div>
      </div>
    </>}
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>Create dashboard</DialogTitle><DialogDescription>Create a personal Command Center view. Operational data always comes from the same live evidence source.</DialogDescription></DialogHeader><div className="space-y-4"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Support AI Operations" autoFocus /><div><div className="mb-2 text-sm font-medium">Widgets</div><div className="grid gap-2">{WIDGET_OPTIONS.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-md border p-3 text-sm"><input type="checkbox" checked={widgets.includes(item.id)} onChange={(e) => setWidgets((current) => e.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} />{item.label}</label>)}</div></div></div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button><Button onClick={() => void saveNew()} disabled={busy}>{busy ? "Creating…" : "Create dashboard"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function FilterGroup({ title, items }: { title: string; items: string[] }) { return <div><div className="mb-2 flex items-center justify-between text-xs font-semibold">{title}<ChevronDown className="h-3.5 w-3.5 text-muted-foreground" /></div><div className="space-y-2">{items.map((item, index) => <label key={item} className="flex items-center gap-2 text-xs text-muted-foreground"><input type={title === "Status" ? "radio" : "checkbox"} name={title} defaultChecked={index === 0 && title === "Status"} className="accent-[var(--primary)]" />{item}</label>)}</div></div>; }
function Kpi({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: number }) { return <Card><CardContent className="p-3"><Icon className="h-4 w-4 text-muted-foreground" /><div className="mt-1 text-xl font-semibold">{value.toLocaleString()}</div><div className="text-[11px] text-muted-foreground">{label}</div></CardContent></Card>; }