import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/AppLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { useTenantContext } from "@/lib/tenant";
import { DEMO_AGENT_OUTCOMES, DEMO_AGENT_CONNECTIONS } from "@/lib/demo-data";
import { DEMO_AGENT_OUTCOMES, DEMO_AGENT_CONNECTIONS } from "@/lib/demo-data";
import { DEMO_AGENT_OUTCOMES, DEMO_AGENT_CONNECTIONS } from "@/lib/demo-data";
import { ArrowRight, Link2, Plus, ShieldCheck, Trash2, Workflow } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_app/agentic-studio/governance")({ component: AgenticGovernancePage });
type Outcome = { id: string; agent_key: string; name: string; description: string | null; trigger_config: Record<string, unknown>; approval_required: boolean; enabled: boolean };
type Connection = { id: string; source_agent_key: string; target_agent_key: string; purpose: string | null; allowed_capabilities: string[]; approval_required: boolean; enabled: boolean };
const agents = [{ key: "agent-license", name: "License Agent" }, { key: "agent-security", name: "Security Agent" }, { key: "agent-cost", name: "Cost Agent" }, { key: "agent-incident", name: "Incident Agent" }, { key: "agent-workflow", name: "Workflow Agent" }];

export function AgenticGovernancePage() {
  const { tenantId, environmentMode } = useTenantContext();
  const [outcomes, setOutcomes] = useState<Outcome[]>([]); const [connections, setConnections] = useState<Connection[]>([]);
  const [agent, setAgent] = useState("agent-license"); const [name, setName] = useState(""); const [description, setDescription] = useState("");
  const [source, setSource] = useState("agent-license"); const [target, setTarget] = useState("agent-security"); const [purpose, setPurpose] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { if (!tenantId) return; setLoading(true); if (environmentMode === "demo") { setOutcomes(DEMO_AGENT_OUTCOMES as Outcome[]); setConnections(DEMO_AGENT_CONNECTIONS as Connection[]); setLoading(false); return; } const [o, c] = await Promise.all([supabase.from("agent_outcomes").select("id,agent_key,name,description,trigger_config,approval_required,enabled").eq("tenant_id", tenantId).order("created_at"), supabase.from("agent_connections").select("id,source_agent_key,target_agent_key,purpose,allowed_capabilities,approval_required,enabled").eq("tenant_id", tenantId).order("created_at")]); setOutcomes((o.data ?? []) as Outcome[]); setConnections((c.data ?? []) as Connection[]); setLoading(false); };
  useEffect(() => { void load(); }, [tenantId, environmentMode]);
  const addOutcome = async () => { if (!tenantId || !name.trim() || saving) return; setSaving(true); if (environmentMode === "demo") { setOutcomes((current) => [...current, { id:`demo-outcome-${Date.now()}`, agent_key:agent, name:name.trim(), description:description.trim() || null, trigger_config:{}, approval_required:true, enabled:true }]); setSaving(false); setName(""); setDescription(""); toast.success("Demo governed outcome created"); return; } const { error } = await supabase.from("agent_outcomes").insert({ tenant_id: tenantId, agent_key: agent, name: name.trim(), description: description.trim() || null, trigger_config: {}, approval_required: true, enabled: true }); setSaving(false); if (error) { toast.error("Outcome could not be created", { description: error.message }); return; } setName(""); setDescription(""); await load(); toast.success("Governed outcome created"); };
  const addConnection = async () => { if (!tenantId || source === target || saving) return; setSaving(true); if (environmentMode === "demo") { setConnections((current) => [...current, { id:`demo-connection-${Date.now()}`, source_agent_key:source, target_agent_key:target, purpose:purpose.trim() || null, allowed_capabilities:[], approval_required:true, enabled:true }]); setSaving(false); setPurpose(""); toast.success("Demo governed relationship created"); return; } const { error } = await supabase.from("agent_connections").insert({ tenant_id: tenantId, source_agent_key: source, target_agent_key: target, purpose: purpose.trim() || null, allowed_capabilities: [], approval_required: true, enabled: true }); setSaving(false); if (error) { toast.error("Relationship could not be created", { description: error.message }); return; } setPurpose(""); await load(); toast.success("Governed relationship created"); };
  const toggle = async (table: "agent_outcomes" | "agent_connections", id: string, field: "enabled" | "approval_required", value: boolean) => { if (!tenantId) return; if (environmentMode === "demo") { if (table === "agent_outcomes") setOutcomes((current) => current.map((row) => row.id === id ? ({ ...row, [field]: value } as Outcome) : row)); else setConnections((current) => current.map((row) => row.id === id ? ({ ...row, [field]: value } as Connection) : row)); return; } const { error } = await supabase.from(table).update({ [field]: value }).eq("id", id).eq("tenant_id", tenantId); if (error) toast.error("Policy could not be updated", { description: error.message }); else await load(); };
  const remove = async (table: "agent_outcomes" | "agent_connections", id: string) => { if (!tenantId) return; if (environmentMode === "demo") { if (table === "agent_outcomes") setOutcomes((current) => current.filter((row) => row.id !== id)); else setConnections((current) => current.filter((row) => row.id !== id)); return; } const { error } = await supabase.from(table).delete().eq("id", id).eq("tenant_id", tenantId); if (error) toast.error("Object could not be removed", { description: error.message }); else await load(); };
  return <div className="space-y-5">
    <PageHeader title="Agent Governance" description="The deployed agent is the worker. Governance is the durable policy boundary: allowed outcomes, approval gates and permitted agent-to-agent relationships." actions={<Button variant="outline" asChild><Link to="/agentic-studio">Back to Studio</Link></Button>} />
    <Card><CardHeader><CardTitle className="text-sm">Governance control plane</CardTitle><CardDescription>These are persisted tenant-scoped policy objects. They are intentionally separate from the agent's deployment configuration.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><div className="rounded-lg border p-4"><div className="text-2xl font-semibold">{outcomes.length}</div><div className="text-xs text-muted-foreground">governed outcomes</div></div><div className="rounded-lg border p-4"><div className="text-2xl font-semibold">{connections.length}</div><div className="text-xs text-muted-foreground">agent relationships</div></div><div className="rounded-lg border p-4"><div className="text-sm font-medium">Approval</div><div className="mt-1 text-xs text-muted-foreground">New objects start approval-gated.</div></div><div className="rounded-lg border p-4"><div className="text-sm font-medium">Evidence</div><div className="mt-1 text-xs text-muted-foreground">Changes are persisted against the tenant.</div></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Plus className="h-4 w-4" />Multiple outcomes per agent</CardTitle><CardDescription>Create real, independently enabled objectives instead of showing synthetic proposals.</CardDescription></CardHeader><CardContent className="space-y-3"><Select value={agent} onValueChange={setAgent}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{agents.map(a => <SelectItem key={a.key} value={a.key}>{a.name}</SelectItem>)}</SelectContent></Select><Input value={name} onChange={e => setName(e.target.value)} placeholder="Outcome name" /><Input value={description} onChange={e => setDescription(e.target.value)} placeholder="Outcome description" /><Button onClick={() => void addOutcome()} disabled={!name.trim() || saving}>Create outcome</Button><div className="space-y-2 pt-2">{loading ? <div className="text-xs text-muted-foreground">Loading…</div> : outcomes.length ? outcomes.map(o => <div key={o.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><div><div className="text-sm font-medium">{o.name}</div><div className="mt-1 text-xs text-muted-foreground">{o.agent_key} · {o.description || "No description"}</div></div><Button variant="ghost" size="icon" onClick={() => void remove("agent_outcomes", o.id)}><Trash2 className="h-4 w-4" /></Button></div><div className="mt-3 flex flex-wrap gap-3 text-xs"><Badge variant="outline">{Object.keys(o.trigger_config || {}).length ? "Triggered" : "No trigger"}</Badge><label className="flex items-center gap-2"><Switch checked={o.approval_required} onCheckedChange={v => void toggle("agent_outcomes", o.id, "approval_required", v)} />Approval</label><label className="flex items-center gap-2"><Switch checked={o.enabled} onCheckedChange={v => void toggle("agent_outcomes", o.id, "enabled", v)} />Enabled</label></div></div>) : <div className="rounded-md border border-dashed p-4 text-xs text-muted-foreground">No outcomes configured. Create the first governed objective above.</div>}</div></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Link2 className="h-4 w-4" />Agent-to-agent governance</CardTitle><CardDescription>Configure an explicit source → target relationship. This is an authorization boundary, not a claim that runtime A2A execution already exists.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{agents.map(a => <SelectItem key={a.key} value={a.key}>{a.name}</SelectItem>)}</SelectContent></Select><ArrowRight className="h-4 w-4" /><Select value={target} onValueChange={setTarget}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{agents.filter(a => a.key !== source).map(a => <SelectItem key={a.key} value={a.key}>{a.name}</SelectItem>)}</SelectContent></Select></div><Input value={purpose} onChange={e => setPurpose(e.target.value)} placeholder="Relationship purpose" /><Button onClick={() => void addConnection()} disabled={source === target || saving}>Create relationship</Button><div className="space-y-2 pt-2">{connections.length ? connections.map(c => <div key={c.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 text-sm font-medium"><Workflow className="h-4 w-4 text-primary" />{c.source_agent_key}<ArrowRight className="h-3.5 w-3.5" />{c.target_agent_key}</div><Button variant="ghost" size="icon" onClick={() => void remove("agent_connections", c.id)}><Trash2 className="h-4 w-4" /></Button></div><div className="mt-1 text-xs text-muted-foreground">{c.purpose || "No purpose configured"}</div><div className="mt-3 flex flex-wrap gap-3 text-xs"><label className="flex items-center gap-2"><Switch checked={c.approval_required} onCheckedChange={v => void toggle("agent_connections", c.id, "approval_required", v)} />Approval</label><label className="flex items-center gap-2"><Switch checked={c.enabled} onCheckedChange={v => void toggle("agent_connections", c.id, "enabled", v)} />Enabled</label><Badge variant="outline">{c.allowed_capabilities.length} capabilities</Badge></div></div>) : <div className="rounded-md border border-dashed p-4 text-xs text-muted-foreground">No relationships configured. Create one only when a real workflow needs an agent hand-off.</div>}</div></CardContent></Card>
    </div>
    <Card><CardContent className="flex gap-3 p-4 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" /><div><div className="font-medium text-foreground">Governance → Approval → Execution → Verify</div><div className="mt-1">Agentic Studio plans the work; Governance defines the policy boundary; Approval Center is the human gate; runtime execution and Audit/Verify provide evidence.</div></div></CardContent></Card>
  </div>;
}
