import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, Bot, CheckCircle2, CircleCheck, Clock3, Eye, Gauge, RefreshCw, ShieldAlert, ShieldCheck, Users } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { PageHeader } from "@/components/layout/AppLayout";
import { EmptyIntegrationsState } from "@/components/EmptyIntegrationsState";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getCommandCenterData, type CommandCenterData } from "@/lib/command-center.functions";
import { getOnboardingStatus } from "@/lib/onboarding.functions";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/_app/")({ head: () => pageHead({ path: "/", title: "Aegis Command Center — Aegis AI", description: "The Aegis control plane for enterprise AI operations, governance, optimization and governed action." }), component: DashboardPage });

function DashboardPage() {
  const load = useServerFn(getCommandCenterData); const loadOnboarding = useServerFn(getOnboardingStatus);
  const [data, setData] = useState<CommandCenterData | null>(null); const [setup, setSetup] = useState<{ providerCount: number; deployedAgentCount: number; guardrailCount: number } | null>(null); const [loading, setLoading] = useState(true); const [setupOpen, setSetupOpen] = useState(true);
  const refresh = async () => { setLoading(true); try { const [command, onboarding] = await Promise.all([load(), loadOnboarding()]); setData(command); setSetup(onboarding); } catch (error) { toast.error("Command Center unavailable", { description: error instanceof Error ? error.message : "Try again." }); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 60000); return () => window.clearInterval(id); }, [load, loadOnboarding]);
  const showSetup = Boolean(setup && setup.providerCount === 0 && setup.deployedAgentCount === 0);
  const connectedIntegrations = data?.posture.integrations.filter((item) => item.status === "connected").length ?? 0;
  const unhealthyIntegrations = data?.posture.integrations.filter((item) => item.status !== "connected" || item.healthStatus === "unhealthy").length ?? 0;
  return <div><PageHeader title="Aegis Command Center" description="The control plane for enterprise AI: observe what is happening, govern risk, optimize operations and move into verified action." actions={<Button variant="outline" size="sm" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`mr-1.5 h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Refresh</Button>} />
    <Card className="mb-4 overflow-hidden border-primary/20 bg-primary/[0.03]"><CardContent className="p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Gauge className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">AI Operations Control Plane</span><Badge variant="outline" className="text-[10px]">Evidence first</Badge></div><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">Aegis is designed to sit above the systems that execute work. It brings provider evidence, AI agents, guardrails, change control and outcomes into one governed operational loop.</p></div></div><div className="flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span className="rounded-full border px-2.5 py-1">Observe</span><ArrowRight className="mt-1 h-3 w-3" /><span className="rounded-full border px-2.5 py-1">Govern</span><ArrowRight className="mt-1 h-3 w-3" /><span className="rounded-full border px-2.5 py-1">Optimize</span><ArrowRight className="mt-1 h-3 w-3" /><span className="rounded-full border px-2.5 py-1">Act</span><ArrowRight className="mt-1 h-3 w-3" /><span className="rounded-full border px-2.5 py-1">Verify</span></div></div></CardContent></Card>
    {showSetup && setupOpen && <Card className="mb-4 border-primary/30"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-base">Get Aegis ready</CardTitle><CardDescription>Completion is derived from your real tenant configuration.</CardDescription></div><Button size="sm" variant="ghost" onClick={() => setSetupOpen(false)}>Collapse</Button></div></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{[{ done: setup!.providerCount > 0, title: "Connect a provider", to: "/integrations" as const }, { done: setup!.deployedAgentCount > 0, title: "Deploy an agent", to: "/agents" as const }, { done: setup!.guardrailCount > 0, title: "Configure a guardrail", to: "/settings" as const }].map((step, index) => <Link key={step.title} to={step.to} className="rounded-lg border p-4 hover:bg-muted/30"><div className="flex items-center gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full border">{step.done ? <CheckCircle2 className="h-4 w-4 text-success" /> : index + 1}</span><span className="text-sm font-medium">{step.title}</span></div></Link>)}</CardContent></Card>}
    {loading && !data ? <div className="py-16 text-center text-sm text-muted-foreground">Loading real operational evidence…</div> : !data?.live.connected ? <EmptyIntegrationsState title="No live provider evidence available" description="Connect and successfully synchronize a provider. Aegis will not fill the Command Center with demo metrics." /> : <>
      <div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline" className="border-success/40 text-success">Live evidence</Badge><span className="text-xs text-muted-foreground">Generated {new Date(data.generatedAt).toLocaleString()}</span>{data.posture.lastSyncRunAt && <span className="text-xs text-muted-foreground">• Last sync run {new Date(data.posture.lastSyncRunAt).toLocaleString()}</span>}</div>
      <div className="mb-6 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><ControlStage icon={Eye} title="Observe" description="Connected systems and evidence" value={`${connectedIntegrations} connected`} href="/integrations" /><ControlStage icon={ShieldCheck} title="Govern" description="Policies and risk controls" value={`${data.risk.guardrailsEnabled} enforcing`} href="/governance" /><ControlStage icon={Gauge} title="Optimize" description="Signals ready for analysis" value={`${data.attention.proposedChanges} proposed`} href="/analytics" /><ControlStage icon={ShieldAlert} title="Act" description="Governed work awaiting action" value={`${data.attention.pendingChanges} pending`} href="/approvals" /><ControlStage icon={CircleCheck} title="Verify" description="Latest synchronization posture" value={data.posture.lastSyncRunStatus ? String(data.posture.lastSyncRunStatus) : "No sync run"} href="/integrations" tone={unhealthyIntegrations > 0 ? "warning" : "success"} /></div>
      <div className="grid grid-cols-2 gap-4 xl:grid-cols-5"><Kpi icon={AlertTriangle} label="Pending attention" value={data.attention.pendingChanges + data.attention.proposedChanges + data.attention.blockingGuardrailEvaluations} /><Kpi icon={ShieldAlert} label="High/Critical open" value={data.risk.criticalOrHighOpen} /><Kpi icon={ShieldCheck} label="Guardrails enforcing" value={data.risk.guardrailsEnabled} /><Kpi icon={Bot} label="Real-bound agents" value={data.posture.agentsWithRealBindings} /><Kpi icon={Users} label="Configured agents" value={data.posture.agentsConfigured} /></div>
      <div className="mt-6 grid gap-4 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><CardTitle className="text-base">What needs attention</CardTitle><CardDescription>Counts are derived from real tenant records and recent governance evaluations.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Attention label="Changes awaiting review" value={data.attention.pendingChanges} href="/approvals" /><Attention label="Proposed changes" value={data.attention.proposedChanges} href="/approvals" /><Attention label="Non-allow guardrail evaluations" value={data.attention.blockingGuardrailEvaluations} href="/governance" /><Attention label="Integrations needing attention" value={data.attention.integrationsNeedingAttention} href="/integrations" /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Operational posture</CardTitle><CardDescription>Real connection and sync state.</CardDescription></CardHeader><CardContent className="space-y-2">{data.posture.integrations.length ? data.posture.integrations.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg border p-3"><div><div className="text-sm font-medium">{item.provider}</div><div className="text-xs text-muted-foreground">{item.lastSyncAt ? `Last sync ${new Date(item.lastSyncAt).toLocaleString()}` : "No persisted sync"}</div></div><Badge variant="outline" className={item.status === "connected" && item.healthStatus !== "unhealthy" ? "border-success/40 text-success" : ""}>{item.status}</Badge></div>) : <div className="py-6 text-center text-sm text-muted-foreground">No integrations configured.</div>}</CardContent></Card></div>
      <div className="mt-6 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Recent changes</CardTitle><CardDescription>Change-control activity that needs operational context.</CardDescription></CardHeader><CardContent className="space-y-2">{data.changed.length ? data.changed.map((change) => <Link key={change.id} to="/approvals/$id" params={{ id: change.id }} className="block rounded-lg border p-3 hover:bg-muted/30"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{change.title}</div><div className="text-xs text-muted-foreground">{change.changeId} · {change.ownerTeam}</div></div><Badge variant="outline">{change.severity}</Badge></div><div className="mt-1 text-xs text-muted-foreground">{change.stage} · updated {new Date(change.updatedAt).toLocaleString()}</div></Link>) : <div className="py-8 text-center text-sm text-muted-foreground">No change records yet.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Recent audit signals</CardTitle><CardDescription>Evidence from the append-only audit stream.</CardDescription></CardHeader><CardContent className="space-y-2">{data.signals.length ? data.signals.slice(0, 8).map((signal) => <div key={signal.id} className="rounded-lg border p-3"><div className="flex items-center gap-2 text-sm"><Activity className="h-4 w-4 text-primary" />{signal.action}</div><div className="mt-1 text-xs text-muted-foreground">{signal.entityType}{signal.entityId ? ` · ${signal.entityId}` : ""} · {new Date(signal.createdAt).toLocaleString()}</div></div>) : <div className="py-8 text-center text-sm text-muted-foreground">No recent audit signals.</div>}</CardContent></Card></div>
      <Card className="mt-6"><CardHeader><CardTitle className="text-base">Continue the operational loop</CardTitle><CardDescription>Move from observation into evidence-backed investigation, measurement and governed action.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Button asChild><Link to="/investigations" search={{ key: undefined }}>Investigate findings</Link></Button><Button variant="outline" asChild><Link to="/analytics">Measure outcomes</Link></Button><Button variant="outline" asChild><Link to="/chat">Ask Aegis</Link></Button><Button variant="outline" asChild><Link to="/approvals">Open Approval Center</Link></Button></CardContent></Card>
    </>}
  </div>;
}
function ControlStage({ icon: Icon, title, description, value, href, tone = "neutral" }: { icon: React.ComponentType<{ className?: string }>; title: string; description: string; value: string; href: "/integrations" | "/governance" | "/analytics" | "/approvals"; tone?: "success" | "warning" | "neutral" }) { const toneClass = tone === "success" ? "text-success" : tone === "warning" ? "text-warning-foreground" : "text-primary"; return <Link to={href} className="group rounded-xl border bg-card p-4 transition-colors hover:bg-muted/30"><div className="flex items-start justify-between gap-2"><div className={`flex h-8 w-8 items-center justify-center rounded-lg bg-muted ${toneClass}`}><Icon className="h-4 w-4" /></div><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></div><div className="mt-3 text-sm font-semibold">{title}</div><div className="mt-0.5 text-xs text-muted-foreground">{description}</div><div className="mt-2 text-xs font-medium capitalize">{value}</div></Link>; }
function Kpi({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: number }) { return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-muted-foreground" /><div className="mt-2 text-2xl font-semibold">{value.toLocaleString()}</div><div className="text-xs text-muted-foreground">{label}</div></CardContent></Card>; }
function Attention({ label, value, href }: { label: string; value: number; href: "/approvals" | "/governance" | "/integrations" }) { return <Link to={href} className="rounded-lg border p-4 hover:bg-muted/30"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 flex items-center gap-2"><span className="text-xl font-semibold">{value.toLocaleString()}</span><Clock3 className="h-4 w-4 text-muted-foreground" /></div></Link>; }
