import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/AppLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useServerFn } from "@tanstack/react-start";
import { discoverItsmRouting } from "@/lib/itsm-routing.functions";
import { useTenantContext } from "@/lib/tenant";
import { DEMO_ITSM_INTEGRATIONS, DEMO_ITSM_CONFIGS, DEMO_ITSM_DISCOVERY } from "@/lib/demo-data";

export const Route = createFileRoute("/_app/settings/itsm-routing")({ component: ItsmRoutingPage });
type Integration = { id: string; provider: "jira" | "servicenow"; display_name: string | null };
type Config = { id: string; integration_id: string; provider: string; target_config: Record<string, string>; issue_type: string | null; notification_emails: string[]; is_default: boolean; automatic_trigger_enabled: boolean };
type Discovery = { projects?: { id: string; key: string; name: string }[]; issueTypes?: { id: string; name: string }[]; categories?: { id: string; name: string }[]; assignmentGroups?: { id: string; name: string }[] };

function ItsmRoutingPage() {
  const { tenantId, environmentMode } = useTenantContext(); const discover = useServerFn(discoverItsmRouting);
  const [integrations, setIntegrations] = useState<Integration[]>([]); const [configs, setConfigs] = useState<Config[]>([]); const [selected, setSelected] = useState<Integration | null>(null); const [discovery, setDiscovery] = useState<Discovery | null>(null);
  const [target, setTarget] = useState(""); const [issueType, setIssueType] = useState(""); const [category, setCategory] = useState(""); const [emails, setEmails] = useState(""); const [automatic, setAutomatic] = useState(false); const [saving, setSaving] = useState(false); const [loadingDiscovery, setLoadingDiscovery] = useState(false); const [error, setError] = useState("");
  const load = async () => { if (!tenantId) return; if (environmentMode === "demo") { setIntegrations(DEMO_ITSM_INTEGRATIONS); setConfigs(DEMO_ITSM_CONFIGS as Config[]); return; } const [i, c] = await Promise.all([supabase.from("integrations").select("id,provider,display_name").eq("tenant_id", tenantId).in("provider", ["jira", "servicenow"]).eq("status", "connected").eq("is_mock", false), (supabase as any).from("itsm_routing_config").select("id,integration_id,provider,target_config,issue_type,notification_emails,is_default,automatic_trigger_enabled").eq("tenant_id", tenantId)]); setIntegrations((i.data ?? []) as Integration[]); setConfigs((c.data ?? []) as Config[]); };
  useEffect(() => { void load(); }, [tenantId, environmentMode]);
  useEffect(() => { const c = selected && configs.find((x) => x.integration_id === selected.id); setTarget(c?.target_config?.projectKey ?? c?.target_config?.assignmentGroup ?? ""); setCategory(c?.target_config?.category ?? ""); setIssueType(c?.issue_type ?? ""); setEmails((c?.notification_emails ?? []).join(", ")); setAutomatic(Boolean(c?.automatic_trigger_enabled)); setDiscovery(null); setError(""); if (selected) { setLoadingDiscovery(true); if (environmentMode === "demo") { setDiscovery(DEMO_ITSM_DISCOVERY[selected.provider]); setLoadingDiscovery(false); } else void discover({ data: { integrationId: selected.id, provider: selected.provider } }).then(setDiscovery).catch((e) => setError(e instanceof Error ? e.message : "Could not load provider options.")).finally(() => setLoadingDiscovery(false)); } }, [selected, configs]);
  const save = async () => { if (!tenantId || !selected || !target) return; setSaving(true); setError(""); const old = configs.find((x) => x.integration_id === selected.id); if (old) { await (supabase as any).from("itsm_routing_config").update({ is_default: false }).eq("tenant_id", tenantId).eq("provider", selected.provider).neq("id", old.id); } const payload = { tenant_id: tenantId, integration_id: selected.id, provider: selected.provider, target_config: selected.provider === "jira" ? { projectKey: target } : { assignmentGroup: target, category: category || null }, issue_type: selected.provider === "jira" ? issueType : "Change Request", default_priority_mapping: { Critical: "1", High: "2", Medium: "3", Low: "4" }, notification_emails: emails.split(",").map((e) => e.trim()).filter(Boolean), is_default: true, automatic_trigger_enabled: automatic, automatic_trigger_stage: automatic ? "Team Approvals" : null, automatic_trigger_severity: automatic ? "Critical" : null }; if (environmentMode === "demo") { const next = { ...payload, id: old?.id ?? `demo-routing-${Date.now()}` } as Config; setConfigs((current) => old ? current.map((row) => row.id === old.id ? next : row) : [...current, next]); setSaving(false); return; } const result = old ? await (supabase as any).from("itsm_routing_config").update(payload).eq("id", old.id).eq("tenant_id", tenantId) : await (supabase as any).from("itsm_routing_config").insert(payload); setSaving(false); if (result.error) { setError(result.error.message); return; } await load(); };
  return <div className="space-y-5"><PageHeader title="ITSM Routing" description="Route Approval Center tickets only to a real connected Jira project or ServiceNow assignment group. Provider options are fetched live." actions={<Button variant="outline" asChild><Link to="/settings">Back to Settings</Link></Button>} />
    <Card><CardHeader><CardTitle className="text-sm">Connected ITSM systems</CardTitle><CardDescription>Only connected non-mock integrations are eligible.</CardDescription></CardHeader><CardContent>{integrations.length ? <div className="grid gap-2 md:grid-cols-2">{integrations.map((i) => <button key={i.id} type="button" onClick={() => setSelected(i)} className={`rounded-lg border p-3 text-left ${selected?.id === i.id ? "border-primary bg-primary/5" : ""}`}><div className="flex items-center justify-between"><span className="text-sm font-medium">{i.display_name ?? i.provider}</span><Badge variant="outline">{i.provider}</Badge></div></button>)}</div> : <div className="rounded-md border border-dashed p-5 text-sm text-muted-foreground">No real Jira or ServiceNow connection is available. Connect one first.</div>}</CardContent></Card>
    {selected && <Card><CardHeader><CardTitle className="text-sm">Routing configuration</CardTitle><CardDescription>{loadingDiscovery ? "Loading live provider options…" : "Choose only values returned by the connected provider. Automatic ticket creation is disabled by default."}</CardDescription></CardHeader><CardContent className="space-y-4">{error && <div className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
      {selected.provider === "jira" ? <><div><label className="text-xs font-medium">Jira project</label><Select value={target} onValueChange={setTarget}><SelectTrigger className="mt-1"><SelectValue placeholder="Select project" /></SelectTrigger><SelectContent>{(discovery?.projects ?? []).map((p) => <SelectItem key={p.id} value={p.key}>{p.key} — {p.name}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs font-medium">Issue type</label><Select value={issueType} onValueChange={setIssueType}><SelectTrigger className="mt-1"><SelectValue placeholder="Select issue type" /></SelectTrigger><SelectContent>{(discovery?.issueTypes ?? []).map((t) => <SelectItem key={t.id} value={t.name}>{t.name}</SelectItem>)}</SelectContent></Select></div></> : <><div><label className="text-xs font-medium">ServiceNow assignment group</label><Select value={target} onValueChange={setTarget}><SelectTrigger className="mt-1"><SelectValue placeholder="Select assignment group" /></SelectTrigger><SelectContent>{(discovery?.assignmentGroups ?? []).map((g) => <SelectItem key={g.id} value={g.name}>{g.name}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs font-medium">Change category</label><Select value={category} onValueChange={setCategory}><SelectTrigger className="mt-1"><SelectValue placeholder="Select category" /></SelectTrigger><SelectContent>{(discovery?.categories ?? []).map((c) => <SelectItem key={c.id} value={c.name}>{c.name}</SelectItem>)}</SelectContent></Select></div></>}
      <div><label className="text-xs font-medium">Risk → priority mapping</label><div className="mt-1 grid grid-cols-4 gap-2">{["Critical","High","Medium","Low"].map((risk, i) => <div key={risk} className="rounded-md border p-2 text-center text-xs"><div className="font-medium">{risk}</div><div className="text-muted-foreground">Priority {i + 1}</div></div>)}</div></div>
      <div><label className="text-xs font-medium">Notification recipients</label><Input className="mt-1" value={emails} onChange={(e) => setEmails(e.target.value)} placeholder="user@example.com, team@example.com" /></div>
      <div className="flex items-center justify-between rounded-md border p-3"><div><div className="text-sm font-medium">Automatic trigger</div><div className="text-xs text-muted-foreground">Create a ticket at Team Approvals when risk is Critical. Approval gating remains unchanged.</div></div><Switch checked={automatic} onCheckedChange={setAutomatic} /></div>
      <Button disabled={saving || loadingDiscovery || !target || (selected.provider === "jira" && !issueType)} onClick={() => void save()}>{saving ? "Saving…" : "Save routing"}</Button>
    </CardContent></Card>}
  </div>;
}
