import type { ReactNode } from "react";
import { Activity, Bot, CheckCircle2, Clock3, Coins, ArrowRight, GitBranch, RefreshCw, Users, Zap } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Analytics } from "@/routes/_app.analytics.types";

export const PRESETS = [7, 30, 60, 90] as const;

export function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string | number }) {
  return <Card><CardContent className="p-4"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{label}</span><Icon className="h-4 w-4" /></div><div className="mt-2 text-2xl font-semibold">{value}</div></CardContent></Card>;
}
export function MetricSmall({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>; }
export function EmptyPanel({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="rounded-lg border border-dashed p-8 text-center"><div className="mx-auto mb-2 flex h-9 w-9 items-center justify-center rounded-full bg-muted"><CheckCircle2 className="h-4 w-4 text-muted-foreground" /></div><div className="font-medium">{title}</div><div className="mx-auto mt-1 max-w-xl text-sm text-muted-foreground">{detail}</div>{action ? <div className="mt-4">{action}</div> : null}</div>; }

export function OverviewView({ data, max }: { data: Analytics; max: number }) {
  const total = data.platform.totalEvents + data.platform.changeRecords + data.ai.requests;
  return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Metric icon={Activity} label="Audit events" value={data.platform.totalEvents.toLocaleString()} /><Metric icon={Users} label="Active actors" value={data.platform.activeUsers.toLocaleString()} /><Metric icon={GitBranch} label="Change records" value={data.platform.changeRecords.toLocaleString()} /><Metric icon={Bot} label="AI requests" value={data.ai.requests.toLocaleString()} /><Metric icon={Clock3} label="Avg AI latency" value={`${data.ai.averageLatencyMs} ms`} /></div><Card><CardHeader><CardTitle className="text-sm">Operational trend</CardTitle><div className="text-xs text-muted-foreground">Daily evidence volume across audit events, change records and AI usage.</div></CardHeader><CardContent>{total ? <><div className="flex h-40 items-end gap-1">{data.trends.map((item) => { const value = item.events + item.changes + item.aiRequests; return <div key={item.date} className="flex h-full flex-1 items-end" title={`${item.date}: ${value} records`}><div className="w-full rounded-t bg-primary/70" style={{ height: `${Math.max(2, (value / max) * 100)}%` }} /></div>; })}</div><div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>{data.period.from.slice(0, 10)}</span><span>{data.period.to.slice(0, 10)}</span></div></> : <EmptyPanel title="No operational evidence in this range" detail="Audit events, change records and AI usage depend on rows being recorded in the selected period." />}</CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-sm">Governance posture</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><MetricSmall label="Pending changes" value={data.platform.pendingChanges} /><MetricSmall label="Critical changes" value={data.severityCounts.critical ?? 0} /><MetricSmall label="Roles represented" value={data.platform.connectedRoles} /><MetricSmall label="Users in tenant" value={data.platform.totalUsers} /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Evidence notes</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>Values are derived from tenant-scoped analytics evidence or the report workspace service.</p><p>Empty windows remain zero rather than being replaced by synthetic activity.</p></CardContent></Card></div></div>;
}

export function AiUsageView({ data }: { data: Analytics }) {
  if (!data.ai.requests) return <EmptyPanel title="No AI usage events in this range" detail="AI metrics appear when ai_usage_events contains tenant-scoped records inside the selected range." />;
  const byFeature = new Map<string, { requests: number; tokens: number; cost: number; latency: number }>();
  for (const row of data.ai.usageDetails) { const current = byFeature.get(row.feature) ?? { requests: 0, tokens: 0, cost: 0, latency: 0 }; current.requests += 1; current.tokens += row.totalTokens; current.cost += row.costEstimate; current.latency += row.latencyMs; byFeature.set(row.feature, current); }
  return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Metric icon={Zap} label="Requests" value={data.ai.requests.toLocaleString()} /><Metric icon={Coins} label="Input tokens" value={data.ai.inputTokens.toLocaleString()} /><Metric icon={Coins} label="Output tokens" value={data.ai.outputTokens.toLocaleString()} /><Metric icon={Coins} label="Total tokens" value={data.ai.totalTokens.toLocaleString()} /><Metric icon={Clock3} label="Avg latency" value={`${data.ai.averageLatencyMs} ms`} /></div><Card><CardHeader><CardTitle className="text-sm">Usage by feature / agent</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-sm"><thead className="bg-muted/20 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Feature</th><th className="px-3 py-3 text-right">Requests</th><th className="px-3 py-3 text-right">Tokens</th><th className="px-3 py-3 text-right">Estimated cost</th><th className="px-3 py-3 text-right">Avg latency</th></tr></thead><tbody>{[...byFeature.entries()].map(([feature, row]) => <tr key={feature} className="border-t"><td className="px-4 py-3 font-medium">{feature}</td><td className="px-3 py-3 text-right">{row.requests}</td><td className="px-3 py-3 text-right">{row.tokens.toLocaleString()}</td><td className="px-3 py-3 text-right">{row.cost.toFixed(6)}</td><td className="px-3 py-3 text-right">{Math.round(row.latency / row.requests)} ms</td></tr>)}</tbody></table></CardContent></Card></div>;
}

export function AgentsView({ data }: { data: Analytics }) { const rows = data.agents.filter((agent) => agent.actions > 0 || agent.changes > 0); if (!rows.length) return <EmptyPanel title="No agent activity in this range" detail="Agents are listed only when their catalogue entry has real change or AI usage evidence in the selected period." />; return <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[860px] text-sm"><thead className="bg-muted/20 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Agent</th><th className="px-3 py-3 text-left">Category</th><th className="px-3 py-3 text-right">Actions</th><th className="px-3 py-3 text-right">Changes</th><th className="px-3 py-3 text-right">Tokens</th><th className="px-3 py-3 text-right">Avg latency</th><th className="px-3 py-3 text-left">Last activity</th></tr></thead><tbody>{rows.map((agent) => <tr key={agent.name} className="border-t"><td className="px-4 py-3 font-medium">{agent.name}</td><td className="px-3 py-3"><Badge variant="outline">{agent.category}</Badge></td><td className="px-3 py-3 text-right">{agent.actions}</td><td className="px-3 py-3 text-right">{agent.changes}</td><td className="px-3 py-3 text-right">{agent.tokens.toLocaleString()}</td><td className="px-3 py-3 text-right">{agent.averageLatencyMs ? `${agent.averageLatencyMs} ms` : "—"}</td><td className="px-3 py-3 text-xs text-muted-foreground">{agent.lastActivity ? new Date(agent.lastActivity).toLocaleString() : "No activity"}</td></tr>)}</tbody></table></CardContent></Card>; }

export function GovernanceView({ data }: { data: Analytics }) { const stages = new Map<string, { count: number; critical: number; high: number }>(); for (const agent of data.agents) for (const row of agent.recentChanges) { const stage = String(row.stage ?? "Unknown"); const current = stages.get(stage) ?? { count: 0, critical: 0, high: 0 }; current.count += 1; current.critical += String(row.severity).toLowerCase() === "critical" ? 1 : 0; current.high += String(row.severity).toLowerCase() === "high" ? 1 : 0; stages.set(stage, current); } if (!stages.size) return <EmptyPanel title="No change records in this range" detail="Governance analytics are derived from tenant-scoped change_records rows." />; return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><MetricSmall label="Change records" value={data.platform.changeRecords} /><MetricSmall label="Pending review" value={data.platform.pendingChanges} /><MetricSmall label="Critical changes" value={data.severityCounts.critical ?? 0} /></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/20 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Stage</th><th className="px-3 py-3 text-right">Records</th><th className="px-3 py-3 text-right">Critical</th><th className="px-3 py-3 text-right">High</th><th className="px-3 py-3">Review</th></tr></thead><tbody>{[...stages.entries()].map(([stage, row]) => <tr key={stage} className="border-t"><td className="px-4 py-3 font-medium">{stage}</td><td className="px-3 py-3 text-right">{row.count}</td><td className="px-3 py-3 text-right">{row.critical}</td><td className="px-3 py-3 text-right">{row.high}</td><td className="px-3 py-3">{["Owner Review", "Team Approvals", "Ready to Execute"].includes(stage) ? <Link to="/approvals" className="inline-flex items-center gap-1 text-primary hover:underline">Approval Center<ArrowRight className="h-3.5 w-3.5" /></Link> : <span className="text-muted-foreground">—</span>}</td></tr>)}</tbody></table></CardContent></Card></div>; }

export function AdminActivityView({ data }: { data: Analytics }) { const actorRows = data.recentEvents.filter((row) => row.actor_email).slice(0, 100); if (!data.userActivity.additions && !data.userActivity.removals && !data.userActivity.updates && !actorRows.length) return <EmptyPanel title="No administrative activity in this range" detail="User additions, removals, updates and actor events are based on recorded audit telemetry." />; return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Additions" value={data.userActivity.additions} /><Metric icon={Users} label="Removals" value={data.userActivity.removals} /><Metric icon={Users} label="Updates" value={data.userActivity.updates} /><Metric icon={Activity} label="Unique actors" value={data.userActivity.uniqueActors} /></div><Card><CardHeader><CardTitle className="text-sm">Recent actor events</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead className="bg-muted/20 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Time</th><th className="px-3 py-3 text-left">Actor</th><th className="px-3 py-3 text-left">Action</th><th className="px-3 py-3 text-left">Entity</th></tr></thead><tbody>{actorRows.map((row, index) => <tr key={`${row.created_at}-${index}`} className="border-t"><td className="px-4 py-3 text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString()}</td><td className="px-3 py-3">{row.actor_email}</td><td className="px-3 py-3">{row.action}</td><td className="px-3 py-3 text-muted-foreground">{row.entity_type} · {row.entity_id}</td></tr>)}</tbody></table></CardContent></Card></div>; }

export function IntegrationsEvidenceView({ workspace, busy, onSync }: { workspace: any; busy: string | null; onSync: (provider: string, connectionId: string) => void }) { if (!workspace.providers.connectedProviders.length) return <EmptyPanel title="No connected providers with evidence" detail="Connect and successfully synchronize a provider to see integration evidence here." action={<Link to="/integrations"><Button size="sm">Open Integrations</Button></Link>} />; return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><MetricSmall label="Connected providers" value={workspace.providers.connectedProviders.length} /><MetricSmall label="Live entity records" value={workspace.providers.entities.length} /><MetricSmall label="Recent sync runs" value={workspace.providers.runs.length} /></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[820px] text-sm"><thead className="bg-muted/20 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Provider</th><th className="px-3 py-3 text-left">Status</th><th className="px-3 py-3 text-right">Records</th><th className="px-3 py-3 text-left">Last sync</th><th className="px-3 py-3">Action</th></tr></thead><tbody>{workspace.providers.connectedProviders.map((connection: any) => { const count = workspace.providers.entities.filter((entity: any) => entity.connection_id === connection.id).length; const latest = workspace.providers.runs.find((run: any) => run.connection_id === connection.id); return <tr key={connection.id} className="border-t"><td className="px-4 py-3 font-medium">{connection.display_name ?? connection.provider}</td><td className="px-3 py-3"><Badge variant="outline" className="border-success/30 text-success">Connected</Badge></td><td className="px-3 py-3 text-right">{count}</td><td className="px-3 py-3 text-xs text-muted-foreground">{connection.last_sync_at ? new Date(connection.last_sync_at).toLocaleString() : "Not synced"}{latest?.status === "failed" ? <span className="ml-2 text-destructive">Last run failed</span> : null}</td><td className="px-3 py-3"><Button size="sm" variant="outline" disabled={busy === connection.id || !["github", "jira", "slack"].includes(connection.provider)} onClick={() => onSync(connection.provider, connection.id)}><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Sync</Button></td></tr>; })}</tbody></table></CardContent></Card></div>; }
