import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, SearchCheck, ShieldAlert, Sparkles } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { PageHeader } from "@/components/layout/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyIntegrationsState } from "@/components/EmptyIntegrationsState";
import { getInvestigation, getInvestigations, type Investigation } from "@/lib/investigation.functions";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/_app/investigations")({ validateSearch: (search: Record<string, unknown>) => ({ key: typeof search.key === "string" ? search.key : undefined }), head: () => pageHead({ path: "/investigations", title: "Investigations — Aegis AI", description: "Evidence-backed investigations across live enterprise operations data." }), component: InvestigationsPage });

function InvestigationsPage() {
  const { key } = Route.useSearch();
  const list = useServerFn(getInvestigations); const load = useServerFn(getInvestigation);
  const [items, setItems] = useState<Awaited<ReturnType<typeof getInvestigations>> | null>(null); const [detail, setDetail] = useState<Investigation | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); const task = key ? load({ data: { key } }).then((result) => { if (active && !('unavailable' in result)) setDetail(result); }) : list().then((result) => { if (active) setItems(result); }); void task.finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [key, list, load]);
  if (loading) return <div className="py-16 text-center text-sm text-muted-foreground">Loading evidence-backed investigations…</div>;
  if (key && !detail) return <EmptyIntegrationsState title="Investigation unavailable" description="The finding is no longer present in the current real provider evidence, or the evidence is insufficient." />;
  if (detail) return <InvestigationDetail data={detail} />;
  if (!items?.connected) return <><PageHeader title="Investigations" description="Aegis investigations are built only from real provider, audit and change evidence." /><EmptyIntegrationsState title="No provider evidence available" description="Connect and successfully synchronize a provider before Aegis can investigate operational findings." /></>;
  return <div><PageHeader title="Investigations" description="Evidence-backed findings that can be traced from detection through governance." />
    {items.investigations.length ? <div className="grid gap-4 lg:grid-cols-2">{items.investigations.map((item) => <Link key={item.key} to="/investigations" search={{ key: item.key }} className="block"><Card className="h-full transition hover:border-primary/40"><CardHeader><div className="flex items-center justify-between gap-3"><Badge variant="outline">{item.severity}</Badge><span className="text-xs text-muted-foreground">{item.confidence} confidence</span></div><CardTitle className="mt-2 text-base">{item.title}</CardTitle><CardDescription>{item.category} · {item.correlatedChangeCount} related change record{item.correlatedChangeCount === 1 ? "" : "s"}</CardDescription></CardHeader><CardContent><p className="text-sm text-muted-foreground">{item.impact}</p><div className="mt-4 text-sm font-medium text-primary">Open investigation →</div></CardContent></Card></Link>)}</div> : <EmptyIntegrationsState title="No active investigations" description="Aegis has no evidence-backed finding to investigate right now. It will not invent one." />}
  </div>;
}

function InvestigationDetail({ data }: { data: Investigation }) { return <div><PageHeader title={data.title} description={`${data.category} investigation · ${data.provider ?? "Provider unavailable"}`} actions={<Button variant="outline" asChild><Link to="/investigations" search={{}}><ArrowLeft className="mr-1.5 h-4 w-4" /> All investigations</Link></Button>} />
  <div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline">Risk: {data.risk.tier}</Badge><Badge variant="outline">Confidence: {data.confidence}</Badge>{data.lastSyncAt && <Badge variant="outline">Last sync {new Date(data.lastSyncAt).toLocaleString()}</Badge>}</div>
  <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Finding</CardTitle></CardHeader><CardContent className="text-sm">{data.finding}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Business impact</CardTitle></CardHeader><CardContent className="text-sm">{data.businessImpact}</CardContent></Card></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Evidence</CardTitle><CardDescription>Only records used to support this finding.</CardDescription></CardHeader><CardContent className="space-y-3">{data.evidence.map((item, index) => <div key={`${item.source}-${index}`} className="rounded-lg border p-3"><div className="text-sm font-medium">{item.source}</div><div className="mt-1 text-sm text-muted-foreground">{item.observation}</div><div className="mt-2 text-[11px] text-muted-foreground">Observed {new Date(item.observedAt).toLocaleString()}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Confidence</CardTitle><CardDescription>Deterministic evidence completeness, not an invented model score.</CardDescription></CardHeader><CardContent><div className="flex items-center gap-2 text-sm"><Sparkles className="h-4 w-4 text-primary" /> {data.confidence}</div><p className="mt-2 text-sm text-muted-foreground">{data.confidenceRationale}</p></CardContent></Card></div>
  <Card className="mt-4"><CardHeader><CardTitle className="text-base">Correlated signals</CardTitle><CardDescription>Only explicit links to persisted change records are shown.</CardDescription></CardHeader><CardContent>{data.correlatedSignals.length ? <div className="space-y-2">{data.correlatedSignals.map((signal) => <Link key={signal.rowId} to="/approvals/$id" params={{ id: signal.rowId }} className="flex items-center justify-between rounded-lg border p-3 hover:bg-muted/30"><div><div className="text-sm font-medium">{signal.title}</div><div className="text-xs text-muted-foreground">{signal.changeId} · {signal.stage} · {signal.severity}</div></div><span className="text-xs text-primary">Open change →</span></Link>)}</div> : <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">No persisted cross-record correlation was found.</div>}</CardContent></Card>
  <div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Timeline</CardTitle></CardHeader><CardContent className="space-y-2">{data.timeline.length ? data.timeline.map((item, index) => <div key={`${item.ts}-${index}`} className="rounded-lg border p-3"><div className="flex items-center gap-2 text-sm"><ShieldAlert className="h-4 w-4 text-primary" /> {item.text}</div><div className="mt-1 text-xs text-muted-foreground">{item.actor} · {new Date(item.ts).toLocaleString()}</div></div>) : <div className="py-6 text-center text-sm text-muted-foreground">No related audit events found.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Recommended action</CardTitle><CardDescription>Recommendations remain subject to the existing approval and guardrail pipeline.</CardDescription></CardHeader><CardContent><div className="rounded-lg border p-4 text-sm">{data.recommendedAction}</div><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><SearchCheck className="h-4 w-4" /> No direct execution is available from this view.</div><Button className="mt-4" asChild><Link to="/approvals">Open Approval Center</Link></Button></CardContent></Card></div>
</div>; }
