import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Clock3, ExternalLink, MessageSquareWarning, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { useServerFn } from "@tanstack/react-start";
import { PageHeader, SeverityBadge, StatusPill } from "@/components/layout/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { listOperationalIssues, updateOperationalIssue } from "@/lib/operational-console.functions";

export const Route = createFileRoute("/platform/operational-console")({ component: OperationalConsolePage });
const sources = ["all", "sync", "agent_run", "integration_health", "guardrail_evaluation", "webhook_delivery", "command_center", "other"];
const severities = ["all", "critical", "high", "medium", "low"];
const statuses = ["all", "open", "acknowledged", "resolved"];
const sourceLabel = (source: string) => source.replaceAll("_", " ");
function OperationalConsolePage() {
  const load = useServerFn(listOperationalIssues); const update = useServerFn(updateOperationalIssue);
  const [issues, setIssues] = useState<any[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [source, setSource] = useState("all"); const [severity, setSeverity] = useState("all"); const [status, setStatus] = useState("all"); const [note, setNote] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [environmentMode, setEnvironmentMode] = useState<"live" | "demo">("live");
  const refresh = async () => { setLoading(true); try { const result = await load({ data: { source: source === "all" ? undefined : source, severity: severity === "all" ? undefined : severity, status: status === "all" ? undefined : status } }); if (!result.ok) throw new Error("Could not load operational issues."); setIssues(result.issues); setEnvironmentMode(result.environmentMode); if (!selectedId && result.issues[0]) setSelectedId(result.issues[0].id); else if (selectedId && !result.issues.some((i: any) => i.id === selectedId)) setSelectedId(result.issues[0]?.id ?? null); } catch (error) { toast.error("Could not load Operational Console", { description: error instanceof Error ? error.message : "Try again." }); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [source, severity, status]);
  const selected = useMemo(() => issues.find((issue) => issue.id === selectedId) ?? issues[0] ?? null, [issues, selectedId]);
  const changeStatus = async (next: "acknowledged" | "resolved") => { if (!selected) return; if (next === "resolved" && !note.trim()) { toast.error("Resolution note required"); return; } setSaving(true); try { const result = await update({ data: { issueId: selected.id, status: next, note: note.trim() || undefined } }); if (!result.ok) throw new Error("Could not update issue."); setNote(""); toast.success(next === "resolved" ? "Issue resolved" : "Issue acknowledged"); await refresh(); } catch (error) { toast.error("Could not update issue", { description: error instanceof Error ? error.message : "Try again." }); } finally { setSaving(false); } };
  return <div className="space-y-5">
    <PageHeader title="Operational Console" description="A live queue of what is currently broken or needs operational attention — separate from Audit Viewer history and Vulnerabilities." actions={<Button variant="outline" size="sm" onClick={() => void refresh()} disabled={loading}><RefreshCw className={`mr-1.5 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button>} />
    <div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-success" />Persisted operational data</Badge><Badge variant="outline">{issues.length} issue{issues.length === 1 ? "" : "s"}</Badge><Badge variant="outline" className="gap-1"><AlertCircle className="h-3 w-3" />{issues.filter((i) => ["critical", "high"].includes(i.severity) && i.status !== "resolved").length} high/critical active</Badge></div>
    <div className="grid gap-4 lg:grid-cols-[1.15fr_1fr]">
      <Card><CardHeader><CardTitle className="text-base">Attention queue</CardTitle><CardDescription>Repeated failures are coalesced; occurrence count shows recurrence rather than duplicate records.</CardDescription><div className="grid gap-2 pt-2 sm:grid-cols-3"><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{sources.map((value) => <SelectItem key={value} value={value}>{value === "all" ? "All sources" : sourceLabel(value)}</SelectItem>)}</SelectContent></Select><Select value={severity} onValueChange={setSeverity}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{severities.map((value) => <SelectItem key={value} value={value}>{value === "all" ? "All severities" : value}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{statuses.map((value) => <SelectItem key={value} value={value}>{value === "all" ? "All statuses" : value}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent className="space-y-2">{loading ? <div className="py-10 text-center text-sm text-muted-foreground">Loading…</div> : issues.length === 0 ? <div className="rounded-lg border border-dashed p-10 text-center"><CheckCircle2 className="mx-auto h-6 w-6 text-success" /><p className="mt-2 text-sm font-medium">No matching operational issues</p><p className="text-xs text-muted-foreground">This means the selected operational queue currently has nothing persisted for attention.</p></div> : issues.map((issue) => <button type="button" key={issue.id} onClick={() => setSelectedId(issue.id)} className={`w-full rounded-lg border p-3 text-left transition hover:bg-muted/30 ${selected?.id === issue.id ? "border-primary bg-primary/[0.04]" : ""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold">{issue.title}</div><div className="mt-1 flex flex-wrap items-center gap-1.5"><StatusPill tone={issue.status === "resolved" ? "success" : issue.status === "acknowledged" ? "warning" : "danger"}>{issue.status}</StatusPill><SeverityBadge severity={issue.severity} /><Badge variant="outline" className="capitalize">{sourceLabel(issue.source)}</Badge></div></div><span className="shrink-0 text-[11px] text-muted-foreground">×{issue.occurrence_count}</span></div><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-muted-foreground"><span>First {new Date(issue.first_seen_at).toLocaleString()}</span><span>Last {new Date(issue.last_seen_at).toLocaleString()}</span></div></button>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Issue detail</CardTitle><CardDescription>Current operational state, recurrence and resolution history.</CardDescription></CardHeader><CardContent>{!selected ? <div className="py-10 text-center text-sm text-muted-foreground">Select an issue to inspect it.</div> : <div className="space-y-4"><div><h2 className="text-lg font-semibold">{selected.title}</h2><div className="mt-2 flex flex-wrap gap-2"><SeverityBadge severity={selected.severity} /><StatusPill tone={selected.status === "resolved" ? "success" : selected.status === "acknowledged" ? "warning" : "danger"}>{selected.status}</StatusPill><Badge variant="outline">{sourceLabel(selected.source)}</Badge><Badge variant="outline">{selected.occurrence_count} occurrences</Badge></div></div><div className="rounded-lg border bg-muted/20 p-3"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><MessageSquareWarning className="h-4 w-4 text-primary" />What happened</div><p className="whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{selected.detail}</p></div><div className="grid gap-2 text-xs sm:grid-cols-2"><div className="rounded-lg border p-3"><Clock3 className="mb-1 h-4 w-4 text-muted-foreground" /><div className="text-muted-foreground">First seen</div><div className="font-medium">{new Date(selected.first_seen_at).toLocaleString()}</div></div><div className="rounded-lg border p-3"><Clock3 className="mb-1 h-4 w-4 text-muted-foreground" /><div className="text-muted-foreground">Last seen</div><div className="font-medium">{new Date(selected.last_seen_at).toLocaleString()}</div></div></div>{selected.related_id && <div className="flex items-center justify-between rounded-lg border p-3 text-xs"><div><div className="text-muted-foreground">Related record</div><div className="font-mono">{selected.related_id}</div></div><ExternalLink className="h-4 w-4 text-muted-foreground" /></div>}{selected.status !== "resolved" && environmentMode === "live" && <div className="space-y-2 border-t pt-4"><Textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Resolution note (required to resolve)…" maxLength={1000} /><div className="flex gap-2"><Button variant="outline" onClick={() => void changeStatus("acknowledged")} disabled={saving || selected.status === "acknowledged"}>Acknowledge</Button><Button onClick={() => void changeStatus("resolved")} disabled={saving || !note.trim()}>Resolve issue</Button></div></div>}{environmentMode === "demo" && <div className="rounded-lg border border-warning/30 bg-warning/5 p-3 text-xs text-muted-foreground">This workspace is in Demo mode; operational issues shown here are still read from persisted operational data and are read-only.</div>}</div>}</CardContent></Card>
    </div>
  </div>;
}
