/**
 * DEMO DATA ONLY.
 *
 * Every event produced here carries `seeded: true` so demo records are always
 * distinguishable from real connector/backend events in code and in the UI.
 * Real emitters must never import this module.
 */
import type { AuditActor, AuditEvent } from "./types";

const ACTORS: Record<string, AuditActor> = {
  amelia: {
    id: "usr_amelia",
    name: "Amelia Ward",
    email: "amelia.ward@contoso.com",
    role: "Admin",
    type: "human",
  },
  daniel: {
    id: "usr_daniel",
    name: "Daniel Osei",
    email: "daniel.osei@contoso.com",
    role: "Manager",
    type: "human",
  },
  priya: {
    id: "usr_priya",
    name: "Priya Raman",
    email: "priya.raman@contoso.com",
    role: "Analyst",
    type: "human",
  },
  jonas: {
    id: "usr_jonas",
    name: "Jonas Meyer",
    email: "jonas.meyer@contoso.com",
    role: "Viewer",
    type: "human",
  },
  licenseAgent: {
    id: "agent-license",
    name: "License Optimization Agent",
    email: "agent-license@aegis.internal",
    role: "System",
    type: "agent",
  },
  platform: {
    id: "system",
    name: "Aegis Platform",
    email: "platform@aegis.internal",
    role: "System",
    type: "system",
  },
};

const WEB = { channel: "web" as const, ip: "203.0.113.24", device: "Chrome 141 · macOS", location: "Dublin, IE" };
const WEB2 = { channel: "web" as const, ip: "198.51.100.77", device: "Edge 140 · Windows 11", location: "Austin, US" };
const AGENT = { channel: "agent" as const, ip: null, device: "Aegis agent runtime", location: "eu-west-1" };
const SCHED = { channel: "scheduler" as const, ip: null, device: "Aegis scheduler", location: "eu-west-1" };
const API = { channel: "api" as const, ip: "192.0.2.51", device: "aegis-cli/1.4", location: "Frankfurt, DE" };

function at(hoursAgo: number): string {
  return new Date(Date.now() - hoursAgo * 3_600_000).toISOString();
}

let seq = 0;
function ev(e: Omit<AuditEvent, "id" | "seeded">): AuditEvent {
  seq += 1;
  return { ...e, id: `evt_${String(seq).padStart(5, "0")}`, seeded: true };
}

/** Builds the full demo audit stream. Ordered newest-first by the query layer. */
export function buildSeedAuditEvents(): AuditEvent[] {
  seq = 0;
  return [
    // ---- Correlation: Genesys reconnect -> agent binding -> change -> execution
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(30),
      actor: ACTORS.platform,
      action: "integration.auth_failed",
      resourceType: "integration",
      resourceName: "Genesys Cloud",
      targetId: "int_genesys_01",
      integration: "Genesys Cloud",
      changes: [
        { field: "health_status", oldValue: "healthy", newValue: "degraded" },
        { field: "client_secret", oldValue: "gc_live_9f3ab7de4471", newValue: "gc_live_5521ccaa9910" },
      ],
      reason: "Refresh token rejected by provider (invalid_grant).",
      result: "failure",
      risk: "high",
      source: SCHED,
      metadata: { error_code: "invalid_grant", attempt: 3, access_token: "eyJhbGciOiJI.sensitive.value" },
      approvalStatus: "not_required",
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(28),
      actor: ACTORS.amelia,
      action: "integration.reconnected",
      resourceType: "integration",
      resourceName: "Genesys Cloud",
      targetId: "int_genesys_01",
      integration: "Genesys Cloud",
      changes: [
        { field: "health_status", oldValue: "degraded", newValue: "healthy" },
        { field: "scopes", oldValue: "users:readonly", newValue: "users:readonly, license:readonly, analytics:readonly" },
      ],
      reason: "Re-authorized read-only OAuth client after credential rotation.",
      result: "success",
      risk: "medium",
      source: WEB,
      metadata: { region: "eu-west-1", flow: "authorization_code" },
      approvalStatus: "not_required",
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(27),
      actor: ACTORS.amelia,
      action: "agent.config_changed",
      resourceType: "agent",
      resourceName: "License Optimization Agent",
      targetId: "agent-license",
      integration: "Genesys Cloud",
      agent: "License Optimization Agent",
      changes: [
        { field: "binding.queue_inventory", oldValue: "disabled", newValue: "enabled" },
        { field: "policy.inactivityThresholdDays", oldValue: "120", newValue: "90" },
      ],
      reason: "Enable queue membership exclusions for unused-license detection.",
      result: "success",
      risk: "medium",
      source: WEB,
      approvalStatus: "not_required",
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(26),
      actor: ACTORS.licenseAgent,
      action: "recommendation.created",
      resourceType: "recommendation",
      resourceName: "Reclaim 142 unused Genesys licenses",
      targetId: "rec_88412",
      integration: "Genesys Cloud",
      agent: "License Optimization Agent",
      changes: [],
      reason: "142 licenses unused for more than 90 days; estimated $18,400/mo saving.",
      result: "success",
      risk: "medium",
      source: AGENT,
      metadata: { candidates: 142, confidence: 0.93, excluded_active_queue_members: 37 },
      approvalStatus: "not_required",
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(25),
      actor: ACTORS.licenseAgent,
      action: "change.created",
      resourceType: "change_record",
      resourceName: "CHG-2041 · Reclaim unused Genesys licenses",
      targetId: "CHG-2041",
      integration: "Genesys Cloud",
      agent: "License Optimization Agent",
      changes: [{ field: "stage", oldValue: null, newValue: "pending_approval" }],
      approvalId: "CHG-2041",
      approvalStatus: "pending",
      result: "pending",
      risk: "medium",
      source: AGENT,
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(24),
      actor: ACTORS.daniel,
      action: "change.approved",
      resourceType: "change_record",
      resourceName: "CHG-2041 · Reclaim unused Genesys licenses",
      targetId: "CHG-2041",
      integration: "Genesys Cloud",
      agent: "License Optimization Agent",
      changes: [{ field: "stage", oldValue: "pending_approval", newValue: "approved" }],
      reason: "Savings validated against Q3 licence forecast.",
      approvalId: "CHG-2041",
      approvalStatus: "approved",
      result: "success",
      risk: "medium",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_genesys_recon",
      timestamp: at(23),
      actor: ACTORS.platform,
      action: "change.executed",
      resourceType: "change_record",
      resourceName: "CHG-2041 · Reclaim unused Genesys licenses",
      targetId: "CHG-2041",
      integration: "Genesys Cloud",
      agent: "License Optimization Agent",
      changes: [
        { field: "stage", oldValue: "approved", newValue: "completed" },
        { field: "licenses_reclaimed", oldValue: "0", newValue: "142" },
      ],
      approvalId: "CHG-2041",
      approvalStatus: "approved",
      result: "success",
      risk: "medium",
      source: SCHED,
      metadata: { duration_ms: 42_318, batches: 8 },
    }),

    // ---- Correlation: failed execution
    ev({
      correlationId: "cor_azure_scale",
      timestamp: at(9),
      actor: ACTORS.daniel,
      action: "change.approved",
      resourceType: "change_record",
      resourceName: "CHG-2078 · Resize Azure SQL pool",
      targetId: "CHG-2078",
      integration: "Azure",
      changes: [{ field: "stage", oldValue: "pending_approval", newValue: "approved" }],
      approvalId: "CHG-2078",
      approvalStatus: "approved",
      result: "success",
      risk: "high",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_azure_scale",
      timestamp: at(8.5),
      actor: ACTORS.platform,
      action: "change.execution_failed",
      resourceType: "change_record",
      resourceName: "CHG-2078 · Resize Azure SQL pool",
      targetId: "CHG-2078",
      integration: "Azure",
      changes: [{ field: "stage", oldValue: "executing", newValue: "failed" }],
      reason: "Provider returned 409 Conflict: pool busy with an in-flight operation.",
      approvalId: "CHG-2078",
      approvalStatus: "approved",
      result: "failure",
      risk: "critical",
      source: SCHED,
      metadata: { http_status: 409, rollback: "completed" },
    }),

    // ---- Identity + licensing
    ev({
      correlationId: "cor_onboard_kim",
      timestamp: at(6),
      actor: ACTORS.amelia,
      action: "user.added",
      resourceType: "user",
      resourceName: "Kim Nguyen",
      targetId: "usr_kim",
      changes: [
        { field: "email", oldValue: null, newValue: "kim.nguyen@contoso.com" },
        { field: "department", oldValue: null, newValue: "Customer Operations" },
      ],
      result: "success",
      risk: "low",
      source: WEB,
      approvalStatus: "not_required",
    }),
    ev({
      correlationId: "cor_onboard_kim",
      timestamp: at(5.9),
      actor: ACTORS.amelia,
      action: "user.role_changed",
      resourceType: "role",
      resourceName: "Kim Nguyen",
      targetId: "usr_kim",
      changes: [{ field: "role", oldValue: "Viewer", newValue: "Analyst" }],
      reason: "Joining the reporting rota.",
      result: "success",
      risk: "high",
      source: WEB,
    }),
    ev({
      correlationId: "cor_onboard_kim",
      timestamp: at(5.8),
      actor: ACTORS.platform,
      action: "license.assigned",
      resourceType: "license",
      resourceName: "Genesys Cloud CX 3",
      targetId: "usr_kim",
      integration: "Genesys Cloud",
      changes: [{ field: "license", oldValue: null, newValue: "Genesys Cloud CX 3" }],
      result: "success",
      risk: "low",
      source: SCHED,
    }),
    ev({
      correlationId: "cor_offboard_lee",
      timestamp: at(4),
      actor: ACTORS.amelia,
      action: "user.deactivated",
      resourceType: "user",
      resourceName: "Marcus Lee",
      targetId: "usr_marcus",
      changes: [{ field: "state", oldValue: "active", newValue: "inactive" }],
      reason: "Offboarding ticket HR-8842.",
      result: "success",
      risk: "medium",
      source: WEB,
    }),
    ev({
      correlationId: "cor_offboard_lee",
      timestamp: at(3.9),
      actor: ACTORS.platform,
      action: "license.unassigned",
      resourceType: "license",
      resourceName: "Genesys Cloud CX 2",
      targetId: "usr_marcus",
      integration: "Genesys Cloud",
      changes: [{ field: "license", oldValue: "Genesys Cloud CX 2", newValue: null }],
      result: "success",
      risk: "low",
      source: SCHED,
    }),
    ev({
      correlationId: "cor_offboard_lee",
      timestamp: at(3.8),
      actor: ACTORS.platform,
      action: "user.removed",
      resourceType: "user",
      resourceName: "Marcus Lee",
      targetId: "usr_marcus",
      changes: [{ field: "directory_entry", oldValue: "present", newValue: "removed" }],
      result: "success",
      risk: "medium",
      source: SCHED,
    }),
    ev({
      correlationId: "cor_licence_tier",
      timestamp: at(20),
      actor: ACTORS.daniel,
      action: "license.changed",
      resourceType: "license",
      resourceName: "Genesys Cloud CX 1 → CX 2",
      targetId: "usr_priya",
      integration: "Genesys Cloud",
      changes: [{ field: "license", oldValue: "Genesys Cloud CX 1", newValue: "Genesys Cloud CX 2" }],
      reason: "Workforce engagement features required.",
      result: "success",
      risk: "low",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_user_update",
      timestamp: at(14),
      actor: ACTORS.daniel,
      action: "user.updated",
      resourceType: "user",
      resourceName: "Priya Raman",
      targetId: "usr_priya",
      changes: [
        { field: "title", oldValue: "Operations Analyst", newValue: "Senior Operations Analyst" },
      ],
      result: "success",
      risk: "low",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_perm_change",
      timestamp: at(13),
      actor: ACTORS.amelia,
      action: "user.permission_changed",
      resourceType: "role",
      resourceName: "Analyst role",
      targetId: "role_analyst",
      changes: [{ field: "permissions", oldValue: "approvals.reject", newValue: "approvals.reject, audit.export" }],
      reason: "Analysts now own weekly audit exports.",
      result: "success",
      risk: "high",
      source: WEB,
    }),

    // ---- Integrations
    ev({
      correlationId: "cor_m365_connect",
      timestamp: at(48),
      actor: ACTORS.amelia,
      action: "integration.connected",
      resourceType: "integration",
      resourceName: "Microsoft 365 / Entra ID",
      targetId: "int_m365_01",
      integration: "Microsoft 365",
      changes: [
        { field: "status", oldValue: "not_connected", newValue: "connected" },
        { field: "api_key", oldValue: null, newValue: "m365_key_5f7c11ab" },
      ],
      result: "success",
      risk: "medium",
      source: WEB,
      metadata: { tenant_domain: "contoso.onmicrosoft.com", scopes: "User.Read.All, Directory.Read.All" },
    }),
    ev({
      correlationId: "cor_sn_disconnect",
      timestamp: at(40),
      actor: ACTORS.amelia,
      action: "integration.disconnected",
      resourceType: "integration",
      resourceName: "ServiceNow",
      targetId: "int_snow_01",
      integration: "ServiceNow",
      changes: [{ field: "status", oldValue: "connected", newValue: "not_connected" }],
      reason: "Migrating to the shared ITSM instance.",
      result: "success",
      risk: "medium",
      source: WEB,
    }),

    // ---- Agents
    ev({
      correlationId: "cor_agent_sec",
      timestamp: at(19),
      actor: ACTORS.amelia,
      action: "agent.connected",
      resourceType: "agent",
      resourceName: "Security & Compliance Agent",
      targetId: "agent-security",
      agent: "Security & Compliance Agent",
      changes: [{ field: "state", oldValue: "unbound", newValue: "connected" }],
      result: "success",
      risk: "medium",
      source: WEB,
    }),
    ev({
      correlationId: "cor_agent_sec",
      timestamp: at(18.5),
      actor: ACTORS.amelia,
      action: "agent.enabled",
      resourceType: "agent",
      resourceName: "Security & Compliance Agent",
      targetId: "agent-security",
      agent: "Security & Compliance Agent",
      changes: [{ field: "enabled", oldValue: "false", newValue: "true" }],
      result: "success",
      risk: "low",
      source: WEB,
    }),
    ev({
      correlationId: "cor_agent_cost",
      timestamp: at(16),
      actor: ACTORS.daniel,
      action: "agent.disabled",
      resourceType: "agent",
      resourceName: "Cost Optimization Agent",
      targetId: "agent-cost",
      agent: "Cost Optimization Agent",
      changes: [{ field: "enabled", oldValue: "true", newValue: "false" }],
      reason: "Paused during month-end close.",
      result: "success",
      risk: "medium",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_agent_cost",
      timestamp: at(15.5),
      actor: ACTORS.daniel,
      action: "agent.disconnected",
      resourceType: "agent",
      resourceName: "Cost Optimization Agent",
      targetId: "agent-cost",
      agent: "Cost Optimization Agent",
      changes: [{ field: "binding.cost_inventory", oldValue: "enabled", newValue: "removed" }],
      result: "warning",
      risk: "medium",
      source: WEB2,
      metadata: { open_recommendations: 4 },
    }),

    // ---- Change rejection + policy
    ev({
      correlationId: "cor_chg_reject",
      timestamp: at(11),
      actor: ACTORS.priya,
      action: "change.rejected",
      resourceType: "change_record",
      resourceName: "CHG-2065 · Bulk deactivate stale AWS IAM keys",
      targetId: "CHG-2065",
      integration: "AWS",
      changes: [{ field: "stage", oldValue: "pending_approval", newValue: "rejected" }],
      reason: "Two keys belong to an active batch pipeline.",
      approvalId: "CHG-2065",
      approvalStatus: "rejected",
      result: "success",
      risk: "medium",
      source: WEB2,
    }),
    ev({
      correlationId: "cor_policy",
      timestamp: at(10),
      actor: ACTORS.amelia,
      action: "approval_policy.changed",
      resourceType: "approval_policy",
      resourceName: "High-risk change policy",
      targetId: "pol_high_risk",
      changes: [
        { field: "required_approvers", oldValue: "1", newValue: "2" },
        { field: "scope", oldValue: "critical", newValue: "critical, high" },
      ],
      reason: "Post-incident review action item.",
      result: "success",
      risk: "high",
      source: WEB,
    }),
    ev({
      correlationId: "cor_guardrail",
      timestamp: at(7),
      actor: ACTORS.amelia,
      action: "security.guardrail_changed",
      resourceType: "security",
      resourceName: "Guardrail · Block bulk license removal > 200",
      targetId: "gr_bulk_license",
      changes: [
        { field: "enforcement_mode", oldValue: "monitor", newValue: "enforce" },
        { field: "severity", oldValue: "medium", newValue: "high" },
      ],
      result: "success",
      risk: "high",
      source: WEB,
    }),
    ev({
      correlationId: "cor_secconf",
      timestamp: at(2.4),
      actor: ACTORS.amelia,
      action: "security.config_changed",
      resourceType: "configuration",
      resourceName: "Session policy",
      targetId: "cfg_session",
      changes: [
        { field: "session_timeout_minutes", oldValue: "480", newValue: "60" },
        { field: "mfa_required", oldValue: "false", newValue: "true" },
      ],
      result: "success",
      risk: "critical",
      source: WEB,
    }),

    // ---- Reporting
    ev({
      correlationId: "cor_report_q3",
      timestamp: at(2),
      actor: ACTORS.daniel,
      action: "report.generated",
      resourceType: "report",
      resourceName: "Executive operations summary · Q3",
      targetId: "rep_9931",
      changes: [],
      result: "success",
      risk: "info",
      source: WEB2,
      metadata: { format: "pdf", sections: "incidents, savings, health" },
    }),
    ev({
      correlationId: "cor_report_q3",
      timestamp: at(1.9),
      actor: ACTORS.daniel,
      action: "report.exported",
      resourceType: "report",
      resourceName: "Executive operations summary · Q3",
      targetId: "rep_9931",
      changes: [],
      result: "success",
      risk: "low",
      source: WEB2,
      metadata: { format: "csv", signed_url_ttl_seconds: 900, access_token: "sbp_signed_abc123" },
    }),

    // ---- Auth + session
    ev({
      correlationId: "cor_login_amelia",
      timestamp: at(1.2),
      actor: ACTORS.amelia,
      action: "auth.login",
      resourceType: "session",
      resourceName: "amelia.ward@contoso.com",
      targetId: "sess_71ab",
      changes: [],
      result: "success",
      risk: "info",
      source: WEB,
      metadata: { provider: "google", mfa: true, session_id: "sess_71ab_secret" },
    }),
    ev({
      correlationId: "cor_login_amelia",
      timestamp: at(0.9),
      actor: ACTORS.amelia,
      action: "auth.mfa_challenge",
      resourceType: "session",
      resourceName: "amelia.ward@contoso.com",
      targetId: "sess_71ab",
      changes: [],
      result: "success",
      risk: "info",
      source: WEB,
    }),
    ev({
      correlationId: "cor_login_fail",
      timestamp: at(0.6),
      actor: { ...ACTORS.jonas, role: "Viewer" },
      action: "auth.login_failed",
      resourceType: "session",
      resourceName: "jonas.meyer@contoso.com",
      targetId: null,
      changes: [],
      reason: "Invalid password · 4th consecutive attempt.",
      result: "failure",
      risk: "high",
      source: { ...API, device: "unknown client" },
      metadata: { attempts: 4, lockout: true },
    }),
    ev({
      correlationId: "cor_logout_priya",
      timestamp: at(0.3),
      actor: ACTORS.priya,
      action: "auth.logout",
      resourceType: "session",
      resourceName: "priya.raman@contoso.com",
      targetId: "sess_5510",
      changes: [],
      result: "success",
      risk: "info",
      source: WEB2,
    }),
  ];
}

export const SEED_ACTORS = ACTORS;
