import crypto from "node:crypto";
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import type { ExternalTicket } from "@/lib/change-data";
import { buildIdempotencyKey } from "@/lib/idempotency";

type TicketSystem = "Jira" | "ServiceNow";
interface StoredCredentials { accessToken?: string; refreshToken?: string; clientId?: string; clientSecret?: string; baseUrl?: string; apiToken?: string; tenant?: string; }
function decryptCredentials(value: string): StoredCredentials { const keyHex = process.env.AEGIS_CREDENTIAL_ENCRYPTION_KEY; if (!keyHex || !/^[0-9a-fA-F]{64}$/.test(keyHex)) throw new Error("AEGIS_CREDENTIAL_ENCRYPTION_KEY is not configured on the server."); const [ivText, tagText, ciphertextText] = value.split("."); if (!ivText || !tagText || !ciphertextText) throw new Error("Stored provider credentials are invalid."); const decipher = crypto.createDecipheriv("aes-256-gcm", Buffer.from(keyHex, "hex"), Buffer.from(ivText, "base64url")); decipher.setAuthTag(Buffer.from(tagText, "base64url")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(ciphertextText, "base64url")), decipher.final()]).toString("utf8")) as StoredCredentials; }
async function requestJson(url: string, init: RequestInit = {}) { const response = await fetch(url, init); const text = await response.text(); let body: any = {}; try { body = text ? JSON.parse(text) : {}; } catch { body = { raw: text }; } if (!response.ok) throw new Error(`Provider request failed (${response.status}).`); return body; }

export const createExternalTicketServer = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { changeRecordId: string; system: TicketSystem }) => ({ changeRecordId: String(input.changeRecordId ?? "").trim(), system: input.system })).handler(async ({ data, context }) => {
  if (!data.changeRecordId) throw new Error("Change record ID is required.");
  if (data.system !== "Jira" && data.system !== "ServiceNow") throw new Error("Unsupported ticket system.");
  const { data: roleRows, error: roleError } = await context.supabase.from("user_roles").select("tenant_id,role").eq("user_id", context.userId); if (roleError) throw roleError;
  const role = roleRows?.find((row) => row.role === "admin" || row.role === "manager"); if (!role?.tenant_id) throw new Error("Admin/manager access is required to create external tickets.");
  const tenantId = role.tenant_id; const provider = data.system === "Jira" ? "jira" : "servicenow";
  const { data: record, error: recordError } = await context.supabase.from("change_records").select("id,change_id,title,ai_reasoning,severity,tenant_id").eq("id", data.changeRecordId).eq("tenant_id", tenantId).maybeSingle(); if (recordError) throw recordError; if (!record) throw new Error("Change record not found in your workspace.");
  const { data: connection, error: connectionError } = await context.supabase.from("provider_connections").select("encrypted_credentials,status").eq("tenant_id", tenantId).eq("provider", provider).maybeSingle(); if (connectionError) throw connectionError; if (!connection || connection.status !== "connected" || !connection.encrypted_credentials) throw new Error(`${data.system} is not connected for this workspace.`);

  const { data: routing, error: routingError } = await (context.supabase as any).from("itsm_routing_config").select("integration_id,provider,target_config,issue_type,default_priority_mapping,is_default").eq("tenant_id", tenantId).eq("provider", provider).eq("is_default", true).maybeSingle();
  if (routingError) throw routingError;
  if (!routing) throw new Error(`Configure ITSM routing for this ${data.system} integration before creating tickets.`);
  const target = (routing.target_config ?? {}) as Record<string,string>;
  if (provider === "jira" && !target.projectKey) throw new Error("ITSM routing is incomplete: configure a Jira project.");
  if (provider === "servicenow" && !target.assignmentGroup) throw new Error("ITSM routing is incomplete: configure a ServiceNow assignment group.");

  const credentials = decryptCredentials(connection.encrypted_credentials);
  const accessToken = credentials.accessToken; if (!accessToken) throw new Error(`${data.system} is connected without an access token.`);
  let ticket: ExternalTicket;
  if (provider === "jira") {
    const sites = await requestJson("https://api.atlassian.com/oauth/token/accessible-resources", { headers: { authorization: `Bearer ${accessToken}` } }); const site = Array.isArray(sites) ? sites.find((s: any) => s.id) : null; const cloudId = String(site?.id ?? ""); const siteUrl = credentials.baseUrl?.replace(/\/$/, "") || String(site?.url ?? "").replace(/\/$/, ""); if (!cloudId) throw new Error("Jira returned no accessible site for this connection.");
    const created = await requestJson(`https://api.atlassian.com/ex/jira/${encodeURIComponent(cloudId)}/rest/api/3/issue`, { method: "POST", headers: { authorization: `Bearer ${accessToken}`, accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ fields: { project: { key: target.projectKey }, summary: `[Cenops] ${record.title}`, issuetype: { name: routing.issue_type || "Task" }, priority: routing.default_priority_mapping?.[record.severity] ? { name: routing.default_priority_mapping[record.severity] } : undefined, description: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text: `Cenops change ${record.change_id} (${record.severity}).` }] }, { type: "paragraph", content: [{ type: "text", text: (record.ai_reasoning ?? "").slice(0, 4000) }] }] } } } }); const key = String(created.key ?? ""); if (!key) throw new Error("Jira created the issue but returned no issue key."); ticket = { system: "Jira", id: key, url: siteUrl ? `${siteUrl}/browse/${encodeURIComponent(key)}` : `https://api.atlassian.com/ex/jira/${encodeURIComponent(cloudId)}/browse/${encodeURIComponent(key)}` };
  } else {
    const baseUrl = credentials.baseUrl?.replace(/\/$/, ""); if (!baseUrl) throw new Error("ServiceNow connection is missing its instance URL."); const created = await requestJson(`${baseUrl}/api/now/table/change_request`, { method: "POST", headers: { authorization: `Bearer ${accessToken}`, accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ short_description: `[Cenops] ${record.title}`, assignment_group: target.assignmentGroup, description: `Cenops change ${record.change_id}\nSeverity: ${record.severity}\n\n${record.ai_reasoning ?? ""}`.slice(0, 8000) }) }); const result = created.result ?? {}; const sysId = String(result.sys_id ?? ""); const number = String(result.number ?? ""); if (!sysId && !number) throw new Error("ServiceNow created the change but returned no change number or sys_id."); ticket = { system: "ServiceNow", id: number || sysId, url: `${baseUrl}/nav_to.do?uri=change_request.do?sys_id=${encodeURIComponent(sysId)}` };
  }
  const idempotencyKey = buildIdempotencyKey("external-ticket", { changeRecordId: record.id, system: data.system });
  const db = context.supabase as any; const existing = await db.from("external_ticket_actions").select("id,status,result").eq("tenant_id", tenantId).eq("idempotency_key", idempotencyKey).maybeSingle(); if (existing.data?.status === "succeeded" && existing.data.result) return existing.data.result;
  await db.from("external_ticket_actions").upsert({ tenant_id: tenantId, change_record_id: record.id, system: data.system, idempotency_key: idempotencyKey, status: "succeeded", result: ticket, error_message: null }, { onConflict: "tenant_id,idempotency_key" });
  const existingRecord = await context.supabase.from("change_records").select("external_tickets,timeline").eq("id", record.id).eq("tenant_id", tenantId).single(); if (existingRecord.error) throw existingRecord.error; const externalTickets = Array.isArray(existingRecord.data.external_tickets) ? existingRecord.data.external_tickets : []; const timeline = Array.isArray(existingRecord.data.timeline) ? existingRecord.data.timeline : []; externalTickets.push(ticket); timeline.unshift({ ts: new Date().toISOString(), actor: context.userId, kind: "system", text: `${data.system} ticket ${ticket.id} created and linked.` }); const { error: updateError } = await context.supabase.from("change_records").update({ external_tickets: externalTickets, timeline }).eq("id", record.id).eq("tenant_id", tenantId); if (updateError) throw updateError;
  return ticket;
});
