import crypto from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveTenantContext } from "@/lib/tenant-context.server";
const API = "https://api.github.com"; const API_VERSION = "2022-11-28";
export type GitHubEntityScope = "all" | "repositories" | "workflows" | "security"; export type GitHubSyncStatus = "running" | "success" | "failed" | "never";
export interface GitHubSyncStatusResult { connectionId: string; status: GitHubSyncStatus; lastAttemptedAt: string | null; lastSuccessfulAt: string | null; repositoriesCount: number; workflowRunsCount: number; securityAlertsCount: number; errorMessage: string | null; healthStatus: "healthy" | "unhealthy" | "unknown"; }
export interface GitHubSyncResult extends GitHubSyncStatusResult { staleCount: number; recordsUpserted: number; }
interface GitHubCredentials { accessToken?: string; } interface GitHubRepository { id: number; full_name: string; name: string; html_url: string; private: boolean; archived: boolean; default_branch: string; pushed_at: string | null; updated_at: string; } interface GitHubWorkflowRun { id: number; name: string | null; status: string; conclusion: string | null; html_url: string; created_at: string; updated_at: string; run_started_at: string | null; } interface GitHubCodeAlert { number: number; state: string; rule?: { description?: string; severity?: string; security_severity_level?: string | null }; html_url?: string; created_at?: string; updated_at?: string; } interface GitHubDependabotAlert { number: number; state: string; dependency?: { package?: { name?: string; ecosystem?: string } }; security_advisory?: { ghsa_id?: string; summary?: string; severity?: string }; html_url?: string; created_at?: string; updated_at?: string; }
function decryptCredentials(value: string): GitHubCredentials { const keyHex = process.env.AEGIS_CREDENTIAL_ENCRYPTION_KEY; if (!keyHex || !/^[0-9a-fA-F]{64}$/.test(keyHex)) throw new Error("Credential encryption is not configured on the server."); const [iv, tag, ciphertext] = value.split("."); if (!iv || !tag || !ciphertext) throw new Error("GitHub credential ciphertext is malformed."); const decipher = crypto.createDecipheriv("aes-256-gcm", Buffer.from(keyHex, "hex"), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(ciphertext, "base64url")), decipher.final()]).toString("utf8")) as GitHubCredentials; }
async function githubRequest<T>(path: string, token: string): Promise<{ data: T; headers: Headers }> { const response = await fetch(`${API}${path}`, { headers: { accept: "application/vnd.github+json", authorization: `Bearer ${token}`, "x-github-api-version": API_VERSION, "user-agent": "Aegis-AI/1.0" } }); const text = await response.text(); let body: unknown = {}; try { body = text ? JSON.parse(text) : {}; } catch { body = { raw: text }; } if (!response.ok) { const error = new Error(`GitHub API ${response.status}: ${typeof body === "object" ? JSON.stringify(body).slice(0, 1200) : String(body)}`); (error as Error & { status?: number }).status = response.status; throw error; } return { data: body as T, headers: response.headers }; }
function nextPage(headers: Headers): number | null { const match = headers.get("link")?.match(/<[^>]+[?&]page=(\d+)[^>]*>;\s*rel="next"/); return match ? Number(match[1]) : null; }
async function githubPaginate<T>(path: string, token: string, limitPages = 100, collectionKey?: string): Promise<T[]> { const rows: T[] = []; let page = 1; for (let i = 0; i < limitPages; i += 1) { const separator = path.includes("?") ? "&" : "?"; const { data, headers } = await githubRequest<unknown>(`${path}${separator}per_page=100&page=${page}`, token); const pageRows = Array.isArray(data) ? data : collectionKey && data && typeof data === "object" && Array.isArray((data as Record<string, unknown>)[collectionKey]) ? (data as Record<string, unknown>)[collectionKey] : []; rows.push(...(pageRows as T[])); const next = nextPage(headers); if (!next) break; page = next; } return rows; }
function isUnavailableSecurityEndpoint(error: unknown) { const status = error instanceof Error ? (error as Error & { status?: number }).status : undefined; return status === 403 || status === 404; }
async function getConnection(tenantId: string, connectionId: string) { const { data, error } = await supabaseAdmin.from("provider_connections").select("id,tenant_id,provider,status,encrypted_credentials").eq("id", connectionId).eq("tenant_id", tenantId).eq("provider", "github").maybeSingle(); if (error) throw error; if (!data) throw new Error("GitHub integration connection was not found for this tenant."); if (data.status !== "connected") throw new Error(`GitHub connection is ${data.status}.`); if (!data.encrypted_credentials) throw new Error("GitHub connection has no stored credentials."); return { ...data, credentials: decryptCredentials(data.encrypted_credentials) }; }
async function recordSyncAudit(tenantId: string, connectionId: string, action: string, detail: string, payload: Record<string, unknown>) { const { data, error } = await supabaseAdmin.from("audit_log").insert({ tenant_id: tenantId, action, entity_type: "github_sync", entity_id: connectionId, detail, payload }).select("id").maybeSingle(); if (error) throw error; return data?.id ?? null; }
export async function healthCheckGitHub(tenantId: string, connectionId: string) { const connection = await getConnection(tenantId, connectionId); const token = connection.credentials.accessToken; if (!token) throw new Error("GitHub connection has no access token."); const { data } = await githubRequest<{ id: number; login: string; name?: string | null }>("/user", token); return { ok: true as const, externalId: String(data.id), login: data.login, displayName: data.name ?? data.login }; }
function repoEntity(repo: GitHubRepository, syncedAt: string) { return { entity_type: "repository", entity_key: String(repo.id), repository_name: repo.full_name, html_url: repo.html_url, provider_updated_at: repo.updated_at, synced_at: syncedAt, stale: false, payload: { id: repo.id, name: repo.name, fullName: repo.full_name, private: repo.private, archived: repo.archived, defaultBranch: repo.default_branch, pushedAt: repo.pushed_at, updatedAt: repo.updated_at, url: repo.html_url } }; }
function workflowEntity(run: GitHubWorkflowRun, syncedAt: string, repositoryName: string) { return { entity_type: "workflow_run", entity_key: String(run.id), repository_name: repositoryName, workflow_status: run.status, workflow_conclusion: run.conclusion, html_url: run.html_url, provider_updated_at: run.updated_at, synced_at: syncedAt, stale: false, payload: { id: run.id, name: run.name, status: run.status, conclusion: run.conclusion, createdAt: run.created_at, updatedAt: run.updated_at, runStartedAt: run.run_started_at, repository: repositoryName, url: run.html_url } }; }
function securityEntity(alert: GitHubCodeAlert | GitHubDependabotAlert, kind: "code_scanning" | "dependabot", syncedAt: string, repositoryName: string) { const code = kind === "code_scanning"; const severity = code ? alert.rule?.security_severity_level ?? alert.rule?.severity ?? null : alert.security_advisory?.severity ?? null; const title = code ? alert.rule?.description ?? `Code scanning alert #${alert.number}` : alert.security_advisory?.summary ?? `Dependabot alert #${alert.number}`; return { entity_type: "security_alert", entity_key: `${kind}:${repositoryName}:${alert.number}`, repository_name: repositoryName, alert_severity: severity, alert_title: title, alert_state: alert.state, html_url: alert.html_url ?? null, provider_updated_at: alert.updated_at ?? alert.created_at ?? null, synced_at: syncedAt, stale: false, payload: { kind, number: alert.number, state: alert.state, severity, title, url: alert.html_url ?? null, createdAt: alert.created_at ?? null, updatedAt: alert.updated_at ?? null, dependency: alert.dependency ?? null, advisory: alert.security_advisory ?? null } }; }
export function reconcileGithubEntityKeys(existingKeys: string[], currentKeys: string[]) { const current = new Set(currentKeys); return existingKeys.filter((key) => !current.has(key)); }

export async function syncGitHub(tenantId: string, connectionId: string, entityScope: GitHubEntityScope = "all", syncRunId?: string, idempotencyKey?: string): Promise<GitHubSyncResult> {
  const connection = await getConnection(tenantId, connectionId); const token = connection.credentials.accessToken; if (!token) throw new Error("GitHub connection has no access token."); const attemptedAt = new Date().toISOString(); const runKey = idempotencyKey ?? `github-sync:${tenantId}:${connectionId}:${Math.floor(Date.now() / 300000)}`;
  const { data: prior } = await supabaseAdmin.from("provider_sync_runs").select("id,status").eq("tenant_id", tenantId).eq("connection_id", connectionId).eq("idempotency_key", runKey).maybeSingle(); if (prior?.status === "success") return getGitHubSyncStatus(tenantId, connectionId); const run = syncRunId ?? prior?.id;
  const statusTable = supabaseAdmin.from("github_sync_status" as any); await statusTable.upsert({ tenant_id: tenantId, connection_id: connectionId, last_attempted_at: attemptedAt, status: "running", error_message: null, updated_at: attemptedAt }, { onConflict: "tenant_id,connection_id" });
  const scopes = entityScope === "all" ? new Set(["repository", "workflow_run", "security_alert"]) : new Set(entityScope === "repositories" ? ["repository"] : entityScope === "workflows" ? ["workflow_run"] : ["security_alert"]);
  try {
    const repos = await githubPaginate<GitHubRepository>("/user/repos?sort=updated&affiliation=owner,collaborator,organization_member", token); const syncedAt = new Date().toISOString(); const rows: any[] = [];
    if (scopes.has("repository")) rows.push(...repos.map((repo) => repoEntity(repo, syncedAt))); let workflowCount = 0;
    for (const repo of repos) { const [owner, name] = repo.full_name.split("/"); const repoPath = `/repos/${encodeURIComponent(owner)}/${encodeURIComponent(name)}`; if (scopes.has("workflow_run")) { const runs = await githubPaginate<GitHubWorkflowRun>(`${repoPath}/actions/runs`, token, 2, "workflow_runs"); workflowCount += runs.length; rows.push(...runs.map((run) => workflowEntity(run, syncedAt, repo.full_name))); } if (scopes.has("security_alert")) { const [code, dependabot] = await Promise.allSettled([githubPaginate<GitHubCodeAlert>(`${repoPath}/code-scanning/alerts?state=open&sort=updated&direction=desc`, token), githubPaginate<GitHubDependabotAlert>(`${repoPath}/dependabot/alerts?state=open&sort=updated&direction=desc`, token)]); if (code.status === "rejected" && !isUnavailableSecurityEndpoint(code.reason)) throw code.reason; if (dependabot.status === "rejected" && !isUnavailableSecurityEndpoint(dependabot.reason)) throw dependabot.reason; if (code.status === "fulfilled") rows.push(...code.value.map((alert) => securityEntity(alert, "code_scanning", syncedAt, repo.full_name))); if (dependabot.status === "fulfilled") rows.push(...dependabot.value.map((alert) => securityEntity(alert, "dependabot", syncedAt, repo.full_name))); } }
    const securityCount = rows.filter((row) => row.entity_type === "security_alert").length; const { data: existing, error: existingError } = await supabaseAdmin.from("github_synced_entities" as any).select("entity_type,entity_key").eq("tenant_id", tenantId).eq("connection_id", connectionId).eq("stale", false); if (existingError) throw existingError;
    const currentKeys = new Set(rows.map((row) => `${row.entity_type}:${row.entity_key}`)); const staleRows = (existing ?? []).filter((row: any) => scopes.has(row.entity_type) && !currentKeys.has(`${row.entity_type}:${row.entity_key}`));
    for (const row of staleRows) { const { error } = await supabaseAdmin.from("github_synced_entities" as any).update({ stale: true, synced_at: syncedAt }).eq("tenant_id", tenantId).eq("connection_id", connectionId).eq("entity_type", row.entity_type).eq("entity_key", row.entity_key); if (error) throw error; }
    for (const row of rows) { const { error } = await supabaseAdmin.from("github_synced_entities" as any).upsert({ tenant_id: tenantId, connection_id: connectionId, ...row }, { onConflict: "tenant_id,connection_id,entity_type,entity_key" }); if (error) throw error; }
    const counts = { repositories: rows.filter((r) => r.entity_type === "repository").length, workflowRuns: workflowCount, securityAlerts: securityCount }; const finishedAt = new Date().toISOString(); const auditId = await recordSyncAudit(tenantId, connectionId, "github.sync.succeeded", `GitHub sync completed with ${rows.length} records.`, { entityScope, ...counts, staleCount: staleRows.length, idempotencyKey: runKey });
    const { error: statusError } = await statusTable.upsert({ tenant_id: tenantId, connection_id: connectionId, last_attempted_at: attemptedAt, last_successful_at: finishedAt, status: "success", error_message: null, repositories_count: counts.repositories, workflow_runs_count: counts.workflowRuns, security_alerts_count: counts.securityAlerts, updated_at: finishedAt }, { onConflict: "tenant_id,connection_id" }); if (statusError) throw statusError;
    if (run) { const { error: runError } = await supabaseAdmin.from("provider_sync_runs").update({ status: "success", finished_at: finishedAt, records_seen: rows.length, records_upserted: rows.length, records_staled: staleRows.length, audit_log_id: auditId, error_message: null }).eq("id", run).eq("tenant_id", tenantId); if (runError) throw runError; }
    return { connectionId, status: "success", lastAttemptedAt: attemptedAt, lastSuccessfulAt: finishedAt, repositoriesCount: counts.repositories, workflowRunsCount: counts.workflowRuns, securityAlertsCount: counts.securityAlerts, errorMessage: null, healthStatus: "healthy", staleCount: staleRows.length, recordsUpserted: rows.length };
  } catch (error) { const message = error instanceof Error ? error.message : String(error); await statusTable.upsert({ tenant_id: tenantId, connection_id: connectionId, last_attempted_at: attemptedAt, status: "failed", error_message: message.slice(0, 2000), updated_at: new Date().toISOString() }, { onConflict: "tenant_id,connection_id" }); let auditId: string | null = null; try { auditId = await recordSyncAudit(tenantId, connectionId, "github.sync.failed", "GitHub sync failed.", { entityScope, error: message.slice(0, 2000), idempotencyKey: runKey }); } catch { /* preserve original provider error */ } if (run) await supabaseAdmin.from("provider_sync_runs").update({ status: "failed", finished_at: new Date().toISOString(), audit_log_id: auditId, error_message: message.slice(0, 2000) }).eq("id", run).eq("tenant_id", tenantId); throw error; }
}
export async function getGitHubSyncStatus(tenantId: string, connectionId: string): Promise<GitHubSyncStatusResult> { const { data, error } = await supabaseAdmin.from("github_sync_status" as any).select("connection_id,status,last_attempted_at,last_successful_at,repositories_count,workflow_runs_count,security_alerts_count,error_message").eq("tenant_id", tenantId).eq("connection_id", connectionId).maybeSingle(); if (error) throw error; if (!data) return { connectionId, status: "never", lastAttemptedAt: null, lastSuccessfulAt: null, repositoriesCount: 0, workflowRunsCount: 0, securityAlertsCount: 0, errorMessage: null, healthStatus: "unknown" }; return { connectionId: data.connection_id, status: data.status as GitHubSyncStatus, lastAttemptedAt: data.last_attempted_at, lastSuccessfulAt: data.last_successful_at, repositoriesCount: Number(data.repositories_count ?? 0), workflowRunsCount: Number(data.workflow_runs_count ?? 0), securityAlertsCount: Number(data.security_alerts_count ?? 0), errorMessage: data.error_message, healthStatus: data.status === "success" ? "healthy" : data.status === "failed" ? "unhealthy" : "unknown" }; }
export async function authorizeGitHubSync(supabase: SupabaseClient, userId: string, connectionId: string) { const context = await resolveTenantContext(supabase, userId); if (!context.roles.some((role) => ["admin", "manager", "analyst"].includes(role))) throw new Error("Analyst access is required to synchronize GitHub data."); await getConnection(context.tenantId, connectionId); return context.tenantId; }
