import { PROVIDER_REGISTRY } from "@/lib/integrations/provider-registry";

export interface ProviderSetupField {
  key: string;
  label: string;
  required?: boolean;
  sensitive?: boolean;
  description?: string;
}

export interface ProviderSetupGuide {
  providerId: string;
  summary: string;
  prerequisites: string[];
  providerSteps: string[];
  cenopsSteps: string[];
  fieldMap: ProviderSetupField[];
  officialLinks: Array<{ label: string; url: string }>;
  troubleshooting: string[];
}

const sharedTroubleshooting = [
  "If credential storage fails before provider authorization starts, verify the server has AEGIS_CREDENTIAL_ENCRYPTION_KEY configured. Never put this secret in a VITE_ or browser-visible variable.",
  "Authentication success does not by itself mean the integration is Connected. Wait for the real health check and a successful synchronization where a production sync path exists.",
  "If a provider is registered but its production connector contract is incomplete, CenOps must report that boundary rather than inventing live status or data.",
];

const guides: Record<string, Omit<ProviderSetupGuide, "providerId">> = {
  genesys: {
    summary: "Connect Genesys Cloud for voice, digital, workforce and license telemetry.",
    prerequisites: ["A Genesys Cloud organization with permission to create an OAuth client.", "A supported Genesys Cloud region and the CenOps redirect URI."],
    providerSteps: ["In Genesys Cloud, open Admin → Integrations → OAuth and choose Add client.", "Use Client Credentials as the grant type.", "Assign the read roles/divisions required for organization, users, licenses, routing and analytics.", "Copy the Client ID and Client Secret."],
    cenopsSteps: ["Open Integrations → Genesys Cloud → Connect.", "Enter the integration name and environment.", "Enter Client ID and Client Secret and select the Genesys region.", "Authorize and wait for the health check and synchronization result."],
    fieldMap: [{key:"clientId",label:"Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true},{key:"region",label:"Region",required:true}],
    officialLinks: [{label:"Create OAuth client",url:"https://help.genesys.cloud/articles/create-an-oauth-client/"},{label:"Client credentials",url:"https://developer.genesys.cloud/authorization/platform-auth/use-client-credentials"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  aws: {
    summary: "Connect AWS through cross-account IAM role assumption for cloud inventory, cost and operational signals.",
    prerequisites: ["An AWS administrator who can create or update the target IAM role trust policy.", "The CenOps-generated external ID and the target role ARN."],
    providerSteps: ["Create an IAM role for CenOps cross-account access.", "Configure the trust relationship for the CenOps AWS account and the generated external ID.", "Attach only the least-privilege permissions required for the AWS data you want CenOps to read.", "Copy the role ARN."],
    cenopsSteps: ["Open Integrations → AWS → Connect.", "Generate the external ID in CenOps.", "Add that external ID to the AWS trust policy.", "Enter the AWS Role ARN and click Connect & verify."],
    fieldMap: [{key:"roleArn",label:"AWS Role ARN",required:true},{key:"externalId",label:"External ID",required:true,description:"Generated by CenOps; use it in the AWS trust relationship."}],
    officialLinks: [{label:"IAM roles",url:"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html"},{label:"AssumeRole",url:"https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html"}],
    troubleshooting: [...sharedTroubleshooting,"An AWS role can be correctly configured yet still fail if the trust relationship or attached permissions do not allow the requested APIs."],
  },
  azure: {
    summary: "Connect Microsoft Azure using Microsoft Entra application credentials for Resource Graph, Cost Management and Defender context.",
    prerequisites: ["An Entra application with a tenant ID, client ID and client secret.", "API permissions appropriate to the Azure management data you want to expose."],
    providerSteps: ["In Entra ID, create an App registration.", "Create a client secret.", "Grant the required Azure management/API permissions and admin consent where required.", "Record the tenant ID, application client ID and secret."],
    cenopsSteps: ["Open Integrations → Microsoft Azure → Connect.", "Enter the Entra Tenant ID, Application Client ID and Client Secret.", "Authorize and wait for the connection result and sync state."],
    fieldMap: [{key:"tenant",label:"Microsoft Entra Tenant ID",required:true},{key:"clientId",label:"Application Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Register an app",url:"https://learn.microsoft.com/en-us/graph/auth-register-app-v2"},{label:"Configure API permissions",url:"https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-configure-app-access-web-apis"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  gcp: {
    summary: "Connect Google Cloud using a service account for compute, storage, IAM and cost insights.",
    prerequisites: ["A Google Cloud service account with access to the target project.", "The service-account email, project ID and private key material."],
    providerSteps: ["Open GCP IAM → Service Accounts and create or select a service account.", "Grant only the Viewer/cost permissions required by your CenOps use case.", "Create the service-account key where your security policy permits it.", "Copy the service-account email, project ID and private key."],
    cenopsSteps: ["Open Integrations → Google Cloud → Connect.", "Enter service-account email, project ID and private key.", "Run connection verification and wait for the sync result."],
    fieldMap: [{key:"clientEmail",label:"Service account email",required:true},{key:"projectId",label:"Project ID",required:true},{key:"privateKey",label:"Service account private key",required:true,sensitive:true}],
    officialLinks: [{label:"Create service accounts",url:"https://cloud.google.com/iam/docs/service-accounts-create"},{label:"Create and manage keys",url:"https://cloud.google.com/iam/docs/keys-create-delete"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  m365: {
    summary: "Connect Microsoft 365 through Microsoft Entra application credentials for users and licensing context.",
    prerequisites: ["An Entra app registration with tenant ID, client ID and secret.", "The Microsoft Graph application permissions required by the implemented connector and admin consent."],
    providerSteps: ["Create an Entra App registration.", "Add the required Microsoft Graph application permissions such as User.Read.All and LicenseAssignment.Read.All.", "Grant admin consent.", "Create a client secret and record the tenant ID, client ID and secret."],
    cenopsSteps: ["Open Integrations → Microsoft 365 → Connect.", "Enter Tenant ID, Client ID and Client Secret.", "Authorize and wait for health and synchronization."],
    fieldMap: [{key:"tenant",label:"Microsoft Entra Tenant ID",required:true},{key:"clientId",label:"Application Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Register an app",url:"https://learn.microsoft.com/en-us/graph/auth-register-app-v2"},{label:"Microsoft Graph permissions",url:"https://learn.microsoft.com/en-us/graph/permissions-reference"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  "google-workspace": {
    summary: "Connect Google Workspace using a service account with domain-wide delegation.",
    prerequisites: ["A Google Cloud service account.", "Admin SDK APIs enabled.", "Workspace Admin domain-wide delegation configured for the required read scopes.", "A delegated administrator email."],
    providerSteps: ["Create the service account in Google Cloud.", "Enable the required Admin SDK APIs.", "Configure domain-wide delegation in Google Workspace Admin → API controls.", "Authorize the required Admin SDK scopes and record the service-account email, private key and delegated admin email."],
    cenopsSteps: ["Open Integrations → Google Workspace → Connect.", "Enter the service-account email, delegated admin email and private key.", "Verify access and wait for synchronization."],
    fieldMap: [{key:"clientEmail",label:"Service account email",required:true},{key:"delegatedAdminEmail",label:"Delegated admin email",required:true},{key:"privateKey",label:"Service account private key",required:true,sensitive:true}],
    officialLinks: [{label:"Create credentials",url:"https://developers.google.com/workspace/guides/create-credentials"},{label:"Domain-wide delegation",url:"https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  jira: {
    summary: "Connect Jira Cloud through an Atlassian OAuth 2.0 application.",
    prerequisites: ["An Atlassian developer application.", "The CenOps Jira callback URI and required read/write Jira scopes."],
    providerSteps: ["Create an Atlassian app.", "Configure OAuth 2.0 (3LO).", "Add the CenOps callback URI and scopes such as read:jira-work and write:jira-work.", "Copy the client ID and secret."],
    cenopsSteps: ["Open Integrations → Jira → Connect.", "Enter the OAuth client ID and secret.", "Authorize Atlassian and complete the callback.", "Wait for the real connection and sync status."],
    fieldMap: [{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Jira OAuth 2.0 (3LO)",url:"https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  servicenow: {
    summary: "Connect ServiceNow through an OAuth application and instance URL.",
    prerequisites: ["A ServiceNow instance.", "An OAuth application with a client ID and secret.", "The CenOps callback URI."],
    providerSteps: ["In ServiceNow, open System OAuth → Application Registry.", "Create an OAuth API endpoint for external clients.", "Record the client ID and client secret and configure the CenOps callback URI."],
    cenopsSteps: ["Open Integrations → ServiceNow → Connect.", "Enter the instance URL, client ID and client secret.", "Authorize and complete the callback.", "Wait for health and sync."],
    fieldMap: [{key:"baseUrl",label:"ServiceNow instance URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"OAuth on ServiceNow",url:"https://docs.servicenow.com/bundle/xanadu-platform-security/page/administer/security/concept/c_OAuthApplications.html"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  freshworks: {
    summary: "Connect Freshworks/Freshservice using an OAuth application for tickets, assets and SLA context.",
    prerequisites: ["A Freshservice organization.", "An OAuth application and the required ticket scopes.", "The CenOps callback URI."],
    providerSteps: ["Create/configure a Freshworks OAuth application.", "Grant the scopes needed for the Freshservice resources you want to sync.", "Record the organization URL, client ID and secret."],
    cenopsSteps: ["Open Integrations → Freshworks → Connect.", "Enter the Freshservice organization URL, client ID and secret.", "Authorize and complete the callback.", "Review the real health and sync status."],
    fieldMap: [{key:"orgUrl",label:"Freshservice organization URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Freshworks developer",url:"https://developers.freshworks.com/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  zendesk: {
    summary: "Connect Zendesk for support tickets, customers, agents and service metrics.",
    prerequisites: ["A Zendesk subdomain.", "A global OAuth client and secret configured with the CenOps callback URI."],
    providerSteps: ["In Zendesk, create/configure an OAuth client.", "Configure the CenOps callback URI and required read scopes.", "Record the subdomain, client ID and secret."],
    cenopsSteps: ["Open Integrations → Zendesk → Connect.", "Enter the subdomain, global OAuth client ID and secret.", "Authorize Zendesk and wait for synchronization."],
    fieldMap: [{key:"subdomain",label:"Zendesk subdomain",required:true},{key:"clientId",label:"Global OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Zendesk API authentication",url:"https://developer.zendesk.com/api-reference/introduction/security-and-auth/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  salesforce: {
    summary: "Connect Salesforce using OAuth client credentials and the configured Salesforce environment.",
    prerequisites: ["A Salesforce app/External Client App with API OAuth enabled.", "An integration user and the required API scope.", "The CenOps callback/redirect configuration required by the selected OAuth flow."],
    providerSteps: ["In Salesforce Setup, open App Manager/External Client Apps.", "Enable OAuth and the API scope required by CenOps.", "Configure the client credentials flow where that is the selected implementation.", "Copy the consumer/client key and secret."],
    cenopsSteps: ["Open Integrations → Salesforce → Connect.", "Enter Client ID and Client Secret.", "Select the appropriate environment.", "Authorize and wait for health and sync."],
    fieldMap: [{key:"clientId",label:"Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Salesforce OAuth and Connected Apps",url:"https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.htm"},{label:"Client credentials flow",url:"https://help.salesforce.com/s/articleView?id=xcloud.remoteaccess_oauth_client_credentials_flow_ca.htm"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  zoho: {
    summary: "Connect Zoho CRM using a server-based OAuth application.",
    prerequisites: ["A Zoho API Console server-based application.", "The appropriate Zoho CRM scopes and regional Accounts URL."],
    providerSteps: ["Create a server-based application in the Zoho API Console.", "Configure the required CRM scopes.", "Record the Accounts URL, client ID and secret."],
    cenopsSteps: ["Open Integrations → Zoho → Connect.", "Select the correct Accounts region URL.", "Enter client ID and secret and complete authorization."],
    fieldMap: [{key:"accountsUrl",label:"Zoho Accounts URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Zoho CRM OAuth overview",url:"https://www.zoho.com/crm/developer/docs/api/v2/oauth-overview.html"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  hubspot: {
    summary: "Connect HubSpot through an OAuth application for CRM, ticket and engagement context.",
    prerequisites: ["A HubSpot developer app.", "Required scopes and the CenOps callback URI."],
    providerSteps: ["Create a HubSpot app.", "Configure authentication and the scopes required for CenOps.", "Copy the client ID and secret."],
    cenopsSteps: ["Open Integrations → HubSpot → Connect.", "Enter client ID and secret.", "Authorize HubSpot and wait for the sync state."],
    fieldMap: [{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"HubSpot OAuth",url:"https://developers.hubspot.com/docs/apps/developer-platform/build-apps/authentication/oauth/working-with-oauth"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  slack: {
    summary: "Connect Slack for channels, messages and workflow context.",
    prerequisites: ["A Slack app.", "The required OAuth scopes and workspace installation permission.", "The CenOps callback URI."],
    providerSteps: ["Create a Slack app.", "Configure OAuth scopes.", "Install the app to the target workspace and configure the callback.", "Record the client ID and secret."],
    cenopsSteps: ["Open Integrations → Slack → Connect.", "Enter client ID and secret.", "Authorize Slack and choose the target workspace if prompted.", "Wait for synchronization."],
    fieldMap: [{key:"clientId",label:"Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Slack OAuth installation",url:"https://docs.slack.dev/authentication/installing-with-oauth/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  github: {
    summary: "Connect GitHub through the CenOps GitHub App installation flow.",
    prerequisites: ["Permission to install the CenOps GitHub App.", "The repositories the installation should be allowed to access."],
    providerSteps: ["Open the GitHub App installation flow from CenOps.", "Choose the GitHub organization/account.", "Select only the repositories CenOps should access.", "Complete installation and return to CenOps."],
    cenopsSteps: ["Open Integrations → GitHub → Connect.", "Continue to GitHub.", "Install the App and select repositories.", "Return to CenOps and wait for the real sync status."],
    fieldMap: [{key:"installation",label:"GitHub App installation",required:true,description:"No personal access token is entered in CenOps."}],
    officialLinks: [{label:"Register a GitHub App",url:"https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app"},{label:"Choose GitHub App permissions",url:"https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app"},{label:"Install a GitHub App",url:"https://docs.github.com/en/apps/using-github-apps/installing-a-github-app-from-a-third-party"}],
    troubleshooting: [...sharedTroubleshooting,"Do not paste a personal access token into the GitHub integration. The product flow uses the GitHub App installation."],
  },
  gitlab: {
    summary: "Connect GitLab through an OAuth application for projects, pipelines, repositories and security findings.",
    prerequisites: ["A GitLab OAuth application.", "The CenOps callback URI and required scopes."],
    providerSteps: ["Create an OAuth application in GitLab Applications/User Settings.", "Configure the redirect URI and required scopes.", "Copy the application ID and secret."],
    cenopsSteps: ["Open Integrations → GitLab → Connect.", "Enter the GitLab instance URL, client ID and secret.", "Authorize and wait for sync."],
    fieldMap: [{key:"baseUrl",label:"GitLab instance URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"GitLab OAuth applications",url:"https://docs.gitlab.com/ee/integration/oauth_provider.html"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  confluence: {
    summary: "Connect Confluence for knowledge spaces, pages and operational documentation.",
    prerequisites: ["An Atlassian OAuth application with Confluence read scopes.", "The CenOps callback URI."],
    providerSteps: ["Configure an Atlassian OAuth app for Confluence.", "Grant the required Confluence scopes.", "Record the client ID and secret."],
    cenopsSteps: ["Open Integrations → Confluence → Connect.", "Enter client ID and secret.", "Authorize Atlassian and wait for synchronization."],
    fieldMap: [{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Confluence Cloud OAuth",url:"https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  rubrik: {
    summary: "Connect Rubrik Security Cloud using service-account client credentials.",
    prerequisites: ["Rubrik Security Cloud access.", "A service account with the required roles.", "The RSC client ID, secret and token endpoint."],
    providerSteps: ["In RSC, open Settings → Users and Access → Service Accounts.", "Add a service account and assign the minimum required roles.", "Download/record the client ID and secret and use the documented access-token URI."],
    cenopsSteps: ["Open Integrations → Rubrik → Connect.", "Enter the RSC client ID, client secret and access-token URI.", "Run connection validation and wait for sync."],
    fieldMap: [{key:"clientId",label:"Rubrik Security Cloud Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true},{key:"accessTokenUri",label:"Access token URI",required:true}],
    officialLinks: [{label:"Rubrik Security Cloud authentication",url:"https://developer.rubrik.com/Rubrik-Security-Cloud-API/authentication/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  veeam: {
    summary: "Connect Veeam Service Provider Console using the credential flow exposed by the current CenOps connector.",
    prerequisites: ["A Veeam Service Provider Console instance and an account permitted to use its API."],
    providerSteps: ["Open the Veeam Service Provider Console API/OAuth documentation for your deployed product version.", "Create or identify the API-capable account and record the base URL and credentials."],
    cenopsSteps: ["Open Integrations → Veeam → Connect.", "Enter the Veeam Service Provider Console URL, username and password.", "Run connection verification and wait for synchronization."],
    fieldMap: [{key:"baseUrl",label:"Veeam Service Provider Console URL",required:true},{key:"username",label:"Username",required:true},{key:"password",label:"Password",required:true,sensitive:true}],
    officialLinks: [{label:"Veeam Help Center",url:"https://helpcenter.veeam.com/"}],
    troubleshooting: [...sharedTroubleshooting,"Veeam authentication differs by Veeam product/deployment. Use the documentation for the exact Service Provider Console version rather than assuming a generic Veeam OAuth flow."],
  },
  cohesity: {
    summary: "Connect Cohesity through the API key and API base URL exposed by the current connector.",
    prerequisites: ["A Cohesity cluster/Helios environment and an API key with the required read permissions."],
    providerSteps: ["Open the Cohesity administration/developer interface.", "Create an API/access key with least-privilege permissions.", "Copy the API base URL and key."],
    cenopsSteps: ["Open Integrations → Cohesity → Connect.", "Enter the API base URL and API key.", "Verify access and wait for sync."],
    fieldMap: [{key:"baseUrl",label:"Cohesity API base URL",required:true},{key:"apiKey",label:"API Key",required:true,sensitive:true}],
    officialLinks: [{label:"Cohesity Developer",url:"https://developer.cohesity.com/"}],
    troubleshooting: [...sharedTroubleshooting,"Cohesity authentication and endpoints can differ by product/deployment. Confirm the target API before creating credentials."],
  },
  crowdstrike: {
    summary: "Connect CrowdStrike Falcon through OAuth 2.0 client credentials.",
    prerequisites: ["Falcon API client credentials.", "The correct regional Falcon API base URL.", "Scopes appropriate to the evidence CenOps should read."],
    providerSteps: ["In Falcon, open Support → API Clients and Keys.", "Create an API client with the minimum required scopes.", "Record the client ID, secret and regional API base URL."],
    cenopsSteps: ["Open Integrations → CrowdStrike → Connect.", "Enter Falcon API base URL, client ID and secret.", "Authorize and wait for health and sync."],
    fieldMap: [{key:"apiBaseUrl",label:"Falcon OAuth API base URL",required:true},{key:"clientId",label:"Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"CrowdStrike API documentation",url:"https://falcon.crowdstrike.com/documentation/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  "microsoft-defender": {
    summary: "Connect Microsoft Defender through Microsoft Entra application credentials.",
    prerequisites: ["An Entra application.", "Defender/Graph permissions such as Alert.Read.All and AdvancedQuery.Read.All as required.", "Tenant ID and client secret with admin consent where required."],
    providerSteps: ["Register an Entra application.", "Grant the required Defender/Graph application permissions.", "Grant admin consent.", "Create a client secret and record tenant ID, client ID and secret."],
    cenopsSteps: ["Open Integrations → Microsoft Defender → Connect.", "Enter customer tenant ID, client ID and secret.", "Verify access and wait for synchronization."],
    fieldMap: [{key:"customerTenantId",label:"Microsoft Entra Tenant ID",required:true},{key:"clientId",label:"Application Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Microsoft Graph app registration",url:"https://learn.microsoft.com/en-us/graph/auth-register-app-v2"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  okta: {
    summary: "Connect Okta using an SSWS API token and organization URL.",
    prerequisites: ["Okta administrator access.", "An API token with the minimum required permissions.", "The Okta organization URL."],
    providerSteps: ["Open Okta Admin → Security → API → Tokens.", "Create a token for the CenOps integration.", "Copy the token once and record the organization URL."],
    cenopsSteps: ["Open Integrations → Okta → Connect.", "Enter the Okta org URL and SSWS API token.", "Verify access and wait for synchronization."],
    fieldMap: [{key:"baseUrl",label:"Okta org URL",required:true},{key:"apiToken",label:"SSWS API Token",required:true,sensitive:true}],
    officialLinks: [{label:"Create an Okta API token",url:"https://developer.okta.com/docs/guides/create-an-api-token/main/"},{label:"OAuth service apps",url:"https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  datadog: {
    summary: "Connect Datadog using an API key, application key and site.",
    prerequisites: ["Datadog organization access.", "An API key and application key with the required read permissions."],
    providerSteps: ["Open Datadog Organization Settings → API Keys and Application Keys.", "Create or select keys with least privilege.", "Identify the Datadog site used by the organization."],
    cenopsSteps: ["Open Integrations → Datadog → Connect.", "Select the Datadog site.", "Enter API Key and Application Key.", "Verify access and wait for sync."],
    fieldMap: [{key:"site",label:"Datadog site",required:true},{key:"apiKey",label:"API Key",required:true,sensitive:true},{key:"appKey",label:"Application Key",required:true,sensitive:true}],
    officialLinks: [{label:"Datadog API and application keys",url:"https://docs.datadoghq.com/account_management/api-app-keys/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  newrelic: {
    summary: "Connect New Relic using a user API key and the correct region.",
    prerequisites: ["New Relic account access.", "A user API key permitted to read the required telemetry.", "The New Relic region."],
    providerSteps: ["Open the New Relic user menu and API keys.", "Create/select a user key with the required access.", "Identify whether the account is in US, EU or Japan."],
    cenopsSteps: ["Open Integrations → New Relic → Connect.", "Select the region.", "Enter the User API Key.", "Verify and wait for synchronization."],
    fieldMap: [{key:"region",label:"Region",required:true},{key:"apiKey",label:"New Relic User API Key",required:true,sensitive:true}],
    officialLinks: [{label:"New Relic API keys",url:"https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  splunk: {
    summary: "Connect Splunk using a bearer token and REST API base URL.",
    prerequisites: ["A Splunk instance with REST API access.", "A token permitted to read the required data.", "The REST API base URL, commonly the management endpoint."],
    providerSteps: ["Create a Splunk authentication token using the provider's token management flow.", "Grant only the permissions required by CenOps.", "Record the REST API base URL and token."],
    cenopsSteps: ["Open Integrations → Splunk → Connect.", "Enter the REST API base URL and bearer token.", "Verify access and wait for sync."],
    fieldMap: [{key:"baseUrl",label:"Splunk REST API base URL",required:true},{key:"token",label:"Bearer token",required:true,sensitive:true}],
    officialLinks: [{label:"Splunk token authentication",url:"https://docs.splunk.com/Documentation/Splunk/latest/Security/UseTokenAuth"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  pagerduty: {
    summary: "Connect PagerDuty using a REST API token for incident and service context.",
    prerequisites: ["PagerDuty administrator/API access.", "A REST API token with the required read permissions."],
    providerSteps: ["Open PagerDuty Integrations → API Access Keys.", "Create an API key with the least privilege appropriate to the integration.", "Copy the token securely."],
    cenopsSteps: ["Open Integrations → PagerDuty → Connect.", "Enter the REST API token.", "Verify access and wait for synchronization."],
    fieldMap: [{key:"apiToken",label:"PagerDuty REST API token",required:true,sensitive:true}],
    officialLinks: [{label:"PagerDuty API key management",url:"https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTUy-api-key-management"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  workday: {
    summary: "Connect Workday using the tenant-specific OAuth configuration exposed by the current connector.",
    prerequisites: ["A Workday tenant.", "OAuth client credentials and redirect configuration.", "The Workday region and tenant alias."],
    providerSteps: ["Register/configure the Workday API client in the target tenant.", "Grant the required security domains/API permissions.", "Record region, tenant alias, client ID and secret."],
    cenopsSteps: ["Open Integrations → Workday → Connect.", "Select the region.", "Enter tenant alias, client ID and secret.", "Authorize and wait for synchronization."],
    fieldMap: [{key:"region",label:"Region",required:true},{key:"tenantAlias",label:"Workday tenant alias",required:true},{key:"clientId",label:"Client ID",required:true},{key:"clientSecret",label:"Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Workday API and OAuth",url:"https://community.workday.com/"}],
    troubleshooting: [...sharedTroubleshooting,"Workday access is constrained by tenant-specific security domains and business-process permissions; successful OAuth alone does not guarantee access to the desired REST APIs."],
  },
  sap: {
    summary: "Connect SAP using product/tenant-specific OAuth endpoints; CenOps does not guess SAP endpoints.",
    prerequisites: ["The exact SAP product/API target.", "An SAP service binding or application configuration that provides authorization and token endpoints.", "Client credentials and any required scope."],
    providerSteps: ["Identify the exact SAP product/API runtime.", "Create/configure the OAuth client or BTP/IAS service binding.", "Copy the documented authorization URL, token URL, client ID, secret and scope."],
    cenopsSteps: ["Open Integrations → SAP → Connect.", "Enter the documented authorization URL and token URL.", "Enter client ID, client secret and optional scope.", "Authorize and wait for the actual sync result."],
    fieldMap: [{key:"authorizationUrl",label:"OAuth Authorization URL",required:true},{key:"tokenUrl",label:"OAuth Token URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true},{key:"scope",label:"Scope"}],
    officialLinks: [{label:"SAP Help Portal",url:"https://help.sap.com/"}],
    troubleshooting: [...sharedTroubleshooting,"SAP authentication varies substantially by product and API runtime. Do not substitute a generic SAP OAuth endpoint."],
  },
  oracle: {
    summary: "Connect Oracle using the identity-domain OAuth configuration supported by the current connector.",
    prerequisites: ["An Oracle identity domain/application configuration.", "OAuth client credentials and any required scope."],
    providerSteps: ["Configure a confidential OAuth application in the target Oracle identity domain.", "Grant the required API permissions/scopes.", "Record the identity-domain URL, client ID and secret."],
    cenopsSteps: ["Open Integrations → Oracle → Connect.", "Enter the identity-domain URL, client ID and secret.", "Verify and wait for synchronization."],
    fieldMap: [{key:"identityDomainUrl",label:"Oracle identity domain URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"Oracle Cloud IAM policies",url:"https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/policygetstarted.htm"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  snowflake: {
    summary: "Connect Snowflake using an account-specific OAuth security integration.",
    prerequisites: ["A Snowflake account and role allowed to create/configure the security integration.", "An OAuth client and the required role/session scope."],
    providerSteps: ["Create/configure a Snowflake OAuth security integration for the chosen client model.", "Grant the minimum required role/session scope.", "Record the account URL, client ID, client secret and scope."],
    cenopsSteps: ["Open Integrations → Snowflake → Connect.", "Enter the Snowflake account URL, client ID, client secret and scope.", "Authorize and wait for synchronization."],
    fieldMap: [{key:"accountUrl",label:"Snowflake account URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true},{key:"scope",label:"Scope",required:true}],
    officialLinks: [{label:"Snowflake OAuth custom clients",url:"https://docs.snowflake.com/en/user-guide/oauth-custom"},{label:"CREATE SECURITY INTEGRATION",url:"https://docs.snowflake.com/en/sql-reference/sql/create-security-integration-oauth-snowflake"}],
    troubleshooting: [...sharedTroubleshooting],
  },
  mongodb: {
    summary: "Connect MongoDB Atlas using an Atlas service-account client-credential flow.",
    prerequisites: ["A MongoDB Atlas organization/project.", "An Atlas service account with the required roles.", "The Atlas account URL and client credentials."],
    providerSteps: ["In Atlas Access Manager, create/select a service account.", "Assign the minimum required project/organization roles.", "Copy the client ID and secret and confirm the Atlas account URL."],
    cenopsSteps: ["Open Integrations → MongoDB → Connect.", "Enter the Atlas account URL, client ID and secret.", "Verify access and wait for synchronization."],
    fieldMap: [{key:"accountUrl",label:"MongoDB Atlas account URL",required:true},{key:"clientId",label:"OAuth Client ID",required:true},{key:"clientSecret",label:"OAuth Client Secret",required:true,sensitive:true}],
    officialLinks: [{label:"MongoDB Atlas service accounts",url:"https://www.mongodb.com/docs/atlas/api/service-accounts-overview/"}],
    troubleshooting: [...sharedTroubleshooting],
  },
};

export const PROVIDER_SETUP_GUIDES: ProviderSetupGuide[] = PROVIDER_REGISTRY.map((provider) => {
  const guide = guides[provider.id];
  if (!guide) throw new Error("Missing provider setup guide for " + provider.id);
  return { providerId: provider.id, ...guide };
});

export const PROVIDER_SETUP_GUIDE_BY_ID = new Map(
  PROVIDER_SETUP_GUIDES.map((guide) => [guide.providerId, guide]),
);
