export type ProviderCapability = "read" | "write" | "sync" | "events";
export type ProviderAvailability = "available" | "coming_soon";
export interface ProviderDefinition { id: string; name: string; category: string; description: string; auth: "OAuth 2.0" | "API Key" | "Access Keys" | "AWS IAM Role" | "GitHub App" | "MCP"; scopes: string[]; capabilities: ProviderCapability[]; availability: ProviderAvailability; logoUrl: string; }
const simpleIcon = (slug: string, color?: string) => `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ""}`;

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  { id: "genesys", name: "Genesys Cloud", category: "Contact Center", description: "Voice, digital, workforce and license telemetry.", auth: "OAuth 2.0", scopes: ["organization:readonly", "users:readonly", "license:readonly", "routing:readonly", "analytics:readonly"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("genesys") },
  { id: "aws", name: "AWS", category: "Cloud", description: "EC2, S3, IAM, Cost Explorer and CloudWatch via cross-account IAM role assumption.", auth: "AWS IAM Role", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("amazonaws", "232f3e") },
  { id: "azure", name: "Microsoft Azure", category: "Cloud", description: "Resource Graph, Cost Management and Defender.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("microsoftazure", "0078d4") },
  { id: "gcp", name: "Google Cloud", category: "Cloud", description: "Compute, storage, IAM and cloud cost insights via a Google service account.", auth: "OAuth 2.0", scopes: ["https://www.googleapis.com/auth/cloud-platform"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("googlecloud") },
  { id: "m365", name: "Microsoft 365", category: "Productivity", description: "Entra ID, licensing, Teams and Exchange.", auth: "OAuth 2.0", scopes: ["LicenseAssignment.Read.All", "User.Read.All"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("microsoft365") },
  { id: "google-workspace", name: "Google Workspace", category: "Productivity", description: "Users, groups, Drive and workspace administration via service-account domain-wide delegation.", auth: "OAuth 2.0", scopes: ["https://www.googleapis.com/auth/admin.directory.user.readonly", "https://www.googleapis.com/auth/admin.directory.group.readonly"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("google") },
  { id: "jira", name: "Jira", category: "ITSM & DevOps", description: "Issues, projects, workflows and automation.", auth: "OAuth 2.0", scopes: ["read:jira-work", "write:jira-work"], capabilities: ["read", "write", "sync"], availability: "available", logoUrl: simpleIcon("jira") },
  { id: "servicenow", name: "ServiceNow", category: "ITSM", description: "Incidents, changes, problems and CMDB.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "write", "sync"], availability: "available", logoUrl: simpleIcon("servicenow") },
  { id: "freshworks", name: "Freshworks", category: "ITSM & Customer Support", description: "Freshservice, Freshdesk, tickets, assets and SLAs.", auth: "OAuth 2.0", scopes: ["freshservice.tickets.view", "freshservice.tickets.edit", "freshservice.tickets.conversations.create"], capabilities: ["read", "write", "sync"], availability: "available", logoUrl: simpleIcon("freshworks") },
  { id: "zendesk", name: "Zendesk", category: "Customer Support", description: "Support tickets, customers, agents and service metrics.", auth: "OAuth 2.0", scopes: ["read", "tickets:read", "users:read", "organizations:read"], capabilities: ["read", "write", "sync"], availability: "available", logoUrl: simpleIcon("zendesk") },
  { id: "salesforce", name: "Salesforce", category: "CRM", description: "Accounts, opportunities, cases and events.", auth: "OAuth 2.0", scopes: ["api"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("salesforce") },
  { id: "zoho", name: "Zoho", category: "CRM & Business", description: "Zoho CRM records, users and configuration context.", auth: "OAuth 2.0", scopes: ["ZohoCRM.modules.READ", "ZohoCRM.settings.READ", "ZohoCRM.users.READ"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("zoho") },
  { id: "hubspot", name: "HubSpot", category: "CRM & Marketing", description: "CRM records, tickets, engagements and automation context.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("hubspot") },
  { id: "slack", name: "Slack", category: "Collaboration", description: "Channels, messages and workflow context.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("slack") },
  { id: "github", name: "GitHub", category: "DevOps", description: "Repositories, Actions and security context via GitHub App installation.", auth: "GitHub App", scopes: ["installation-selected-repositories"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("github") },
  { id: "gitlab", name: "GitLab", category: "DevOps", description: "Projects, pipelines, repositories and security findings.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("gitlab") },
  { id: "confluence", name: "Confluence", category: "Knowledge & Collaboration", description: "Knowledge spaces, pages and operational documentation.", auth: "OAuth 2.0", scopes: ["read:confluence-content.all", "read:confluence-space.summary", "read:confluence-user", "offline_access"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("confluence") },
  { id: "rubrik", name: "Rubrik", category: "Data Protection", description: "Rubrik Security Cloud via service-account client credentials.", auth: "OAuth 2.0", scopes: ["client_credentials"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("rubrik") },
  { id: "veeam", name: "Veeam", category: "Data Protection", description: "Veeam Service Provider Console REST API with OAuth 2.0 tokens.", auth: "OAuth 2.0", scopes: ["password", "refresh_token"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("veeam") },
  { id: "cohesity", name: "Cohesity", category: "Data Protection", description: "Data security, backup, recovery and storage management.", auth: "API Key", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("cohesity") },
  { id: "crowdstrike", name: "CrowdStrike", category: "Security", description: "Endpoint security, detections, vulnerabilities and identity context via OAuth2 client credentials.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("crowdstrike") },
  { id: "microsoft-defender", name: "Microsoft Defender", category: "Security", description: "Threat detections, vulnerabilities and security posture via Microsoft Entra application context.", auth: "OAuth 2.0", scopes: ["Alert.Read.All", "AdvancedQuery.Read.All"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("microsoftdefender") },
  { id: "okta", name: "Okta", category: "Identity & Security", description: "Okta management APIs using an SSWS API token for org administration endpoints.", auth: "API Key", scopes: ["SSWS"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("okta") },
  { id: "datadog", name: "Datadog", category: "Observability", description: "Metrics, monitors, logs and service health signals.", auth: "API Key", scopes: ["api-key", "application-key"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("datadog") },
  { id: "newrelic", name: "New Relic", category: "Observability", description: "Application performance, alerts and infrastructure telemetry.", auth: "API Key", scopes: ["user-key"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("newrelic") },
  { id: "splunk", name: "Splunk", category: "Observability & Security", description: "Splunk REST API using a platform authentication token.", auth: "Access Keys", scopes: ["bearer-token"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("splunk") },
  { id: "pagerduty", name: "PagerDuty", category: "Incident Management", description: "Incidents, services, on-call schedules and response metrics.", auth: "API Key", scopes: ["provider-managed"], capabilities: ["read", "sync", "events"], availability: "available", logoUrl: simpleIcon("pagerduty") },
  { id: "workday", name: "Workday", category: "HR & Workforce", description: "Workforce identity, organizational and lifecycle context.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("workday") },
  { id: "sap", name: "SAP", category: "ERP", description: "SAP OAuth 2.0 connection using tenant/product-specific authorization and token endpoints.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("sap") },
  { id: "oracle", name: "Oracle", category: "ERP & Database", description: "Enterprise applications, databases and infrastructure context.", auth: "OAuth 2.0", scopes: ["provider-managed"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("oracle") },
  { id: "snowflake", name: "Snowflake", category: "Data & Analytics", description: "Warehouses, databases, usage and data platform telemetry via account-specific OAuth.", auth: "OAuth 2.0", scopes: ["session:role:PUBLIC"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("snowflake") },
  { id: "mongodb", name: "MongoDB", category: "Database", description: "MongoDB Atlas clusters, projects and operational health via Atlas service accounts.", auth: "OAuth 2.0", scopes: ["client_credentials"], capabilities: ["read", "sync"], availability: "available", logoUrl: simpleIcon("mongodb") },
];
