import crypto from "node:crypto";
import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { PROVIDER_REGISTRY } from "./provider-registry";
import { validateProviderConnection, type ProviderConnectionInput, type ProviderId } from "./production-connectors.server";

function encryptCredentials(value: unknown): string { const keyHex = process.env.AEGIS_CREDENTIAL_ENCRYPTION_KEY; if (!keyHex || !/^[0-9a-fA-F]{64}$/.test(keyHex)) throw new Error("AEGIS_CREDENTIAL_ENCRYPTION_KEY is not configured on the server."); const key = Buffer.from(keyHex, "hex"); const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", key, iv); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(value), "utf8"), cipher.final()]); const tag = cipher.getAuthTag(); return [iv.toString("base64url"), tag.toString("base64url"), ciphertext.toString("base64url")].join("."); }

type CatalogConnection = { id: string; provider: string; status: "connected" | "failed" | "disconnected"; display_name: string | null; environment: string; external_id: string | null; credential_expires_at: string | null; last_sync_at: string | null; last_error: string | null; connected_at: string | null; updated_at: string; sync_status?: "running" | "success" | "failed" | "never"; sync_last_attempted_at?: string | null; sync_last_successful_at?: string | null; sync_record_count?: number; sync_health_status?: "healthy" | "unhealthy" | "unknown"; sync_error?: string | null; sync_counts?: { repositories: number; workflowRuns: number; securityAlerts: number }; };
function mapGenesysIntegration(row: { id: string; provider: string; status: string; external_org_id: string | null; external_org_name: string | null; region: string | null; metadata: unknown; last_sync_at: string | null; last_sync_error: string | null; health_detail: string | null; connected_at: string | null; updated_at: string }): CatalogConnection { const status: CatalogConnection["status"] = row.status === "connected" ? "connected" : row.status === "disconnected" ? "disconnected" : "failed"; const environment = (() => { const meta = (row.metadata ?? null) as Record<string, unknown> | null; return typeof meta?.environment === "string" && meta.environment.trim() ? meta.environment : "Production"; })(); return { id: row.id, provider: "genesys", status, display_name: row.external_org_name || "Genesys Cloud", environment, external_id: row.external_org_id, credential_expires_at: null, last_sync_at: row.last_sync_at, last_error: row.last_sync_error || row.health_detail, connected_at: row.connected_at, updated_at: row.updated_at }; }

export const getProviderCatalog = createServerFn({ method: "GET" }).middleware([requireSupabaseAuth]).handler(async ({ context }) => {
  const { data: roles } = await context.supabase.from("user_roles").select("tenant_id,role").eq("user_id", context.userId);
  const tenantId = roles?.find((r) => r.tenant_id)?.tenant_id;
  const [{ data: providerConnections }, { data: genesysIntegrations }, { data: githubSyncStatuses }] = tenantId ? await Promise.all([
    context.supabase.from("provider_connections").select("id,provider,status,display_name,environment,external_id,credential_expires_at,last_sync_at,last_error,connected_at,updated_at").eq("tenant_id", tenantId).order("updated_at", { ascending: false }),
    context.supabase.from("integrations").select("id,provider,status,external_org_id,external_org_name,region,metadata,last_sync_at,last_sync_error,health_detail,connected_at,updated_at").eq("tenant_id", tenantId).eq("provider", "genesys").order("updated_at", { ascending: false }),
    context.supabase.from("github_sync_status" as any).select("connection_id,status,last_attempted_at,last_successful_at,repositories_count,workflow_runs_count,security_alerts_count,error_message").eq("tenant_id", tenantId),
  ]) : [{ data: [] }, { data: [] }, { data: [] }];
  const githubStatusByConnection = new Map((githubSyncStatuses ?? []).map((row: any) => [row.connection_id, row]));
  const genericConnections = ((providerConnections ?? []) as CatalogConnection[]).map((connection) => {
    if (connection.provider !== "github") return connection;
    const status = githubStatusByConnection.get(connection.id);
    if (!status) return { ...connection, sync_status: "never" as const, sync_health_status: "unknown" as const, sync_counts: { repositories: 0, workflowRuns: 0, securityAlerts: 0 } };
    return { ...connection, last_sync_at: status.last_successful_at ?? connection.last_sync_at, last_error: status.error_message ?? connection.last_error, sync_status: status.status, sync_last_attempted_at: status.last_attempted_at, sync_last_successful_at: status.last_successful_at, sync_record_count: Number(status.repositories_count ?? 0) + Number(status.workflow_runs_count ?? 0) + Number(status.security_alerts_count ?? 0), sync_health_status: status.status === "success" ? "healthy" as const : status.status === "failed" ? "unhealthy" as const : "unknown" as const, sync_error: status.error_message, sync_counts: { repositories: Number(status.repositories_count ?? 0), workflowRuns: Number(status.workflow_runs_count ?? 0), securityAlerts: Number(status.security_alerts_count ?? 0) } };
  });
  const mappedGenesys = (genesysIntegrations ?? []).map(mapGenesysIntegration);
  const hasDedicatedGenesys = mappedGenesys.length > 0;
  const connections = [...genericConnections.filter((x) => !hasDedicatedGenesys || x.provider !== "genesys"), ...mappedGenesys].sort((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime());
  return { providers: PROVIDER_REGISTRY.map((p) => ({ ...p, configured: connections.some((x) => x.provider === p.id && x.status === "connected"), connections: connections.filter((x) => x.provider === p.id) })), connections };
});

export const startProviderConnection = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: { provider: string }) => ({ provider: String(input.provider ?? "").trim().toLowerCase() as ProviderId })).handler(async ({ data }) => { const provider = PROVIDER_REGISTRY.find((p) => p.id === data.provider); if (!provider) return { ok: false as const, errorCode: "provider_not_supported", errorMessage: "Provider is not registered." }; return { ok: true as const, provider, requiresCredentials: true }; });

export const connectProvider = createServerFn({ method: "POST" }).middleware([requireSupabaseAuth]).inputValidator((input: Omit<ProviderConnectionInput, "tenantId"> & { connectionId?: string; displayName?: string; environment?: string }) => input).handler(async ({ data, context }) => { try { if ((data.provider as string) === "genesys") return { ok: false as const, error: "Genesys Cloud must be connected through its OAuth authorization flow." }; const { data: roles } = await context.supabase.from("user_roles").select("tenant_id,role").eq("user_id", context.userId); const tenantId = roles?.find((r) => r.role === "admin" || r.role === "manager")?.tenant_id; if (!tenantId) return { ok: false as const, error: "Admin/manager access is required to connect an integration." }; const result = await validateProviderConnection({ ...data, tenantId }); const encrypted = result.ok ? encryptCredentials({ accessToken: result.accessToken, refreshToken: result.refreshToken, clientId: data.clientId, clientSecret: data.clientSecret, apiToken: data.apiToken, accessKeyId: data.accessKeyId, secretAccessKey: data.secretAccessKey, sessionToken: data.sessionToken, tenant: data.tenant, baseUrl: data.baseUrl, region: data.region }) : null; const displayName = data.displayName?.trim() || result.displayName || null; const environment = data.environment?.trim() || "Production"; const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data: connectionId, error } = await supabaseAdmin.from("provider_connections").upsert({ id: data.connectionId ?? undefined, tenant_id: tenantId, provider: data.provider, external_id: result.externalId ?? null, display_name: displayName, environment, status: result.status, encrypted_credentials: encrypted, credential_expires_at: result.expiresAt ?? null, last_error: result.error ?? null, created_by: context.userId, connected_at: result.status === "connected" ? new Date().toISOString() : null, updated_at: new Date().toISOString() }, { onConflict: "id" }).select("id").single(); if (error) throw new Error(error.message); return { ok: result.ok, status: result.status, provider: data.provider, displayName, externalId: result.externalId, connectionId, error: result.error }; } catch (error) { return { ok: false as const, error: error instanceof Error ? error.message : "Connection failed." }; } });
