/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthChangePasswordRouteImport } from './routes/auth.change-password'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformAgenticStudioRouteImport } from './routes/platform.agentic-studio'
import { Route as PlatformAgentsRouteImport } from './routes/platform.agents'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform.analytics'
import { Route as PlatformAuditRouteImport } from './routes/platform.audit'
import { Route as PlatformChatRouteImport } from './routes/platform.chat'
import { Route as PlatformGovernanceRouteImport } from './routes/platform.governance'
import { Route as PlatformIntegrationsRouteImport } from './routes/platform.integrations'
import { Route as PlatformInvestigationsRouteImport } from './routes/platform.investigations'
import { Route as PlatformMarketplaceRouteImport } from './routes/platform.marketplace'
import { Route as PlatformOperationalConsoleRouteImport } from './routes/platform.operational-console'
import { Route as PlatformReportsRouteImport } from './routes/platform.reports'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformUsersRouteImport } from './routes/platform.users'
import { Route as ResourcesWhatIsAiopsRouteImport } from './routes/resources.what-is-aiops'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiInternalProviderSyncRouteImport } from './routes/api.internal.provider-sync'
import { Route as IntegrationsGenesysCallbackRouteImport } from './routes/integrations.genesys.callback'
import { Route as IntegrationsGithubSetupRouteImport } from './routes/integrations.github.setup'
import { Route as PlatformAgentEvaluationRunIdRouteImport } from './routes/platform.agent-evaluation.$runId'
import { Route as PlatformAgentRunRunIdRouteImport } from './routes/platform.agent-run.$runId'
import { Route as PlatformAgentAgentKeyRouteImport } from './routes/platform.agent.$agentKey'
import { Route as PlatformApprovalsIndexRouteImport } from './routes/platform.approvals.index'
import { Route as PlatformApprovalsIdRouteImport } from './routes/platform.approvals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAgenticStudioRoute = PlatformAgenticStudioRouteImport.update({
  id: '/agentic-studio',
  path: '/agentic-studio',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAgentsRoute = PlatformAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformChatRoute = PlatformChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformGovernanceRoute = PlatformGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformIntegrationsRoute = PlatformIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformInvestigationsRoute = PlatformInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformMarketplaceRoute = PlatformMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOperationalConsoleRoute =
  PlatformOperationalConsoleRouteImport.update({
    id: '/operational-console',
    path: '/operational-console',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformReportsRoute = PlatformReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const ResourcesWhatIsAiopsRoute = ResourcesWhatIsAiopsRouteImport.update({
  id: '/resources/what-is-aiops',
  path: '/resources/what-is-aiops',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalProviderSyncRoute = ApiInternalProviderSyncRouteImport.update({
  id: '/api/internal/provider-sync',
  path: '/api/internal/provider-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGenesysCallbackRoute =
  IntegrationsGenesysCallbackRouteImport.update({
    id: '/integrations/genesys/callback',
    path: '/integrations/genesys/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsGithubSetupRoute = IntegrationsGithubSetupRouteImport.update({
  id: '/integrations/github/setup',
  path: '/integrations/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAgentEvaluationRunIdRoute =
  PlatformAgentEvaluationRunIdRouteImport.update({
    id: '/agent-evaluation/$runId',
    path: '/agent-evaluation/$runId',
    getParentRoute: () => PlatformRoute,
  } as any)
const PlatformAgentRunRunIdRoute = PlatformAgentRunRunIdRouteImport.update({
  id: '/agent-run/$runId',
  path: '/agent-run/$runId',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAgentAgentKeyRoute = PlatformAgentAgentKeyRouteImport.update({
  id: '/agent/$agentKey',
  path: '/agent/$agentKey',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformApprovalsIndexRoute = PlatformApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformApprovalsIdRoute = PlatformApprovalsIdRouteImport.update({
  id: '/approvals/$id',
  path: '/approvals/$id',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/platform': typeof PlatformRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/platform/agentic-studio': typeof PlatformAgenticStudioRoute
  '/platform/agents': typeof PlatformAgentsRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/chat': typeof PlatformChatRoute
  '/platform/governance': typeof PlatformGovernanceRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/investigations': typeof PlatformInvestigationsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/operational-console': typeof PlatformOperationalConsoleRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/resources/what-is-aiops': typeof ResourcesWhatIsAiopsRoute
  '/platform/': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/provider-sync': typeof ApiInternalProviderSyncRoute
  '/integrations/genesys/callback': typeof IntegrationsGenesysCallbackRoute
  '/integrations/github/setup': typeof IntegrationsGithubSetupRoute
  '/platform/agent-evaluation/$runId': typeof PlatformAgentEvaluationRunIdRoute
  '/platform/agent-run/$runId': typeof PlatformAgentRunRunIdRoute
  '/platform/agent/$agentKey': typeof PlatformAgentAgentKeyRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/platform/approvals/': typeof PlatformApprovalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/platform/agentic-studio': typeof PlatformAgenticStudioRoute
  '/platform/agents': typeof PlatformAgentsRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/chat': typeof PlatformChatRoute
  '/platform/governance': typeof PlatformGovernanceRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/investigations': typeof PlatformInvestigationsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/operational-console': typeof PlatformOperationalConsoleRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/resources/what-is-aiops': typeof ResourcesWhatIsAiopsRoute
  '/platform': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/provider-sync': typeof ApiInternalProviderSyncRoute
  '/integrations/genesys/callback': typeof IntegrationsGenesysCallbackRoute
  '/integrations/github/setup': typeof IntegrationsGithubSetupRoute
  '/platform/agent-evaluation/$runId': typeof PlatformAgentEvaluationRunIdRoute
  '/platform/agent-run/$runId': typeof PlatformAgentRunRunIdRoute
  '/platform/agent/$agentKey': typeof PlatformAgentAgentKeyRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/platform/approvals': typeof PlatformApprovalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/platform': typeof PlatformRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/platform/agentic-studio': typeof PlatformAgenticStudioRoute
  '/platform/agents': typeof PlatformAgentsRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/chat': typeof PlatformChatRoute
  '/platform/governance': typeof PlatformGovernanceRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/investigations': typeof PlatformInvestigationsRoute
  '/platform/marketplace': typeof PlatformMarketplaceRoute
  '/platform/operational-console': typeof PlatformOperationalConsoleRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/resources/what-is-aiops': typeof ResourcesWhatIsAiopsRoute
  '/platform/': typeof PlatformIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/provider-sync': typeof ApiInternalProviderSyncRoute
  '/integrations/genesys/callback': typeof IntegrationsGenesysCallbackRoute
  '/integrations/github/setup': typeof IntegrationsGithubSetupRoute
  '/platform/agent-evaluation/$runId': typeof PlatformAgentEvaluationRunIdRoute
  '/platform/agent-run/$runId': typeof PlatformAgentRunRunIdRoute
  '/platform/agent/$agentKey': typeof PlatformAgentAgentKeyRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/platform/approvals/': typeof PlatformApprovalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/platform'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/change-password'
    | '/platform/agentic-studio'
    | '/platform/agents'
    | '/platform/analytics'
    | '/platform/audit'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/integrations'
    | '/platform/investigations'
    | '/platform/marketplace'
    | '/platform/operational-console'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform/users'
    | '/resources/what-is-aiops'
    | '/platform/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/provider-sync'
    | '/integrations/genesys/callback'
    | '/integrations/github/setup'
    | '/platform/agent-evaluation/$runId'
    | '/platform/agent-run/$runId'
    | '/platform/agent/$agentKey'
    | '/platform/approvals/$id'
    | '/platform/approvals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/change-password'
    | '/platform/agentic-studio'
    | '/platform/agents'
    | '/platform/analytics'
    | '/platform/audit'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/integrations'
    | '/platform/investigations'
    | '/platform/marketplace'
    | '/platform/operational-console'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform/users'
    | '/resources/what-is-aiops'
    | '/platform'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/provider-sync'
    | '/integrations/genesys/callback'
    | '/integrations/github/setup'
    | '/platform/agent-evaluation/$runId'
    | '/platform/agent-run/$runId'
    | '/platform/agent/$agentKey'
    | '/platform/approvals/$id'
    | '/platform/approvals'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/platform'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/change-password'
    | '/platform/agentic-studio'
    | '/platform/agents'
    | '/platform/analytics'
    | '/platform/audit'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/integrations'
    | '/platform/investigations'
    | '/platform/marketplace'
    | '/platform/operational-console'
    | '/platform/reports'
    | '/platform/settings'
    | '/platform/users'
    | '/resources/what-is-aiops'
    | '/platform/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/provider-sync'
    | '/integrations/genesys/callback'
    | '/integrations/github/setup'
    | '/platform/agent-evaluation/$runId'
    | '/platform/agent-run/$runId'
    | '/platform/agent/$agentKey'
    | '/platform/approvals/$id'
    | '/platform/approvals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  McpRoute: typeof McpRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ResourcesWhatIsAiopsRoute: typeof ResourcesWhatIsAiopsRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiInternalProviderSyncRoute: typeof ApiInternalProviderSyncRoute
  IntegrationsGenesysCallbackRoute: typeof IntegrationsGenesysCallbackRoute
  IntegrationsGithubSetupRoute: typeof IntegrationsGithubSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/agentic-studio': {
      id: '/platform/agentic-studio'
      path: '/agentic-studio'
      fullPath: '/platform/agentic-studio'
      preLoaderRoute: typeof PlatformAgenticStudioRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/agents': {
      id: '/platform/agents'
      path: '/agents'
      fullPath: '/platform/agents'
      preLoaderRoute: typeof PlatformAgentsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/chat': {
      id: '/platform/chat'
      path: '/chat'
      fullPath: '/platform/chat'
      preLoaderRoute: typeof PlatformChatRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/governance': {
      id: '/platform/governance'
      path: '/governance'
      fullPath: '/platform/governance'
      preLoaderRoute: typeof PlatformGovernanceRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/integrations': {
      id: '/platform/integrations'
      path: '/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof PlatformIntegrationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/investigations': {
      id: '/platform/investigations'
      path: '/investigations'
      fullPath: '/platform/investigations'
      preLoaderRoute: typeof PlatformInvestigationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/marketplace': {
      id: '/platform/marketplace'
      path: '/marketplace'
      fullPath: '/platform/marketplace'
      preLoaderRoute: typeof PlatformMarketplaceRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/operational-console': {
      id: '/platform/operational-console'
      path: '/operational-console'
      fullPath: '/platform/operational-console'
      preLoaderRoute: typeof PlatformOperationalConsoleRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/reports': {
      id: '/platform/reports'
      path: '/reports'
      fullPath: '/platform/reports'
      preLoaderRoute: typeof PlatformReportsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/resources/what-is-aiops': {
      id: '/resources/what-is-aiops'
      path: '/resources/what-is-aiops'
      fullPath: '/resources/what-is-aiops'
      preLoaderRoute: typeof ResourcesWhatIsAiopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/provider-sync': {
      id: '/api/internal/provider-sync'
      path: '/api/internal/provider-sync'
      fullPath: '/api/internal/provider-sync'
      preLoaderRoute: typeof ApiInternalProviderSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/genesys/callback': {
      id: '/integrations/genesys/callback'
      path: '/integrations/genesys/callback'
      fullPath: '/integrations/genesys/callback'
      preLoaderRoute: typeof IntegrationsGenesysCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/github/setup': {
      id: '/integrations/github/setup'
      path: '/integrations/github/setup'
      fullPath: '/integrations/github/setup'
      preLoaderRoute: typeof IntegrationsGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/agent-evaluation/$runId': {
      id: '/platform/agent-evaluation/$runId'
      path: '/agent-evaluation/$runId'
      fullPath: '/platform/agent-evaluation/$runId'
      preLoaderRoute: typeof PlatformAgentEvaluationRunIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/agent-run/$runId': {
      id: '/platform/agent-run/$runId'
      path: '/agent-run/$runId'
      fullPath: '/platform/agent-run/$runId'
      preLoaderRoute: typeof PlatformAgentRunRunIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/agent/$agentKey': {
      id: '/platform/agent/$agentKey'
      path: '/agent/$agentKey'
      fullPath: '/platform/agent/$agentKey'
      preLoaderRoute: typeof PlatformAgentAgentKeyRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/approvals/': {
      id: '/platform/approvals/'
      path: '/approvals'
      fullPath: '/platform/approvals/'
      preLoaderRoute: typeof PlatformApprovalsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/approvals/$id': {
      id: '/platform/approvals/$id'
      path: '/approvals/$id'
      fullPath: '/platform/approvals/$id'
      preLoaderRoute: typeof PlatformApprovalsIdRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformRouteChildren {
  PlatformAgenticStudioRoute: typeof PlatformAgenticStudioRoute
  PlatformAgentsRoute: typeof PlatformAgentsRoute
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformChatRoute: typeof PlatformChatRoute
  PlatformGovernanceRoute: typeof PlatformGovernanceRoute
  PlatformIntegrationsRoute: typeof PlatformIntegrationsRoute
  PlatformInvestigationsRoute: typeof PlatformInvestigationsRoute
  PlatformMarketplaceRoute: typeof PlatformMarketplaceRoute
  PlatformOperationalConsoleRoute: typeof PlatformOperationalConsoleRoute
  PlatformReportsRoute: typeof PlatformReportsRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformAgentEvaluationRunIdRoute: typeof PlatformAgentEvaluationRunIdRoute
  PlatformAgentRunRunIdRoute: typeof PlatformAgentRunRunIdRoute
  PlatformAgentAgentKeyRoute: typeof PlatformAgentAgentKeyRoute
  PlatformApprovalsIdRoute: typeof PlatformApprovalsIdRoute
  PlatformApprovalsIndexRoute: typeof PlatformApprovalsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAgenticStudioRoute: PlatformAgenticStudioRoute,
  PlatformAgentsRoute: PlatformAgentsRoute,
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformChatRoute: PlatformChatRoute,
  PlatformGovernanceRoute: PlatformGovernanceRoute,
  PlatformIntegrationsRoute: PlatformIntegrationsRoute,
  PlatformInvestigationsRoute: PlatformInvestigationsRoute,
  PlatformMarketplaceRoute: PlatformMarketplaceRoute,
  PlatformOperationalConsoleRoute: PlatformOperationalConsoleRoute,
  PlatformReportsRoute: PlatformReportsRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformUsersRoute: PlatformUsersRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformAgentEvaluationRunIdRoute: PlatformAgentEvaluationRunIdRoute,
  PlatformAgentRunRunIdRoute: PlatformAgentRunRunIdRoute,
  PlatformAgentAgentKeyRoute: PlatformAgentAgentKeyRoute,
  PlatformApprovalsIdRoute: PlatformApprovalsIdRoute,
  PlatformApprovalsIndexRoute: PlatformApprovalsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  McpRoute: McpRoute,
  PlatformRoute: PlatformRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ResourcesWhatIsAiopsRoute: ResourcesWhatIsAiopsRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiInternalProviderSyncRoute: ApiInternalProviderSyncRoute,
  IntegrationsGenesysCallbackRoute: IntegrationsGenesysCallbackRoute,
  IntegrationsGithubSetupRoute: IntegrationsGithubSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
