export type HelpSection = {
  heading: string;
  body: string;
  bullets?: string[];
  steps?: string[];
};

export type HelpTopic = {
  id: string;
  title: string;
  group: "Getting started" | "Core control plane" | "Configuration deep-dives" | "Operations";
  summary: string;
  sections: HelpSection[];
  relatedRoutes?: Array<{ label: string; to: string; topic?: string }>;
};

const s = (heading: string, body: string, bullets?: string[], steps?: string[]): HelpSection => ({ heading, body, bullets, steps });

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: "platform-overview",
    title: "Platform overview",
    group: "Getting started",
    summary: "CenOps is Aegis's AI Operations & Governance control plane: it collects operational evidence, applies governance, proposes governed actions, verifies outcomes, and records the audit trail.",
    sections: [
      s("What it is", "CenOps sits above enterprise execution systems rather than replacing them. Its working loop is Observe → Govern → Optimize → Act → Verify → Audit → Outcome.", ["Observe: connected providers and synchronized snapshots supply operational evidence.", "Govern: platform baselines, organization guardrails, instructions and permissions constrain AI behavior.", "Optimize: agents, analytics and investigations turn evidence into findings and recommendations.", "Act: recommendations become change records and, where a write-capable connector and authorization exist, an approved execution.", "Verify + Audit: post-action verification, post-sync evidence and audit records establish what actually happened."]),
      s("Use cases", "Use CenOps when you need one operational control plane for AI-enabled enterprise operations.", ["Investigate an operational finding using persisted evidence.", "Ask Copilot for an evidence-grounded answer within the user's department scope.", "Connect enterprise systems and synchronize provider evidence before using live views.", "Govern AI and write actions with mandatory guardrails and approvals."]),
      s("How it works", "The platform is evidence-first. A provider being listed in the catalog does not mean its data is live. Live evidence requires a valid connection plus a successful synchronization or provider snapshot. Demo mode is explicitly labeled and uses fixtures instead of external providers."),
      s("Prerequisites", "An authenticated user with access to a tenant/workspace. For live operational evidence, at least one supported provider must be connected and synchronized."),
      s("Step-by-step", "Use the main navigation to move from observation to governed action.", [ ], ["Open Command Center to see the current operational view.", "Connect an enterprise system in Integrations.", "Run or wait for a successful synchronization.", "Review AI Agents, Copilot, Investigations, Analytics and Audit using the resulting evidence.", "When a recommendation requires action, send it through Approval Center and verify the resulting state after execution and sync."]),
      s("Configuration options", "Workspace settings include organization metadata, security/AI-safety controls, approval requirements, rollback-plan generation, data masking, department access and environment mode."),
      s("Common mistakes / integrity notes", "Do not interpret a populated demo view as live provider evidence. Do not treat an approval record as proof that a provider mutation succeeded. Execution and verification are separate states."),
    ],
    relatedRoutes: [{label:"Command Center",to:"/"},{label:"Integrations",to:"/integrations"},{label:"Copilot",to:"/chat"},{label:"Analytics",to:"/analytics"}],
  },
  {
    id: "first-time-setup",
    title: "First-time setup checklist",
    group: "Getting started",
    summary: "A safe first run is: establish the workspace, configure people and departments, connect a real provider, synchronize it, then configure agents and governance.",
    sections: [
      s("What it is", "A practical sequence for moving from an authenticated empty workspace to a usable operational control plane."),
      s("Use cases", "Use this sequence for a new workspace, a new environment, or a production onboarding review.", ["Establish tenant identity and organization metadata.", "Set user roles and department boundaries.", "Connect only providers that have real credentials or OAuth/App authorization.", "Validate health and sync evidence before enabling dependent AI behavior."]),
      s("Prerequisites", "Admin access for workspace-level configuration and a real provider account for the first live integration."),
      s("Step-by-step", "Complete these in order.", [], ["Confirm organization name, domain and timezone in Settings.", "Invite workspace members from User Management and assign the least privilege role needed.", "Define department memberships and department-level agent/provider access where used.", "Connect a provider from Integrations using its supported auth flow.", "Run Sync Now and confirm health/last-sync evidence.", "Review Governance: platform baseline, organization guardrails, instructions and Simulator.", "Review AI Agents and deploy only the agents and bindings supported by the connected evidence.", "Use Command Center, Copilot and Investigations to validate the operational loop.", "Use Audit Viewer and Analytics to verify that activity is persisted and attributable."]),
      s("Common mistakes / integrity notes", "Do not bulk-enable agents before their required bindings and provider evidence exist. Do not assume a catalog icon means an integration is production-ready."),
    ],
    relatedRoutes: [{label:"Settings",to:"/settings"},{label:"Users",to:"/users"},{label:"Integrations",to:"/integrations"},{label:"Governance",to:"/governance"},{label:"AI Agents",to:"/agents"}],
  },
  {
    id: "tenants-organizations-environments",
    title: "Tenants, organizations & environments",
    group: "Getting started",
    summary: "A workspace is tenant-scoped. Environment mode distinguishes Demo from Live behavior and is visible in the application header.",
    sections: [
      s("What it is", "Tenant context is the security and data boundary used throughout the application. Organization metadata identifies the workspace, while environment mode determines whether the UI uses demo fixtures or live connected data."),
      s("Use cases", "Use environment mode to make a controlled demo or to explicitly return to evidence-backed live behavior.", ["Demo mode for presentations and training.", "Live mode for real provider evidence and operational workflows.", "Department assignments to isolate people, agents and integration instances within a tenant."]),
      s("How it works", "The app shell loads TenantProvider and RoleProvider for authenticated users. The header exposes Live/Demo mode. In Demo mode the product displays a DEMO MODE banner and fixture data; in Live mode the application uses connected workspace data and real empty/error states where evidence is unavailable."),
      s("Prerequisites", "Admin access is required to change the environment mode and workspace-wide settings."),
      s("Step-by-step", "Change workspace context carefully.", [], ["Open Settings to review organization and security controls.", "Use the Live/Demo control in the header when an administrator needs to change environment mode.", "Before switching to Live, confirm providers are connected and synchronized.", "Before using provider-backed actions, confirm the displayed mode is Live."]),
      s("Configuration options", "Organization name, primary domain, timezone, data masking, write approval requirement, rollback-plan generation and department isolation are tenant-scoped."),
      s("Common mistakes / integrity notes", "Demo mode is not a safe synonym for production. It explicitly replaces views with mock data. Live mode does not invent missing data; an unconnected provider produces an empty or error state."),
    ],
    relatedRoutes: [{label:"Settings",to:"/settings"},{label:"User Management",to:"/users"}],
  },
  {
    id: "roles-permissions",
    title: "Roles & permissions (User management)",
    group: "Getting started",
    summary: "Workspace membership is role-based. The current UI exposes Admin, Manager, Analyst and Viewer roles, with sensitive administration protected server-side.",
    sections: [
      s("What it is", "User Management lists real authenticated workspace members and allows invitations/removal. The invite form assigns Viewer, Analyst, Manager or Admin."),
      s("Use cases", "Use roles to keep operational access proportional to responsibility.", ["Admin: workspace and security administration, including environment and department controls.", "Manager: operational management and approved configuration actions exposed by the product.", "Analyst: evidence, investigation, synchronization and analytical workflows available to the role.", "Viewer: read-focused access where permitted."]),
      s("How it works", "User membership is loaded from the authenticated tenant. Server functions enforce tenant and role checks rather than trusting browser-supplied tenant identifiers. Department membership adds another scoping layer for AI and provider evidence."),
      s("Prerequisites", "Administrative role for inviting/removing members and configuring department access."),
      s("Step-by-step", "Manage a team.", [], ["Open User Management.", "Invite a user with their full name, company email and role.", "After joining, review department membership in Settings.", "For department-scoped operations, assign only the departments, agents and provider instances the user needs.", "Remove a user from User Management when access should be revoked."]),
      s("Configuration options", "Roles, user membership, department memberships, department-to-agent bindings and department-to-provider-connection access are configurable from the administration surfaces."),
      s("Common mistakes / integrity notes", "A role label is not a substitute for authorization checks. The product also enforces tenant and department boundaries server-side."),
    ],
    relatedRoutes: [{label:"User Management",to:"/users"},{label:"Settings / Department isolation",to:"/settings"}],
  },
  {
    id: "command-center",
    title: "Command Center",
    group: "Core control plane",
    summary: "The main operational surface for observing findings, provider-backed signals and the health of governed operations.",
    sections: [
      s("What it is", "Command Center is the observation hub for the control plane. It should be read as a current operational view, not as an independent source of provider truth."),
      s("Use cases", "Start here for a high-level operational review, triage and navigation into deeper evidence."),
      s("How it works", "Command Center consumes the platform's persisted evidence and operational state. In Live mode, useful provider-backed data depends on successful connection and sync. In Demo mode, it shows clearly labeled mock data."),
      s("Prerequisites", "Authentication. For live provider signals, at least one connected and synchronized provider."),
      s("Step-by-step", "Review the control plane.", [], ["Confirm Live or Demo mode in the header.", "Review the current findings and operational signals.", "Open the linked investigation or provider detail for evidence.", "Use Approval Center only when a recommendation represents a governed change intent."]),
      s("Configuration options", "Most Command Center behavior is driven by integrations, agent configuration, governance and workspace environment mode rather than by a large Command Center settings form."),
      s("Common mistakes / integrity notes", "A blank live Command Center can be correct when there is no connected evidence. Do not populate live operational metrics with synthetic data merely to avoid an empty state."),
    ],
    relatedRoutes: [{label:"Command Center",to:"/"},{label:"Operational Console",to:"/operational-console"}],
  },
  {
    id: "integrations",
    title: "Integrations",
    group: "Core control plane",
    summary: "Integrations connect enterprise systems and create tenant-scoped provider connection instances whose credentials and evidence are managed server-side.",
    sections: [
      s("What it is", "The Integrations page is the control plane for provider instances. It supports multiple instances of the same provider and keeps connection metadata separate from secret credential payloads."),
      s("Use cases", "Connect the systems that supply operational evidence or support governed execution.", ["Genesys Cloud via its dedicated OAuth flow.", "GitHub via GitHub App installation.", "AWS via role assumption and external ID.", "OAuth providers such as Jira, Slack, Salesforce and ServiceNow.", "Credential-based providers where the product exposes a supported credential form."]),
      s("How it works", "The provider catalog describes available providers, but catalog presence is not proof of implementation depth. A connection is useful only after a real authentication/credential flow succeeds and live provider evidence can be synchronized."),
      s("Prerequisites", "Admin or manager access for connection management, plus provider-side credentials/authorization. Some flows require a provider-owned app configuration and redirect URI."),
      s("Step-by-step", "Connect and validate a provider.", [], ["Open Integrations.", "Choose a provider and review its documented authentication method.", "Complete the provider's OAuth, GitHub App, AWS role or credential flow.", "Confirm the connection appears with a truthful status.", "Use Sync Now where available and wait for a successful sync.", "Review last-sync/health evidence before relying on the provider in agents, Copilot or analytics."]),
      s("Configuration options", "Provider forms include environment/display name plus provider-specific identifiers such as OAuth client ID/secret, instance URLs, AWS role ARN/external ID, service-account material, API keys or token endpoints. Department scoping can grant a specific connection instance to a department."),
      s("Common mistakes / integrity notes", "Connected should mean authenticated and usable, not merely that a button was clicked. Failed means the connection requires remediation; Disconnected means it is no longer an active connection. Many providers in the catalog can still be partial or connector-specific."),
    ],
    relatedRoutes: [{label:"Integrations",to:"/integrations"}],
  },
  {
    id: "ai-agents",
    title: "AI Agents",
    group: "Core control plane",
    summary: "Agents turn governed operational evidence into repeatable analysis or action. Their runtime behavior is constrained by capabilities, integration bindings, tenant scope and governance.",
    sections: [
      s("What it is", "The Agents surface contains the platform's agent definitions and deployment/runtime controls. Definitions and tenant access are separate concerns: a globally defined agent can still require tenant-scoped bindings before it is usable."),
      s("Use cases", "Use agents for repeatable evidence collection, analysis, recommendations and tightly controlled operations."),
      s("How it works", "Agents reach integrations through server-side capability and authorization layers. They do not receive raw provider credentials. Real bindings point to live provider connections; mock bindings are explicit and should not be mistaken for production evidence."),
      s("Prerequisites", "A configured agent, appropriate tenant/department access, supported capabilities and any required connected provider instances."),
      s("Step-by-step", "Deploy and validate an agent.", [], ["Open AI Agents and select the relevant agent.", "Review its capabilities, bindings and deployment state.", "Confirm its provider/data sources are real and authorized for the tenant.", "Review Governance constraints that apply to its operations.", "Enable/deploy only after the required evidence and permissions exist.", "Inspect agent runs and results for evidence provenance rather than relying on narrative output alone."]),
      s("Configuration options", "Agent configuration includes enablement/deployment state, capabilities, provider bindings and department access. Agentic Studio also provides governance-oriented configuration surfaces."),
      s("Common mistakes / integrity notes", "Do not call an agent production-ready simply because its definition exists. The runtime must have supported real bindings and current evidence. If a required provider is absent, the correct state is unavailable or action-required."),
    ],
    relatedRoutes: [{label:"AI Agents",to:"/agents"},{label:"Agentic Studio",to:"/agentic-studio"},{label:"Agent Governance",to:"/agentic-studio/governance"}],
  },
  {
    id: "copilot",
    title: "CenOps Copilot (Chat)",
    group: "Core control plane",
    summary: "Copilot provides evidence-grounded operational answers within the user's tenant and, where configured, department scope.",
    sections: [
      s("What it is", "Chat is the conversational control surface for asking operational questions, inspecting evidence and turning a recommendation into a governed change proposal."),
      s("Use cases", "Ask for current operational facts, explanations of findings, provider context and recommended next actions."),
      s("How it works", "The session resolves tenant and department context before accessing provider-backed evidence. Answers should be grounded in persisted evidence; missing provider evidence should remain an explicit limitation rather than becoming a fabricated answer."),
      s("Prerequisites", "Authenticated access and any required department memberships/provider connections. Live answers depend on synchronized evidence."),
      s("Step-by-step", "Use Copilot safely.", [], ["Open Chat.", "Select or remain within the appropriate department scope.", "Ask a concrete operational question.", "Inspect cited evidence or evidence summaries returned with the answer.", "When a recommendation is appropriate, send it to Approval Center rather than executing directly.", "Use chat history to revisit prior investigation context."]),
      s("Configuration options", "Department membership and department access to agents/provider instances are managed in Settings. Governance and write-approval settings constrain downstream actions."),
      s("Common mistakes / integrity notes", "A plausible natural-language answer is not itself evidence. Treat provider sync freshness and cited evidence as the source of operational truth."),
    ],
    relatedRoutes: [{label:"CenOps Copilot",to:"/chat"},{label:"Department configuration",to:"/settings"}],
  },
  {
    id: "investigations",
    title: "Investigations / Vulnerabilities",
    group: "Core control plane",
    summary: "Investigations turn operational anomalies into evidence-backed findings with context, timelines and correlated signals.",
    sections: [
      s("What it is", "The Investigations surface is for structured triage of operational findings and vulnerabilities rather than free-form narrative alone."),
      s("Use cases", "Investigate provider health issues, changes, security findings and cross-system operational signals."),
      s("How it works", "A finding should carry evidence, timeline context, correlated signals and confidence so that a reviewer can distinguish observed facts from interpretation."),
      s("Prerequisites", "Live investigations require persisted provider evidence and/or platform operational records. Empty live state can be valid when no evidence exists."),
      s("Step-by-step", "Triage a finding.", [], ["Open Investigations.", "Select a finding with the relevant severity/status.", "Review the evidence and event timeline.", "Review any correlated provider changes and confidence indicators.", "Decide whether a recommendation warrants a governed change record.", "Send supported recommendations to Approval Center for authorization."]),
      s("Configuration options", "Investigations are driven mainly by evidence and connected providers. Provider-specific capabilities determine which findings can be collected."),
      s("Common mistakes / integrity notes", "A correlation is not automatically causation. Use the evidence and timeline fields to keep the reasoning explicit. Do not promote an unsupported hypothesis into a verified incident."),
    ],
    relatedRoutes: [{label:"Investigations",to:"/investigations"}],
  },
  {
    id: "approval-center",
    title: "Approval Center",
    group: "Core control plane",
    summary: "Approval Center records human authorization for proposed changes. Approval is a governance state, not proof of successful provider execution.",
    sections: [
      s("What it is", "The Approval Center manages change records and approval stages for governed operational actions."),
      s("Use cases", "Use it to review change intent, approve or reject proposals, and provide a clear human decision boundary before supported write execution."),
      s("How it works", "A recommendation becomes a change record. Reviewers can approve/reject, including supported bulk flows. An approved record can proceed to execution only when a write-capable authorized integration and execution gate exist. Verification must then confirm the resulting provider state."),
      s("Prerequisites", "A proposed change and a user with the appropriate approval permission. Provider-side write capability is a separate prerequisite for execution."),
      s("Step-by-step", "Review a change.", [], ["Open Approval Center.", "Review the proposed intent, scope, risk and evidence.", "Approve or reject using the available stage controls.", "If approved, monitor execution status if a supported connector exists.", "Review verification/post-sync evidence before calling the outcome successful."]),
      s("Configuration options", "Workspace settings can require approval for write actions and auto-generate rollback plans for new change proposals."),
      s("Common mistakes / integrity notes", "Approval is not execution. Execution is not verification. Verification is not complete until the post-change state is evidenced and, where applicable, synchronized back into the control plane."),
    ],
    relatedRoutes: [{label:"Approval Center",to:"/approvals"}],
  },
  {
    id: "governance",
    title: "Governance (Guardrails & Instructions)",
    group: "Core control plane",
    summary: "Governance combines non-bypassable platform controls with organization guardrails and advisory instructions.",
    sections: [
      s("What it is", "The Governance surface provides platform baseline guardrails, organization-authored guardrails, instructions/guidelines, simulator testing and activity/history."),
      s("Use cases", "Constrain AI behavior, control write actions, test policy outcomes and retain version history for explainability."),
      s("How it works", "Platform baseline guardrails are always evaluated and cannot be removed. Organization guardrails add tenant-specific controls without weakening the baseline. Instructions guide behavior but are not equivalent to mandatory guardrails. The server-side guardrail layer is the enforcement point."),
      s("Prerequisites", "Administrative or management permissions for authoring organization guardrails."),
      s("Step-by-step", "Create a guardrail.", [], ["Open Governance.", "Review Platform baseline controls first.", "Create or edit an organization guardrail when permitted.", "Choose scope, severity, effect and enforcement mode carefully.", "Use Simulator to test behavior before relying on the rule.", "Review version history and evaluation activity.", "Pair high-impact write restrictions with Approval Center policy."]),
      s("Configuration options", "Guardrails expose scope, type, severity, effect, enforcement mode, enablement and version history. Instructions are maintained separately as advisory guidance."),
      s("Common mistakes / integrity notes", "Never describe instructions as equivalent to server-enforced guardrails. A simulated result is not a live execution. A guardrail evaluation records a verdict; it does not itself prove an external provider mutation."),
    ],
    relatedRoutes: [{label:"Governance",to:"/governance"}],
  },
  {
    id: "analytics-reports",
    title: "Analytics & Reports",
    group: "Core control plane",
    summary: "Analytics turns persisted evidence, findings and AI-usage telemetry into time-bounded operational reporting.",
    sections: [
      s("What it is", "The Analytics surface provides time-range views, findings and AI usage metrics, plus report generation/management where implemented."),
      s("Use cases", "Use Analytics for operational review, trend analysis, AI usage visibility and report distribution."),
      s("How it works", "Analytics should consume the platform's persisted records. Provider-backed metrics become meaningful only after successful provider connection and synchronization. AI usage telemetry is a separate evidence stream and should not be conflated with provider health."),
      s("Prerequisites", "Authentication. Provider-backed analytics require connected/synchronized providers; AI usage views require telemetry."),
      s("Step-by-step", "Review analytics.", [], ["Open Analytics.", "Choose the relevant time range.", "Review findings and AI usage separately.", "Open provider-backed detail when a metric needs evidence.", "Generate or refresh reports using the available report controls."]),
      s("Configuration options", "Analytics settings include sensitive-data masking in workspace settings. Report parameters and time ranges are controlled on the Analytics surface."),
      s("Common mistakes / integrity notes", "Do not compare demo-mode metrics with live metrics as though they came from the same evidence population."),
    ],
    relatedRoutes: [{label:"Analytics",to:"/analytics"}],
  },
  {
    id: "audit-viewer",
    title: "Audit Viewer",
    group: "Core control plane",
    summary: "Audit Viewer is the historical accountability surface for changes, syncs, governance decisions and other operational events.",
    sections: [
      s("What it is", "Audit Viewer exposes persisted audit records so users can trace what happened, when, to which tenant/resource and under which correlation context."),
      s("Use cases", "Use audit for incident review, governance evidence, change accountability, connector troubleshooting and compliance export."),
      s("How it works", "Operational actions and sync workflows can emit audit records with action/entity context and correlation data. The audit record complements provider evidence; it does not replace external-system verification."),
      s("Prerequisites", "Authenticated access. More sensitive export/filter functions may be role-limited."),
      s("Step-by-step", "Trace an event.", [], ["Open Audit Viewer.", "Filter by time or event criteria.", "Locate the relevant action, entity and correlation ID.", "Cross-check the linked provider/sync/change record.", "Export audit data when your role and the screen allow it."]),
      s("Configuration options", "Audit filtering/export is screen-specific. Workspace data masking settings can reduce exposure of sensitive identifiers in AI/analytics views."),
      s("Common mistakes / integrity notes", "An audit event saying an operation was requested or approved is not identical to a verified provider state change."),
    ],
    relatedRoutes: [{label:"Audit Viewer",to:"/audit"}],
  },
  {
    id: "connect-provider",
    title: "How to connect a provider",
    group: "Configuration deep-dives",
    summary: "Choose the provider's real authentication model, complete authorization/credential validation, then synchronize and verify evidence before relying on it.",
    sections: [
      s("What it is", "A provider connection creates a tenant-scoped instance with server-managed credential material and non-secret operational metadata."),
      s("How it works", "Supported connection patterns include dedicated OAuth flows, GitHub App installation, AWS role assumption and provider-specific credential forms. The exact form is provider-specific and must not be inferred from the catalog alone."),
      s("Prerequisites", "Admin/manager privileges and the provider-side app/credentials needed by that integration. For OAuth, redirect URLs and scopes must match the configured provider application."),
      s("Step-by-step", "Connect a provider.", [], ["Open Integrations and choose the provider.", "Complete the provider's supported authorization flow.", "Wait for the connection to show its actual state.", "Run Sync Now where provided.", "Confirm health, last sync and resulting evidence.", "Only then use the connection in agents, Chat or live analytics."]),
      s("Configuration options", "Display name, environment and provider-specific connection settings are available. Department access can be granted to specific instances, which is important when Production and UAT are both connected."),
      s("Common mistakes / integrity notes", "Never paste credentials into chat or documentation. Never label a provider fully live until its authentication and synchronization path has succeeded. A failed OAuth callback or missing provider-side app configuration should surface as action-required, not as connected."),
    ],
    relatedRoutes: [{label:"Integrations",to:"/integrations"}],
  },
  {
    id: "deploy-agent",
    title: "How to deploy and configure an AI agent",
    group: "Configuration deep-dives",
    summary: "Deploy an agent only after its definition, capabilities, provider bindings, department scope and governance constraints are understood.",
    sections: [
      s("What it is", "Agent deployment makes a defined agent available to the intended tenant/department context. It does not automatically create provider capabilities or bypass governance."),
      s("How it works", "The runtime resolves tenant context, agent capabilities, provider bindings and guardrails before provider access. Credentials remain server-side and agents operate through governed server-side connectors."),
      s("Prerequisites", "Agent definition, supported capability, appropriate integration connection, tenant/department access and any required guardrails."),
      s("Step-by-step", "Configure safely.", [], ["Open AI Agents and select the agent detail page.", "Review the agent's capability requirements.", "Check real provider bindings and their current sync/health state.", "Configure department access where needed.", "Review governance policies affecting the agent.", "Enable/deploy and test with evidence-backed inputs.", "Inspect run results and evidence provenance after execution."]),
      s("Configuration options", "Deployment state, capabilities, provider connections, department access and governance controls vary by agent."),
      s("Common mistakes / integrity notes", "A mock binding is not a live provider. Enabling an agent without its required evidence source produces an incomplete configuration, not a production runtime."),
    ],
    relatedRoutes: [{label:"AI Agents",to:"/agents"},{label:"Agent detail example",to:"/agent/agent-license"},{label:"Agentic Studio",to:"/agentic-studio"}],
  },
  {
    id: "guardrails-manage",
    title: "How to create and manage guardrails",
    group: "Configuration deep-dives",
    summary: "Use organization guardrails for mandatory tenant-specific controls, then validate them with the Simulator and retain their version history.",
    sections: [
      s("What it is", "Organization guardrails are persistent policy records evaluated in the governed operation path."),
      s("Use cases", "Block risky writes, constrain data access, require specific operating conditions and create an auditable policy boundary."),
      s("How it works", "Platform baseline controls run first. Organization guardrails are layered on top. The system records evaluations so operators can inspect verdicts and reasons."),
      s("Prerequisites", "A role permitted to manage governance."),
      s("Step-by-step", "Author a guardrail.", [], ["Open Governance → Guardrails.", "Choose New guardrail.", "Define the scope, type, severity, action/effect and enforcement mode.", "Save the rule.", "Run it through Simulator with representative inputs.", "Review version history and Activity after rollout.", "Monitor for expected evaluation results during real operations."]),
      s("Configuration options", "Guardrail type, scope, severity, action/effect, enforcement mode and enabled state. Platform baseline controls cannot be edited or removed."),
      s("Common mistakes / integrity notes", "Changing an organization guardrail must never be used to weaken platform baseline protection. Test policy changes before enabling high-impact production restrictions."),
    ],
    relatedRoutes: [{label:"Governance",to:"/governance"}],
  },
  {
    id: "recommendation-to-change",
    title: "How recommendations become governed changes",
    group: "Configuration deep-dives",
    summary: "Recommendations are advisory until they enter the governed change path: recommendation → change record → approval → authorized execution → verification → audit.",
    sections: [
      s("What it is", "A change record is the explicit bridge between an AI recommendation and a governed operational action."),
      s("How it works", "Chat, agents or investigations can produce a recommendation. The product then records intent and context in a change record. Approval rules and guardrails are evaluated before an eligible write execution can occur."),
      s("Step-by-step", "Follow the change path.", [], ["Review the recommendation and evidence.", "Send the recommendation to Approval Center.", "Review change scope, risk, affected integration and rollback information.", "Approve/reject according to the required stage.", "Where supported, allow the authorized write-capable connector to execute.", "Verify the provider's post-change state.", "Run/post the provider synchronization if required.", "Review the resulting audit records and evidence."]),
      s("Common mistakes / integrity notes", "Never describe an approved change as successfully executed without verification. Never treat an LLM recommendation as an instruction to mutate an external system directly."),
    ],
    relatedRoutes: [{label:"Chat",to:"/chat"},{label:"Investigations",to:"/investigations"},{label:"Approval Center",to:"/approvals"},{label:"Audit",to:"/audit"}],
  },
  {
    id: "verification-audit",
    title: "How verification and audit work",
    group: "Configuration deep-dives",
    summary: "Verification closes the loop by proving the resulting external state; audit records preserve the decision and evidence trail.",
    sections: [
      s("What it is", "Verification is a post-action check against the provider or an authoritative persisted snapshot. Audit is the historical record of the action path."),
      s("How it works", "After an approved execution, a connector can verify the resulting resource state when it implements the necessary readback. A subsequent sync can refresh persisted evidence. Audit entries capture the governance and operational steps."),
      s("Prerequisites", "A provider connector with the required write and read capabilities, plus an execution path that records the action context."),
      s("Step-by-step", "Close a governed action.", [], ["Confirm the change record and approval.", "Execute only through an authorized connector.", "Read the target state back from the provider where supported.", "Record verification outcome.", "Synchronize provider evidence where needed.", "Inspect Audit Viewer for the complete chain."]),
      s("Common mistakes / integrity notes", "No verification implementation means the system should not claim the provider state is confirmed. Approval, execution, verification and audit are separate evidence states."),
    ],
    relatedRoutes: [{label:"Approval Center",to:"/approvals"},{label:"Audit",to:"/audit"},{label:"Integrations",to:"/integrations"}],
  },
  {
    id: "department-scoping-chat",
    title: "Department scoping in Chat",
    group: "Configuration deep-dives",
    summary: "Department scope narrows which users, agents and provider instances can contribute evidence to an AI session.",
    sections: [
      s("What it is", "Department isolation links users to departments and departments to agent keys and specific provider connection instances."),
      s("Use cases", "Prevent a Finance user from seeing Engineering evidence, or prevent an AI session from mixing Production and UAT data unless explicitly authorized."),
      s("How it works", "Settings exposes department data isolation. Administrators can assign users, agent access and specific integration instances. Chat resolves department scope server-side so the browser cannot simply request another tenant/department's data."),
      s("Prerequisites", "Administrator access to Settings and defined departments/providers."),
      s("Step-by-step", "Set department scope.", [], ["Open Settings → Department data isolation.", "Assign users to the correct departments.", "Select a department.", "Enable only the agents needed by that department.", "Enable only the specific provider connection instances needed by that department.", "Open Chat as a department user and confirm evidence is restricted to that scope."]),
      s("Configuration options", "User-to-department memberships, department-to-agent access and department-to-provider-connection access."),
      s("Common mistakes / integrity notes", "Multiple instances of the same provider are not interchangeable. Explicitly assign the intended instance, especially across Production/UAT or regional environments."),
    ],
    relatedRoutes: [{label:"Settings",to:"/settings"},{label:"Chat",to:"/chat"}],
  },
  {
    id: "demo-vs-live",
    title: "Demo mode vs Live mode",
    group: "Configuration deep-dives",
    summary: "Demo mode is intentionally synthetic and visibly labeled; Live mode uses real connected workspace data and exposes real empty/error states.",
    sections: [
      s("What it is", "The app header exposes a Live/Demo environment control for administrators. A Demo banner appears at the top of the application when demo mode is active."),
      s("Use cases", "Demo mode is for training, presentations and deterministic UX walkthroughs. Live mode is for operational work with real evidence."),
      s("How it works", "Switching to Demo replaces views with mock data and the fixtures do not contact external providers. Switching to Live removes mock views and shows connected workspace data; providers that are not connected can legitimately show empty or error states."),
      s("Prerequisites", "Administrator access to change environment mode."),
      s("Step-by-step", "Use modes correctly.", [], ["Check the header before interpreting data.", "Use Demo for safe demonstrations only.", "Switch to Live before production triage.", "After switching to Live, validate integrations and sync state before drawing operational conclusions."]),
      s("Common mistakes / integrity notes", "Never present a demo screenshot or finding as evidence from a real provider. Demo mode is explicitly labeled for this reason."),
    ],
    relatedRoutes: [{label:"Settings",to:"/settings"}],
  },
  {
    id: "sync-health-worker",
    title: "Sync, health, and job worker",
    group: "Operations",
    summary: "Operators should watch connection health, sync freshness and background job status; the worker is an operational dependency, not an implicit guarantee.",
    sections: [
      s("What it is", "Provider synchronization converts external provider state into persisted evidence used by Command Center, reports, Copilot and investigations."),
      s("How it works", "A sync authenticates to the provider, fetches current data, persists entities, reconciles missing entities where supported, records run status and updates last-success timestamps. GitHub has a dedicated connector with pagination and stale reconciliation; generic syncs cover supported providers such as Jira, Slack, Salesforce and ServiceNow. The job worker is only useful when a persistent worker host/process manager is actually provisioned."),
      s("Prerequisites", "Connected provider plus valid credentials/tokens and, for scheduled/background work, a functioning worker/queue environment."),
      s("Step-by-step", "Operate sync safely.", [], ["Check Integrations for connection state.", "Review last sync and health evidence.", "Run Sync Now during troubleshooting when the screen supports it.", "If a sync fails, inspect the operational error and provider auth state.", "For scheduled work, confirm the background worker/queue deployment exists and is healthy.", "Re-run the sync after remediation and verify a successful timestamp and evidence counts."]),
      s("Configuration options", "Provider-specific sync schedules and job-queue settings vary by connector. Edge/background functions should fail closed if the required worker queue configuration is absent."),
      s("Common mistakes / integrity notes", "A worker file existing in the repository is not proof that a persistent production worker is deployed. Do not claim background processing is live without host/process evidence."),
    ],
    relatedRoutes: [{label:"Integrations",to:"/integrations"},{label:"Operational Console",to:"/operational-console"}],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    group: "Operations",
    summary: "Most empty or unhealthy states can be reduced to one of four causes: wrong environment, missing connection, failed sync/authentication, or missing evidence/permission scope.",
    sections: [
      s("What it is", "A practical diagnostic path for empty views, failed syncs, authorization problems and missing evidence."),
      s("Common scenarios", "Start with the visible state, then work backward to the source.", ["Command Center empty in Live mode → confirm a real provider is connected and synchronized.", "Integration shows Failed → inspect provider credentials/OAuth configuration, then reconnect.", "Chat cannot answer a provider question → confirm department access and provider sync freshness.", "Agent cannot use a capability → inspect agent binding, provider availability and governance.", "Approval exists but nothing changed externally → check whether a write-capable connector and authorized execution path exist, then verify.", "Analytics is sparse → check selected time range and whether live telemetry/evidence exists.", "Audit lacks the expected event → inspect whether the operation path executed and whether the relevant audit writer succeeded."]),
      s("Step-by-step", "Use this order to avoid chasing symptoms.", [], ["Confirm Live vs Demo.", "Confirm tenant and department scope.", "Confirm provider connection status.", "Confirm health check/last sync.", "Inspect operational error text and correlation IDs.", "Re-run sync or reconnect when safe.", "Verify the resulting evidence count/timestamp.", "Only then escalate to application/runtime debugging."]),
      s("Integrity notes", "Do not repair an empty live state by inserting fake data. Fix the missing connection, sync, permission or evidence source instead."),
    ],
    relatedRoutes: [{label:"Integrations",to:"/integrations"},{label:"Operational Console",to:"/operational-console"},{label:"Audit",to:"/audit"},{label:"Settings",to:"/settings"}],
  },
];

export const HELP_GROUPS = ["Getting started", "Core control plane", "Configuration deep-dives", "Operations"] as const;

export const HELP_TOPIC_BY_ID = Object.fromEntries(HELP_TOPICS.map((topic) => [topic.id, topic])) as Record<string, HelpTopic>;
